import type { LinuxCommand } from '../linux-data';
import type { LinuxSwitch } from '../linux-switches';

/* More of the shell: finding your way around, and managing files. The records
   follow the same shape as the ones in linux-data and are merged into the
   catalogue there, group by group. */

export const commands: LinuxCommand[] = [
  // ── navigation ────────────────────────────────────────────────────────
  {
    slug: 'tree',
    cmd: 'tree',
    group: 'nav',
    pkg: 'tree',
    fn: 'Draws a directory and everything beneath it as an indented tree.',
    kicker: 'Linux · navigation',
    sub: 'a directory, drawn',
    lede: [
      { m: 'tree' },
      ' lists a directory recursively and ',
      { a: 'draws the nesting with lines' },
      ', so the shape of a project is visible at a glance. It is ',
      { b: 'not installed by default on most systems' },
      ' — one package away.',
    ],
    takeaway: ['ls shows one level; ', { a: 'tree shows how the levels fit together' }, '.'],
    points: [
      { k: 'Shows', v: 'Nested layout', note: 'directories and files' },
      { k: 'Limit depth', v: '-L NUM', note: 'or large trees scroll for ever' },
      { k: 'Ends with', v: 'A count', note: 'directories and files' },
      { k: 'Install', v: 'apt install tree', note: 'or dnf install tree' },
    ],
    session: {
      run: 'tree -L 2 project',
      prompt: '$',
      lines: [
        { text: 'project', n: 1 },
        { text: '├── README.md' },
        { text: '├── src', n: 2 },
        { text: '│   ├── app.py' },
        { text: '│   └── db', n: 3 },
        { text: '└── tests' },
        { text: '    └── test_app.py' },
        { text: '' },
        { text: '3 directories, 3 files', n: 4 },
      ],
      notes: [
        { t: 'The starting directory', d: 'Everything below is drawn relative to it. With no argument, tree starts from the current directory.' },
        { t: 'A branch is a directory', d: 'Entries drawn beneath src and indented are inside it. The vertical line shows that more entries of the parent follow.' },
        { t: '-L 2 stopped here', d: 'db is a directory, but its contents are a third level and were not shown.' },
        { t: 'The summary line', d: 'The starting directory itself is not counted: src, db and tests are the three.' },
      ],
    },
    recipes: [
      { run: 'tree -a', d: 'Includes hidden entries, whose names begin with a dot.' },
      { run: 'tree -d', d: 'Shows directories only, leaving the files out.' },
      { run: 'tree -h --du', d: 'Adds sizes, with each directory showing the total of its contents.' },
      { run: 'tree -I "node_modules|.git"', d: 'Leaves out anything matching a pattern.' },
    ],
    security: {
      lede: ['A drawn tree is ', { b: 'the fastest way to notice what should not be there' }, '.'],
      points: [
        { t: 'Review before publishing', d: 'Running tree -a on a web root or a repository shows stray .git directories, backups and .env files before someone else finds them.' },
        { t: 'Hidden is only hidden from ls', d: 'Without -a, dot files are left out. An audit that skips them skips where secrets usually are.' },
        { t: 'Pasting output', d: 'A tree of a home directory or server reveals user names, software and layout. Trim it before posting it in a public question.' },
      ],
    },
    protocols: [],
    related: ['ls', 'find'],
    footnote: 'Where tree is not installed, "find . -maxdepth 2" lists the same entries without the drawing.',
  },
  {
    slug: 'which',
    cmd: 'which',
    group: 'nav',
    pkg: 'debianutils',
    fn: 'Prints the full path of the program that a command name would run.',
    kicker: 'Linux · navigation',
    sub: 'where does this command live',
    lede: [
      { m: 'which' },
      ' searches the directories in PATH, in order, and ',
      { a: 'prints the first program that matches the name' },
      ' — the one the shell would run. It answers ',
      { b: '"is it installed, and which copy am I getting?"' },
    ],
    takeaway: ['When two versions are installed, ', { a: 'which tells you the one you are actually running' }, '.'],
    points: [
      { k: 'Searches', v: 'PATH', note: 'left to right' },
      { k: 'Prints', v: 'The first match', note: '-a prints them all' },
      { k: 'Finds', v: 'Programs only', note: 'not builtins or aliases' },
      { k: 'Nothing printed', v: 'Not found', note: 'exit status 1' },
    ],
    session: {
      run: 'which python3',
      prompt: '$',
      lines: [
        { text: '/usr/local/bin/python3', n: 1 },
        { text: 'which -a python3', run: true, n: 2 },
        { text: '/usr/local/bin/python3' },
        { text: '/usr/bin/python3' },
        { text: 'which cd', run: true, n: 3 },
        { text: 'type cd', run: true, n: 4 },
        { text: 'cd is a shell builtin' },
      ],
      notes: [
        { t: 'The copy that runs', d: 'Typing python3 runs this file. It was found first because /usr/local/bin comes before /usr/bin in PATH.' },
        { t: '-a shows every match', d: 'Two copies are installed. The system’s own is second, and is only reached by typing its full path.' },
        { t: 'No output for cd', d: 'cd is not a program on disk — it is built into the shell — so which finds nothing and prints nothing.' },
        { t: 'type knows more', d: 'type is part of the shell, so it also reports builtins, aliases and functions. Prefer it when which comes back empty.' },
      ],
    },
    recipes: [
      { run: 'echo $PATH', d: 'Shows the directories that are searched, in order.' },
      { run: 'type -a ls', d: 'Shows everything the name means: alias, builtin and file.' },
      { run: 'command -v git', d: 'The portable form, for use in scripts.' },
      { run: 'ls -l $(which python3)', d: 'Shows whether the program found is a real file or a link to another.' },
    ],
    security: {
      lede: ['The shell runs ', { b: 'the first match in PATH, whoever put it there' }, '.'],
      points: [
        { t: 'PATH hijacking', d: 'A program named ls placed in a directory that comes early in PATH runs instead of the real one. which shows when a common command resolves somewhere unexpected.' },
        { t: 'Never put . in PATH', d: 'With the current directory in PATH, entering a directory someone else controls can run their program in place of yours.' },
        { t: 'Use full paths in privileged scripts', d: 'A script run by root or cron should call /usr/bin/tar, not tar, so it cannot be redirected by a changed PATH.' },
      ],
    },
    protocols: [],
    related: ['find', 'ls'],
    footnote: 'which is a separate program on some systems and a shell builtin on others; the behaviour described is the same.',
  },
  {
    slug: 'locate',
    cmd: 'locate',
    group: 'nav',
    pkg: 'plocate',
    fn: 'Finds files by name almost instantly, by searching a prebuilt index instead of the disk.',
    kicker: 'Linux · navigation',
    sub: 'find by name, fast',
    lede: [
      { m: 'locate' },
      ' looks a name up in ',
      { a: 'a database of every path on the system' },
      ', rebuilt once a day. That makes it far quicker than find, and also means ',
      { b: 'it does not know about files created since the last update' },
      '.',
    ],
    takeaway: ['find walks the disk now; ', { a: 'locate reads yesterday’s list' }, ' — fast, but possibly out of date.'],
    points: [
      { k: 'Searches', v: 'An index', note: 'not the disk itself' },
      { k: 'Matches', v: 'Anywhere in the path', note: 'not just the file name' },
      { k: 'Refresh', v: 'sudo updatedb', note: 'otherwise daily' },
      { k: 'Speed', v: 'Near instant', note: 'even across the whole system' },
    ],
    session: {
      run: 'locate sshd_config',
      prompt: '$',
      lines: [
        { text: '/etc/ssh/sshd_config', n: 1 },
        { text: '/usr/share/man/man5/sshd_config.5.gz' },
        { text: 'locate -c "*.conf"', run: true, n: 2 },
        { text: '412' },
        { text: 'touch new-report.txt && locate new-report.txt', run: true, n: 3 },
        { text: 'sudo updatedb && locate new-report.txt', run: true, n: 4 },
        { text: '/home/user/new-report.txt' },
      ],
      notes: [
        { t: 'Every path containing the text', d: 'Both the configuration file and its manual page match, because the name appears in each path.' },
        { t: '-c counts instead of listing', d: 'A pattern with a wildcard must be quoted, or the shell expands it first.' },
        { t: 'A new file is not found', d: 'The file exists, but the index was built before it did. locate prints nothing.' },
        { t: 'updatedb rebuilds the index', d: 'After a refresh the file appears. On most systems a timer runs updatedb once a day.' },
      ],
    },
    recipes: [
      { run: 'locate -i readme', d: 'Ignores upper and lower case.' },
      { run: 'locate -b "\\hosts"', d: 'Matches the file name exactly, not any path containing the word.' },
      { run: 'locate -n 10 ".log"', d: 'Stops after the first ten results.' },
      { run: 'locate -e report.txt', d: 'Lists only the entries that still exist on disk.' },
    ],
    security: {
      lede: ['The index is ', { b: 'a map of the whole filesystem' }, ', so who may read it matters.'],
      points: [
        { t: 'Results respect permissions', d: 'Modern locate shows a user only the paths they could reach themselves, so the index does not leak the names of other users’ files.' },
        { t: 'A quick way to find secrets', d: 'Searching for id_rsa, .env or .kdbx across a machine takes a second. It is worth doing on your own systems first.' },
        { t: 'Stale by design', d: 'A file deleted today may still be listed, and one planted today will not be. Use find when the answer has to be current.' },
      ],
    },
    protocols: [],
    related: ['find', 'which'],
    footnote: 'The package is plocate on current Debian, Ubuntu and Fedora; older systems ship mlocate, which behaves the same way.',
  },
  {
    slug: 'stat',
    cmd: 'stat',
    group: 'nav',
    pkg: 'coreutils',
    fn: 'Prints everything the filesystem records about a file: size, owner, permissions, inode and all its timestamps.',
    kicker: 'Linux · navigation',
    sub: 'everything about one file',
    lede: [
      { m: 'stat' },
      ' prints a file’s metadata in full. Where ls -l gives one line, ',
      { a: 'stat gives the inode, the mode in octal, and three or four separate times' },
      ' — ',
      { b: 'the detail you need when a permission or a date does not add up' },
      '.',
    ],
    takeaway: ['A file has ', { a: 'three times, not one' }, ': when it was read, when its contents changed, and when its metadata changed.'],
    points: [
      { k: 'Shows', v: 'Metadata', note: 'never the contents' },
      { k: 'Mode', v: 'Octal and letters', note: '0644 and -rw-r--r--' },
      { k: 'Times', v: 'Access, Modify, Change', note: 'and Birth where supported' },
      { k: 'Custom output', v: '-c FORMAT', note: 'for scripts' },
    ],
    session: {
      run: 'stat notes.txt',
      prompt: '$',
      lines: [
        { text: '  File: notes.txt' },
        { text: '  Size: 2048       Blocks: 8          IO Block: 4096   regular file', n: 1 },
        { text: 'Device: 8,2  Inode: 1311234     Links: 1', n: 2 },
        { text: 'Access: (0644/-rw-r--r--)  Uid: ( 1000/    user)   Gid: ( 1000/    user)', n: 3 },
        { text: 'Access: 2026-09-30 11:02:14.000000000 +0530' },
        { text: 'Modify: 2026-09-30 10:40:51.000000000 +0530', n: 4 },
        { text: 'Change: 2026-09-30 10:41:03.000000000 +0530' },
        { text: ' Birth: 2026-09-28 09:12:40.000000000 +0530' },
      ],
      notes: [
        { t: 'Size and type', d: '2048 bytes, occupying 8 blocks of 512 bytes on disk, and an ordinary file rather than a directory or link.' },
        { t: 'The inode is the file’s real identity', d: 'A name is only a pointer to an inode. Links: 1 means one name points at this one.' },
        { t: 'Permissions both ways', d: '0644 is the octal form chmod takes; the letters are what ls shows. Owner and group are given as number and name.' },
        { t: 'Modify and Change are different', d: 'Modify is when the contents last changed. Change is when the metadata did — here a chmod or chown twelve seconds later.' },
      ],
    },
    recipes: [
      { run: 'stat -c "%a %U:%G %n" *', d: 'Prints octal mode, owner, group and name for every file here.' },
      { run: 'stat -c %s file.iso', d: 'Prints only the size in bytes.' },
      { run: 'stat -f /', d: 'Describes the filesystem rather than a file: type, block size, free space.' },
      { run: 'stat -L current', d: 'Follows a symbolic link and describes the file it points to.' },
    ],
    security: {
      lede: ['The three timestamps are ', { b: 'the basic evidence of what happened to a file' }, '.'],
      points: [
        { t: 'Change time is hard to forge', d: 'touch can set Access and Modify to any date, but the kernel sets Change itself. A Modify older than Change means the date was altered or the metadata was.' },
        { t: 'Check the octal mode', d: 'A leading 4 or 2 — 4755 — is set-uid or set-gid. stat shows it plainly where ls shows only an s in the letters.' },
        { t: 'Reading changes the access time', d: 'On some mounts every read updates Access. Investigators copy or mount read-only first, so looking does not overwrite the evidence.' },
      ],
    },
    protocols: [],
    related: ['ls', 'touch'],
    footnote: 'Birth, the creation time, is shown only on filesystems and kernels that record it; otherwise it appears as a dash.',
  },

  // ── file management ───────────────────────────────────────────────────
  {
    slug: 'rmdir',
    cmd: 'rmdir',
    group: 'files',
    pkg: 'coreutils',
    fn: 'Removes a directory, but only if it is empty.',
    kicker: 'Linux · file management',
    sub: 'remove an empty directory',
    lede: [
      { m: 'rmdir' },
      ' deletes a directory and ',
      { a: 'refuses if anything is still inside it' },
      '. That refusal is the point: ',
      { b: 'it cannot destroy files by accident' },
      ', which rm -r can.',
    ],
    takeaway: ['The safe way to remove a directory: ', { a: 'it only works when there is nothing to lose' }, '.'],
    points: [
      { k: 'Removes', v: 'Empty directories', note: 'and nothing else' },
      { k: 'If not empty', v: 'An error', note: 'nothing is deleted' },
      { k: 'Parents too', v: '-p', note: 'a/b/c, then a/b, then a' },
      { k: 'For full ones', v: 'rm -r', note: 'with care' },
    ],
    session: {
      run: 'rmdir old-reports',
      prompt: '$',
      lines: [
        { text: 'rmdir project', run: true, n: 1 },
        { text: "rmdir: failed to remove 'project': Directory not empty", n: 2 },
        { text: 'ls -a project', run: true, n: 3 },
        { text: '.  ..  .gitignore' },
        { text: 'rmdir -pv a/b/c', run: true, n: 4 },
        { text: "rmdir: removing directory, 'a/b/c'" },
        { text: "rmdir: removing directory, 'a/b'" },
        { text: "rmdir: removing directory, 'a'" },
      ],
      notes: [
        { t: 'Success is silent', d: 'old-reports was empty and is gone. Like most commands, rmdir prints nothing when it works.' },
        { t: 'A directory with contents is refused', d: 'Nothing was removed. The error is the safety feature doing its job.' },
        { t: 'It looked empty, but was not', d: 'A hidden file was inside. ls -a shows dot files; plain ls would have shown nothing.' },
        { t: '-p removes the chain', d: 'Each directory is removed once the one inside it has gone, as long as each is empty in turn.' },
      ],
    },
    recipes: [
      { run: 'rmdir dir1 dir2 dir3', d: 'Removes several empty directories at once.' },
      { run: 'find . -type d -empty -delete', d: 'Removes every empty directory beneath the current one.' },
      { run: 'rmdir --ignore-fail-on-non-empty */', d: 'Removes the empty ones and stays quiet about the rest.' },
      { run: 'rm -r project', d: 'Removes a directory and all its contents — the tool for when it is not empty.' },
    ],
    security: {
      lede: ['Choosing rmdir over rm -r is ', { b: 'a habit that prevents accidents' }, '.'],
      points: [
        { t: 'Prefer it in scripts', d: 'A cleanup script that uses rmdir fails loudly if a directory unexpectedly has contents, instead of deleting them.' },
        { t: 'Empty directories still matter', d: 'A mount point is an empty directory. Removing it makes the mount fail at next boot.' },
        { t: 'Removal needs write on the parent', d: 'What decides whether you may remove a directory is the permission on the directory that contains it, not on the directory itself.' },
      ],
    },
    protocols: [],
    related: ['mkdir', 'rm'],
    footnote: 'A directory containing only hidden files is not empty; rmdir will refuse it.',
  },
  {
    slug: 'ln',
    cmd: 'ln',
    group: 'files',
    pkg: 'coreutils',
    fn: 'Creates a link: a second name for a file, or a pointer to another path.',
    kicker: 'Linux · file management',
    sub: 'one file, another name',
    lede: [
      { m: 'ln' },
      ' makes links. A ',
      { a: 'symbolic link, made with -s, is a small file that points at another path' },
      ' — like a shortcut. A ',
      { b: 'hard link is a second name for the very same data' },
      ', indistinguishable from the first.',
    ],
    takeaway: ['A symbolic link points at ', { a: 'a name' }, '; a hard link points at ', { b: 'the data itself' }, '.'],
    points: [
      { k: 'Symbolic', v: 'ln -s target name', note: 'the common kind' },
      { k: 'Hard', v: 'ln target name', note: 'same inode, same disk only' },
      { k: 'Order', v: 'Target, then name', note: 'the same order as cp' },
      { k: 'Broken link', v: 'Target removed', note: 'the link remains, pointing nowhere' },
    ],
    session: {
      run: 'ln -s /var/www/site current',
      prompt: '$',
      lines: [
        { text: 'ls -l current', run: true },
        { text: 'lrwxrwxrwx 1 user user 13 Sep 30 12:01 current -> /var/www/site', n: 1 },
        { text: 'ln notes.txt notes-hard.txt', run: true, n: 2 },
        { text: 'ls -li notes.txt notes-hard.txt', run: true },
        { text: '1311234 -rw-r--r-- 2 user user 2048 Sep 30 10:40 notes-hard.txt', n: 3 },
        { text: '1311234 -rw-r--r-- 2 user user 2048 Sep 30 10:40 notes.txt' },
        { text: 'ln -sfn /var/www/site-v2 current', run: true, n: 4 },
      ],
      notes: [
        { t: 'A symbolic link', d: 'The leading l marks it, and the arrow shows where it points. Its size, 13, is just the length of the path it holds.' },
        { t: 'No -s: a hard link', d: 'A second name is added for the same file. Nothing is copied.' },
        { t: 'Same inode, link count 2', d: 'Both names show inode 1311234, and the count after the permissions is 2. Deleting one name leaves the data reachable by the other.' },
        { t: 'Repointing a link', d: '-f replaces the existing link and -n stops ln from descending into the directory it points at. This is how a release is switched over.' },
      ],
    },
    recipes: [
      { run: 'readlink -f current', d: 'Prints the final path a link resolves to.' },
      { run: 'ln -s ../shared/config.yml config.yml', d: 'A relative link, which keeps working if the whole tree is moved.' },
      { run: 'find . -xtype l', d: 'Finds broken symbolic links — ones whose target no longer exists.' },
      { run: 'unlink current', d: 'Removes a link without touching what it points to. rm does the same.' },
    ],
    security: {
      lede: ['A link makes a program ', { b: 'act on a different file from the one it named' }, '.'],
      points: [
        { t: 'Symlink attacks', d: 'If a privileged program writes to a predictable name in /tmp, a user can put a link there first and redirect the write to a file of their choosing.' },
        { t: 'Links out of a web root', d: 'A symbolic link inside a served directory can expose files outside it. Web servers have settings to refuse to follow them.' },
        { t: 'Hard links keep data alive', d: 'Deleting a file does not free it while another hard link exists. The kernel restricts hard-linking to files you do not own for this reason.' },
      ],
    },
    protocols: [],
    related: ['cp', 'ls'],
    footnote: 'Hard links cannot cross filesystems and cannot be made to directories; symbolic links can do both.',
  },
  {
    slug: 'zip',
    cmd: 'zip',
    group: 'files',
    pkg: 'zip',
    fn: 'Packs files into a compressed .zip archive that Windows and macOS open natively.',
    kicker: 'Linux · file management',
    sub: 'an archive everyone can open',
    lede: [
      { m: 'zip' },
      ' creates the archive format ',
      { a: 'every desktop system understands without extra software' },
      '. Unlike tar it compresses each file separately and ',
      { b: 'does not preserve Linux ownership' },
      ', so it is for sharing rather than for backups.',
    ],
    takeaway: ['tar.gz between Linux machines; ', { a: 'zip when the other end is Windows or macOS' }, '.'],
    points: [
      { k: 'Creates', v: '.zip files', note: 'compressed per file' },
      { k: 'Directories', v: 'Need -r', note: 'or only the empty directory is stored' },
      { k: 'Order', v: 'Archive, then files', note: 'zip out.zip in...' },
      { k: 'Opens with', v: 'unzip', note: 'a separate package' },
    ],
    session: {
      run: 'zip -r site.zip site/',
      prompt: '$',
      lines: [
        { text: '  adding: site/ (stored 0%)', n: 1 },
        { text: '  adding: site/index.html (deflated 63%)', n: 2 },
        { text: '  adding: site/css/ (stored 0%)' },
        { text: '  adding: site/css/style.css (deflated 71%)' },
        { text: 'zip -e secret.zip passwords.txt', run: true, n: 3 },
        { text: 'Enter password: ' },
        { text: 'Verify password: ' },
        { text: '  adding: passwords.txt (deflated 41%)', n: 4 },
      ],
      notes: [
        { t: 'Directories are stored, not compressed', d: 'A directory has no contents of its own, so there is nothing to shrink: 0%.' },
        { t: 'deflated is the saving', d: 'index.html became 63% smaller. Text compresses well; photos and video, already compressed, barely change.' },
        { t: '-e asks for a password', d: 'The password is not shown as it is typed. It is asked twice to catch a mistake.' },
        { t: 'The names are still visible', d: 'Encryption protects the contents only. Anyone can list the archive and see that it holds passwords.txt.' },
      ],
    },
    recipes: [
      { run: 'zip -r project.zip project -x "*.git*"', d: 'Leaves out everything matching a pattern.' },
      { run: 'zip -u site.zip site/index.html', d: 'Updates one file inside an existing archive.' },
      { run: 'zip -9 -r small.zip docs/', d: 'Uses the strongest compression, at the cost of time.' },
      { run: 'zip -d site.zip "site/old.html"', d: 'Deletes an entry from the archive.' },
    ],
    security: {
      lede: ['The password option is ', { b: 'weaker than it looks' }, '.'],
      points: [
        { t: 'Classic zip encryption is broken', d: 'The default scheme used by -e can be cracked quickly. For anything sensitive use 7z with AES, or encrypt the file with gpg or age.' },
        { t: 'Do not put the password on the command line', d: '-P password leaves it in your shell history and visible to other users in the process list. Use -e and type it.' },
        { t: 'Ownership is lost', d: 'A zip does not record Linux owners, and may not keep permissions. Restoring a system from one will not give back what you had.' },
      ],
    },
    protocols: [],
    related: ['unzip', 'tar'],
    footnote: 'zip and unzip are separate packages and neither is installed by default on a minimal system.',
  },
  {
    slug: 'unzip',
    cmd: 'unzip',
    group: 'files',
    pkg: 'unzip',
    fn: 'Lists, tests and extracts the contents of a .zip archive.',
    kicker: 'Linux · file management',
    sub: 'open a zip archive',
    lede: [
      { m: 'unzip' },
      ' extracts a zip archive into the current directory, ',
      { a: 'recreating the directories stored inside it' },
      '. It can also ',
      { b: 'list or test an archive without extracting anything' },
      ', which is the sensible first step.',
    ],
    takeaway: ['List first with -l, then extract with ', { a: '-d into a directory of your choosing' }, '.'],
    points: [
      { k: 'Extracts to', v: 'Current directory', note: 'unless -d names another' },
      { k: 'List only', v: '-l', note: 'nothing is written' },
      { k: 'If a file exists', v: 'It asks', note: '-o overwrites, -n never does' },
      { k: 'Test', v: '-t', note: 'checks the archive is intact' },
    ],
    session: {
      run: 'unzip -l site.zip',
      prompt: '$',
      lines: [
        { text: 'Archive:  site.zip' },
        { text: '  Length      Date    Time    Name', n: 1 },
        { text: '---------  ---------- -----   ----' },
        { text: '        0  2026-09-30 11:40   site/' },
        { text: '     4210  2026-09-30 11:38   site/index.html' },
        { text: '     1822  2026-09-29 17:03   site/css/style.css' },
        { text: '---------                     -------' },
        { text: '     6032                     3 files', n: 2 },
        { text: 'unzip site.zip -d /tmp/restore', run: true, n: 3 },
        { text: 'Archive:  site.zip' },
        { text: '   creating: /tmp/restore/site/' },
        { text: '  inflating: /tmp/restore/site/index.html', n: 4 },
      ],
      notes: [
        { t: 'A listing, nothing extracted', d: 'Each entry’s original size, date and stored path. Every path begins with site/, so extraction will create one tidy directory.' },
        { t: 'The total when unpacked', d: '6032 bytes across three entries. Worth a glance on a large download, to know the space it needs.' },
        { t: '-d chooses the destination', d: 'The directory is created if it does not exist. Without -d, files land wherever you are standing.' },
        { t: 'creating and inflating', d: 'Directories are created, compressed files are inflated back to full size.' },
      ],
    },
    recipes: [
      { run: 'unzip -t backup.zip', d: 'Tests every file in the archive for corruption.' },
      { run: 'unzip site.zip "site/css/*"', d: 'Extracts only the entries matching a pattern.' },
      { run: 'unzip -o update.zip', d: 'Overwrites existing files without asking.' },
      { run: 'unzip -q big.zip -d out', d: 'Extracts quietly, without listing every file.' },
    ],
    security: {
      lede: ['An archive from elsewhere is ', { b: 'a set of instructions to write files' }, ' on your machine.'],
      points: [
        { t: 'Always list first', d: 'An archive with no top directory scatters its files among yours. -l shows this before it happens; -d into an empty directory contains it.' },
        { t: 'Zip bombs', d: 'A few kilobytes can expand into terabytes. The listing shows the unpacked size; be wary of any archive whose total is absurd for its file size.' },
        { t: 'Paths that climb out', d: 'Entries named with ../ try to write outside the destination. Current unzip refuses them, but tools built on other libraries may not.' },
      ],
    },
    protocols: [],
    related: ['zip', 'tar'],
    footnote: 'For .tar.gz, .tar.xz and other tar archives use tar; for .7z and .rar, the 7z command.',
  },
  {
    slug: 'rsync',
    cmd: 'rsync',
    group: 'files',
    pkg: 'rsync',
    fn: 'Copies files between directories or machines, transferring only what has changed.',
    kicker: 'Linux · file management',
    sub: 'copy only the differences',
    lede: [
      { m: 'rsync' },
      ' synchronises one directory with another. It compares the two sides and ',
      { a: 'sends only the files — and the parts of files — that differ' },
      ', which makes a repeat run nearly instant. It works locally and, ',
      { b: 'over SSH, between machines' },
      '.',
    ],
    takeaway: ['cp copies everything every time; ', { a: 'rsync copies only what changed' }, '.'],
    points: [
      { k: 'Transfers', v: 'Only differences', note: 'by size and modification time' },
      { k: 'Usual switches', v: '-avh', note: 'archive, verbose, readable sizes' },
      { k: 'Remote', v: 'user@host:path', note: 'carried over SSH' },
      { k: 'Rehearse', v: '-n', note: 'a dry run that changes nothing' },
    ],
    session: {
      run: 'rsync -avh site/ backup/site/',
      prompt: '$',
      lines: [
        { text: 'sending incremental file list', n: 1 },
        { text: './' },
        { text: 'index.html' },
        { text: 'css/' },
        { text: 'css/style.css' },
        { text: '' },
        { text: 'sent 6.31K bytes  received 65 bytes  12.75K bytes/sec', n: 2 },
        { text: 'total size is 6.03K  speedup is 0.95' },
        { text: 'rsync -avhn --delete site/ user@192.0.2.10:/var/www/site/', run: true, n: 3 },
        { text: 'sending incremental file list' },
        { text: 'deleting old.html', n: 4 },
        { text: 'index.html' },
      ],
      notes: [
        { t: 'The files that needed sending', d: 'On a first run that is everything. The trailing slash on site/ means "the contents of site", not the directory itself.' },
        { t: 'The transfer summary', d: 'Run the same command again and "sent" drops to a few hundred bytes: nothing has changed, so nothing is copied.' },
        { t: 'A remote destination, rehearsed', d: 'user@host:path sends over SSH. -n makes this a dry run: it reports what would happen and changes nothing.' },
        { t: '--delete removes extras', d: 'old.html exists on the server but not locally, so a real run would delete it there. This is why the dry run comes first.' },
      ],
    },
    recipes: [
      { run: 'rsync -avh --progress big.iso user@192.0.2.10:', d: 'Copies one large file to a remote home directory, showing progress.' },
      { run: 'rsync -avh --exclude ".git" project/ backup/', d: 'Leaves out anything matching a pattern.' },
      { run: 'rsync -avhP user@192.0.2.10:/var/log/app/ logs/', d: 'Pulls from a remote machine. -P keeps partial files so an interrupted copy can resume.' },
      { run: 'rsync -a --delete src/ dst/', d: 'Makes dst an exact mirror of src, removing anything extra.' },
    ],
    security: {
      lede: ['With --delete, rsync is ', { b: 'a command that removes files on another machine' }, '.'],
      points: [
        { t: 'The trailing slash changes the meaning', d: '"site/" copies the contents; "site" copies the directory. Combined with --delete, getting it wrong can empty the destination. Rehearse with -n.' },
        { t: 'It runs over SSH', d: 'The transfer is encrypted and authenticated by SSH. The old rsync:// daemon protocol is neither, and should not face the internet.' },
        { t: 'A mirror is not a backup', d: 'A mirror copies deletions and corruption faithfully. A backup needs older versions too — see --link-dest, or a real backup tool.' },
      ],
    },
    protocols: ['ssh', 'tcp'],
    related: ['cp', 'scp'],
    footnote: 'rsync must be installed on both machines for a remote copy.',
  },
];

export const switches: Record<string, LinuxSwitch[]> = {
  tree: [
    { flag: '-L NUM', d: 'Descend only NUM levels deep.' },
    { flag: '-a', d: 'All: include hidden entries.' },
    { flag: '-d', d: 'List directories only.' },
    { flag: '-h', d: 'Print each file’s size in readable units.' },
    { flag: '-f', d: 'Print the full path of each entry.' },
    { flag: '-I PATTERN', d: 'Leave out entries matching the pattern.' },
  ],
  which: [
    { flag: '-a', d: 'Print every match in PATH, not only the first.' },
  ],
  locate: [
    { flag: '-i', d: 'Ignore case.' },
    { flag: '-c', d: 'Count the matches instead of listing them.' },
    { flag: '-n NUM', d: 'Stop after NUM results.' },
    { flag: '-b', d: 'Match against the file name only, not the whole path.' },
    { flag: '-e', d: 'List only entries that still exist.' },
    { flag: '-r REGEX', d: 'Match a regular expression.' },
  ],
  stat: [
    { flag: '-c FORMAT', d: 'Print only the fields named, such as %a for octal mode and %n for name.' },
    { flag: '-f', d: 'Describe the filesystem the file is on, not the file.' },
    { flag: '-L', d: 'Follow symbolic links and describe the target.' },
    { flag: '-t', d: 'Terse: print everything on one line, for scripts.' },
  ],
  rmdir: [
    { flag: '-p', d: 'Parents: remove each directory in the path as it becomes empty.' },
    { flag: '-v', d: 'Verbose: print each directory removed.' },
    { flag: '--ignore-fail-on-non-empty', d: 'Do not report an error for directories that are not empty.' },
  ],
  ln: [
    { flag: '-s', d: 'Symbolic: make a link that points to a path. Without it, a hard link.' },
    { flag: '-f', d: 'Force: replace a link or file that already has the name.' },
    { flag: '-n', d: 'Treat an existing link to a directory as a file, so it is replaced rather than entered.' },
    { flag: '-r', d: 'Relative: work out the relative path to the target for you.' },
    { flag: '-v', d: 'Verbose: print each link made.' },
  ],
  zip: [
    { flag: '-r', d: 'Recursive: include a directory and everything inside it.' },
    { flag: '-e', d: 'Encrypt: ask for a password.' },
    { flag: '-u', d: 'Update: add only files that are new or changed.' },
    { flag: '-d', d: 'Delete entries from an existing archive.' },
    { flag: '-x PATTERN', d: 'Exclude files matching the pattern.' },
    { flag: '-9', d: 'Best compression. -1 is fastest; -0 stores without compressing.' },
    { flag: '-q', d: 'Quiet: do not list each file.' },
  ],
  unzip: [
    { flag: '-l', d: 'List the contents without extracting.' },
    { flag: '-d DIR', d: 'Extract into this directory.' },
    { flag: '-o', d: 'Overwrite existing files without asking.' },
    { flag: '-n', d: 'Never overwrite an existing file.' },
    { flag: '-t', d: 'Test the archive for errors.' },
    { flag: '-q', d: 'Quiet: do not list each file.' },
  ],
  rsync: [
    { flag: '-a', d: 'Archive: recursive, and keep permissions, times, owners and links.' },
    { flag: '-v', d: 'Verbose: list each file transferred.' },
    { flag: '-h', d: 'Human-readable sizes.' },
    { flag: '-n', d: 'Dry run: show what would be done, change nothing.' },
    { flag: '-z', d: 'Compress data during transfer — helps on a slow link.' },
    { flag: '-P', d: 'Show progress and keep partial files, so a transfer can resume.' },
    { flag: '--delete', d: 'Remove files from the destination that are not in the source.' },
    { flag: '--exclude=PATTERN', d: 'Skip files matching the pattern.' },
  ],
};
