import type { LinuxCommand } from '../linux-data';
import type { LinuxSwitch } from '../linux-switches';

/* More of the network: the older tools still met on every system, remote login
   and file transfer, scanning, and the firewall front ends.

   As in linux-data, every address is from a documentation or private range. */

export const commands: LinuxCommand[] = [
  // ── interfaces & addressing ───────────────────────────────────────────
  {
    slug: 'ifconfig',
    cmd: 'ifconfig',
    group: 'iface',
    pkg: 'net-tools',
    fn: 'The older command for showing and setting interface addresses — replaced by ip, but still met everywhere.',
    kicker: 'Linux · interfaces & addressing',
    sub: 'the classic interface tool',
    lede: [
      { m: 'ifconfig' },
      ' shows each network interface with its addresses and counters. It has been ',
      { a: 'superseded by the ip command and is no longer installed by default' },
      ', but ',
      { b: 'older guides, scripts and other Unix systems still use it' },
      ', so it is worth being able to read.',
    ],
    takeaway: ['Learn ', { a: 'ip addr' }, ' for new work; recognise ', { b: 'ifconfig' }, ' when you meet it.'],
    points: [
      { k: 'Shows', v: 'Interfaces', note: 'addresses, MAC, counters' },
      { k: 'Replaced by', v: 'ip addr, ip link', note: 'from iproute2' },
      { k: 'Package', v: 'net-tools', note: 'not installed by default now' },
      { k: 'On Windows', v: 'ipconfig', note: 'a different command' },
    ],
    session: {
      run: 'ifconfig eth0',
      prompt: '$',
      lines: [
        { text: 'eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500', n: 1 },
        { text: '        inet 192.168.1.42  netmask 255.255.255.0  broadcast 192.168.1.255', n: 2 },
        { text: '        inet6 fe80::5054:ff:fe12:3456  prefixlen 64  scopeid 0x20<link>' },
        { text: '        ether 52:54:00:12:34:56  txqueuelen 1000  (Ethernet)', n: 3 },
        { text: '        RX packets 184220  bytes 201938471 (201.9 MB)', n: 4 },
        { text: '        TX packets 96114  bytes 11820342 (11.8 MB)' },
      ],
      notes: [
        { t: 'State and MTU', d: 'UP means enabled and RUNNING means a cable or link is present. 1500 bytes is the usual Ethernet MTU.' },
        { t: 'The IPv4 address', d: 'The netmask is written out in full here; 255.255.255.0 is the same as the /24 that ip addr shows.' },
        { t: 'The MAC address', d: '"ether" is the hardware address of the interface.' },
        { t: 'Traffic counters', d: 'Packets and bytes received and sent since the interface came up. Errors and drops appear on these lines when there are any.' },
      ],
    },
    recipes: [
      { run: 'ip addr show eth0', d: 'The modern equivalent of the command above.' },
      { run: 'ifconfig -a', d: 'Shows every interface, including ones that are down.' },
      { run: 'sudo ifconfig eth0 down', d: 'Disables an interface. "ip link set eth0 down" is the current form.' },
      { run: 'ip -br addr', d: 'One line per interface — the quickest overview.' },
    ],
    security: {
      lede: ['An interface listing shows ', { b: 'every network the machine is attached to' }, '.'],
      points: [
        { t: 'PROMISC in the flags', d: 'An interface in promiscuous mode is accepting traffic not addressed to it — normal while tcpdump runs, suspicious otherwise.' },
        { t: 'Unexpected interfaces', d: 'A tun or tap interface means a VPN or tunnel is up. One nobody set up may be a path out of the network.' },
        { t: 'A MAC address is not proof', d: 'It can be changed with one command, so access control based on MAC addresses alone is easily bypassed.' },
      ],
    },
    protocols: ['ip4', 'ip6', 'eth'],
    related: ['ip-addr', 'ip-link'],
    footnote: 'Changes made with ifconfig or ip last only until reboot; permanent settings belong in netplan or NetworkManager.',
  },
  {
    slug: 'nmcli',
    cmd: 'nmcli',
    group: 'iface',
    pkg: 'network-manager',
    fn: 'Controls NetworkManager from the terminal: lists connections, joins Wi-Fi, and sets addresses that survive a reboot.',
    kicker: 'Linux · interfaces & addressing',
    sub: 'network settings that persist',
    lede: [
      { m: 'nmcli' },
      ' is the command-line face of NetworkManager, which manages networking on most desktops and many servers. Unlike ip, ',
      { a: 'what it configures is saved and applied again at boot' },
      ' — ',
      { b: 'a static address, a DNS server, a Wi-Fi password' },
      '.',
    ],
    takeaway: ['ip changes the network until reboot; ', { a: 'nmcli changes it for good' }, '.'],
    points: [
      { k: 'Overview', v: 'nmcli device status', note: 'each interface and its state' },
      { k: 'Saved profiles', v: 'nmcli connection show', note: 'the stored settings' },
      { k: 'Wi-Fi', v: 'nmcli device wifi list', note: 'scan and connect' },
      { k: 'Persistent', v: 'Yes', note: 'kept across reboots' },
    ],
    session: {
      run: 'nmcli device status',
      prompt: '$',
      lines: [
        { text: 'DEVICE  TYPE      STATE         CONNECTION', n: 1 },
        { text: 'eth0    ethernet  connected     Wired connection 1', n: 2 },
        { text: 'wlan0   wifi      disconnected  --' },
        { text: 'lo      loopback  unmanaged     --' },
        { text: 'nmcli device wifi connect "LabNet" --ask', run: true, n: 3 },
        { text: 'Password: ' },
        { text: "Device 'wlan0' successfully activated with 'f3a1c2d4-7b6e-4a90-8c11-2d5e9f0a1b3c'.", n: 4 },
      ],
      notes: [
        { t: 'One line per interface', d: 'The device, its type, whether it is connected, and which saved profile it is using.' },
        { t: 'Device and connection are different', d: 'eth0 is the hardware. "Wired connection 1" is a profile — a set of saved settings applied to it.' },
        { t: 'Joining a Wi-Fi network', d: '--ask prompts for the password instead of taking it on the command line, where it would be saved in your history.' },
        { t: 'Connected, and remembered', d: 'A profile has been saved. The machine will rejoin this network by itself next time.' },
      ],
    },
    recipes: [
      { run: 'nmcli connection show', d: 'Lists the saved connection profiles.' },
      { run: 'nmcli con mod "Wired connection 1" ipv4.addresses 192.168.1.50/24 ipv4.gateway 192.168.1.1 ipv4.method manual', d: 'Sets a static address on a profile.' },
      { run: 'nmcli con up "Wired connection 1"', d: 'Applies a profile after changing it.' },
      { run: 'nmtui', d: 'A menu-driven version of the same tool.' },
    ],
    security: {
      lede: ['Saved connections ', { b: 'store their passwords on disk' }, '.'],
      points: [
        { t: 'Wi-Fi passwords are saved', d: 'Profiles live in /etc/NetworkManager/system-connections, readable only by root, with the passphrase in plain text. A root compromise reveals every network the machine has joined.' },
        { t: 'Automatic rejoining', d: 'A laptop will connect to any network with a remembered name. Remove profiles for open and public networks so an impostor access point cannot claim it.' },
        { t: 'Changing settings over SSH', d: 'A wrong address or gateway cuts your own connection, and it stays wrong after a reboot. Have console access before changing a remote machine’s network.' },
      ],
    },
    protocols: ['ip4', 'ip6', 'dhcp', 'dns'],
    related: ['ip-addr', 'ifconfig'],
    footnote: 'Ubuntu Server uses netplan and systemd-networkd by default, where nmcli may not be managing the interfaces.',
  },

  // ── names ─────────────────────────────────────────────────────────────
  {
    slug: 'nslookup',
    cmd: 'nslookup',
    group: 'names',
    pkg: 'bind9-dnsutils',
    fn: 'Looks up a name in the DNS and prints the address — the simplest DNS query tool, found on Windows too.',
    kicker: 'Linux · names',
    sub: 'a quick DNS lookup',
    lede: [
      { m: 'nslookup' },
      ' asks a DNS server for a name and prints the answer. It shows less than dig, but ',
      { a: 'it works the same on Linux, macOS and Windows' },
      ', which makes it ',
      { b: 'the lookup command you can rely on finding' },
      '.',
    ],
    takeaway: ['The first test when a site will not load: ', { a: 'does the name resolve at all?' }],
    points: [
      { k: 'Asks', v: 'The system resolver', note: 'or a server you name' },
      { k: 'Prints', v: 'Server, then answer', note: 'two short blocks' },
      { k: 'Record type', v: '-type=MX', note: 'A is the default' },
      { k: 'More detail', v: 'dig', note: 'TTLs, flags, sections' },
    ],
    session: {
      run: 'nslookup example.com',
      prompt: '$',
      lines: [
        { text: 'Server:         127.0.0.53', n: 1 },
        { text: 'Address:        127.0.0.53#53' },
        { text: '' },
        { text: 'Non-authoritative answer:', n: 2 },
        { text: 'Name:   example.com' },
        { text: 'Address: 192.0.2.80', n: 3 },
        { text: 'nslookup -type=MX example.com 192.0.2.53', run: true, n: 4 },
        { text: 'example.com     mail exchanger = 10 mail.example.com.' },
      ],
      notes: [
        { t: 'Who was asked', d: 'The resolver that answered. 127.0.0.53 is systemd-resolved, the local stub on many systems; #53 is the port.' },
        { t: 'Non-authoritative', d: 'The answer came from a cache rather than from the server responsible for the domain. That is normal.' },
        { t: 'The answer', d: 'The IPv4 address the name resolves to.' },
        { t: 'A record type and a chosen server', d: '-type=MX asks which hosts receive mail for the domain, and the address at the end is the DNS server to ask instead of the default.' },
      ],
    },
    recipes: [
      { run: 'nslookup 192.0.2.80', d: 'A reverse lookup: the name for an address.' },
      { run: 'nslookup -type=NS example.com', d: 'Lists the name servers responsible for a domain.' },
      { run: 'nslookup -type=TXT example.com', d: 'Shows TXT records, where SPF and verification strings live.' },
      { run: 'dig +short example.com', d: 'The same lookup with dig, printing only the address.' },
    ],
    security: {
      lede: ['What a name resolves to ', { b: 'decides where your traffic goes' }, '.'],
      points: [
        { t: 'Compare resolvers', d: 'If your resolver and a public one give different addresses for the same name, either the site uses geo-routing or something is rewriting DNS.' },
        { t: 'DNS reveals infrastructure', d: 'MX, NS and TXT records disclose mail providers, hosting and third-party services. It is the first, entirely passive, step of reconnaissance.' },
        { t: 'Plain DNS is unencrypted', d: 'Lookups are visible to everyone on the path and can be forged. DNS over TLS or HTTPS protects them in transit.' },
      ],
    },
    protocols: ['dns', 'udp'],
    related: ['dig', 'host'],
    footnote: 'nslookup has an interactive mode too: run it with no arguments, then type names at its prompt.',
  },
  {
    slug: 'host',
    cmd: 'host',
    group: 'names',
    pkg: 'bind9-host',
    fn: 'Resolves a name to its addresses, or an address to its name, printing one plain sentence per record.',
    kicker: 'Linux · names',
    sub: 'DNS answers in plain words',
    lede: [
      { m: 'host' },
      ' is the shortest way to do a DNS lookup. ',
      { a: 'It prints each record as a sentence' },
      ' — "has address", "mail is handled by" — which makes it ',
      { b: 'easy to read and easy to use in scripts' },
      '.',
    ],
    takeaway: ['dig for the full picture; ', { a: 'host for a one-line answer' }, '.'],
    points: [
      { k: 'Forward', v: 'host NAME', note: 'addresses and mail servers' },
      { k: 'Reverse', v: 'host ADDRESS', note: 'the name for an IP' },
      { k: 'Record type', v: '-t TYPE', note: 'NS, MX, TXT, AAAA' },
      { k: 'Another server', v: 'host NAME SERVER', note: 'as a second argument' },
    ],
    session: {
      run: 'host example.com',
      prompt: '$',
      lines: [
        { text: 'example.com has address 192.0.2.80', n: 1 },
        { text: 'example.com has IPv6 address 2001:db8::80' },
        { text: 'example.com mail is handled by 10 mail.example.com.', n: 2 },
        { text: 'host 192.0.2.80', run: true, n: 3 },
        { text: '80.2.0.192.in-addr.arpa domain name pointer www.example.com.' },
        { text: 'host nosuchname.example', run: true, n: 4 },
        { text: 'Host nosuchname.example not found: 3(NXDOMAIN)' },
      ],
      notes: [
        { t: 'A and AAAA records', d: 'The IPv4 and IPv6 addresses. host asks for several record types at once.' },
        { t: 'The MX record', d: 'Mail for the domain goes to mail.example.com. The 10 is the priority; lower numbers are tried first.' },
        { t: 'A reverse lookup', d: 'The address is reversed and looked up under in-addr.arpa. The PTR record gives the name.' },
        { t: 'NXDOMAIN', d: 'The DNS says this name does not exist — different from a timeout, which would mean no server answered.' },
      ],
    },
    recipes: [
      { run: 'host -t NS example.com', d: 'Lists the domain’s name servers.' },
      { run: 'host -t TXT example.com', d: 'Shows its TXT records.' },
      { run: 'host example.com 192.0.2.53', d: 'Asks a particular DNS server.' },
      { run: 'host -a example.com', d: 'Asks for every record type and prints the full response.' },
    ],
    security: {
      lede: ['Forward and reverse lookups ', { b: 'that disagree are a useful warning' }, '.'],
      points: [
        { t: 'Reverse DNS as a check', d: 'Mail servers compare a sender’s address with its PTR record. A mismatch is one of the signals used to reject spam.' },
        { t: 'Names in logs can be chosen', d: 'Whoever controls an address block controls its PTR records, so a reverse name in a log is a claim, not a fact. Log the address too.' },
        { t: 'NXDOMAIN and timeout differ', d: '"Not found" is an answer; no reply at all means DNS is being blocked or is down. They call for different fixes.' },
      ],
    },
    protocols: ['dns', 'udp'],
    related: ['dig', 'nslookup'],
    footnote: 'host, dig and nslookup all come from the BIND project and query the DNS directly, bypassing /etc/hosts.',
  },

  // ── sockets & transfer ────────────────────────────────────────────────
  {
    slug: 'wget',
    cmd: 'wget',
    group: 'sockets',
    pkg: 'wget',
    fn: 'Downloads files from the web to disk, resuming interrupted transfers and following links if asked.',
    kicker: 'Linux · sockets & transfer',
    sub: 'download a file',
    lede: [
      { m: 'wget' },
      ' fetches a URL and ',
      { a: 'saves it as a file, under the name in the address' },
      '. It is built for downloading: it ',
      { b: 'retries, resumes a broken transfer, and can mirror a whole site' },
      '.',
    ],
    takeaway: ['curl prints a response to the screen; ', { a: 'wget saves it to a file' }, '.'],
    points: [
      { k: 'Saves to', v: 'A file', note: 'named from the URL' },
      { k: 'Resume', v: '-c', note: 'continue a partial download' },
      { k: 'Rename', v: '-O NAME', note: 'capital O' },
      { k: 'Follows', v: 'Redirects', note: 'by default' },
    ],
    session: {
      run: 'wget https://example.com/files/tool-1.4.tar.gz',
      prompt: '$',
      lines: [
        { text: 'Resolving example.com (example.com)... 192.0.2.80', n: 1 },
        { text: 'Connecting to example.com (example.com)|192.0.2.80|:443... connected.' },
        { text: 'HTTP request sent, awaiting response... 200 OK', n: 2 },
        { text: 'Length: 4821033 (4.6M) [application/gzip]' },
        { text: "Saving to: 'tool-1.4.tar.gz'" },
        { text: 'tool-1.4.tar.gz     100%[===================>]   4.60M  3.12MB/s    in 1.5s', n: 3 },
        { text: 'sha256sum tool-1.4.tar.gz', run: true, n: 4 },
        { text: '9f2c1e…a41b  tool-1.4.tar.gz' },
      ],
      notes: [
        { t: 'DNS, then TCP', d: 'The name is resolved and a connection opened to port 443 — the same steps any HTTPS client takes.' },
        { t: 'The server’s answer', d: '200 OK, followed by the size and type of what is about to arrive.' },
        { t: 'The progress bar', d: 'Percentage, bytes received, speed and time. The file is saved in the current directory.' },
        { t: 'Check what you got', d: 'Compare the checksum with the one the publisher lists. If they differ, the file is corrupt or not what it claims to be.' },
      ],
    },
    recipes: [
      { run: 'wget -c https://example.com/big.iso', d: 'Resumes a download that was cut off.' },
      { run: 'wget -O latest.tar.gz https://example.com/download', d: 'Saves under a name of your choosing.' },
      { run: 'wget -q -O - https://example.com/install.sh | less', d: 'Sends the download to a pager instead of a file, to read it first.' },
      { run: 'wget -i urls.txt', d: 'Downloads every URL listed in a file.' },
    ],
    security: {
      lede: ['A downloaded file is ', { b: 'someone else’s code arriving on your machine' }, '.'],
      points: [
        { t: 'Verify before you run', d: 'Check the SHA-256 checksum or GPG signature against the publisher’s. HTTPS proves which server you reached, not that the file is the right one.' },
        { t: 'Never pipe straight to a shell', d: '"wget -O - url | sh" runs whatever the server sends, unseen. Download it, read it, then run it.' },
        { t: 'Leave certificate checking on', d: '--no-check-certificate makes the download open to interception. Fix the certificate problem instead.' },
      ],
    },
    protocols: ['http', 'tls', 'tcp', 'dns', 'ftp'],
    related: ['curl', 'tar'],
    footnote: 'The checksum shown is shortened for the page; a real SHA-256 is 64 hexadecimal characters.',
  },
  {
    slug: 'ssh',
    cmd: 'ssh',
    group: 'sockets',
    pkg: 'openssh-client',
    fn: 'Opens an encrypted shell on another machine, and runs commands there as if you were sitting at it.',
    kicker: 'Linux · sockets & transfer',
    sub: 'a shell on another machine',
    lede: [
      { m: 'ssh' },
      ' — secure shell — logs you in to a remote host over an encrypted connection. ',
      { a: 'Everything you type and everything that comes back is protected' },
      ', and ',
      { b: 'the server proves its identity to you before you prove yours to it' },
      '. It is how servers are administered.',
    ],
    takeaway: [{ a: 'ssh user@host' }, ' — and from then on, your terminal is that machine’s.'],
    points: [
      { k: 'Form', v: 'ssh user@host', note: 'port 22 unless -p' },
      { k: 'Login by', v: 'Key or password', note: 'keys are stronger' },
      { k: 'One command', v: 'ssh host "cmd"', note: 'runs and returns' },
      { k: 'Leave', v: 'exit', note: 'or Ctrl+D' },
    ],
    session: {
      run: 'ssh deploy@192.0.2.10',
      prompt: '$',
      lines: [
        { text: "The authenticity of host '192.0.2.10 (192.0.2.10)' can't be established.", n: 1 },
        { text: 'ED25519 key fingerprint is SHA256:7Kq2nV0xJm4cP9rT1sYbA6dLwE3hZ8uFoGiN5tQpXyM.' },
        { text: 'Are you sure you want to continue connecting (yes/no/[fingerprint])? yes', n: 2 },
        { text: "Warning: Permanently added '192.0.2.10' (ED25519) to the list of known hosts." },
        { text: "deploy@192.0.2.10's password: ", n: 3 },
        { text: 'deploy@web01:~$ hostname', n: 4 },
        { text: 'web01' },
      ],
      notes: [
        { t: 'A host seen for the first time', d: 'ssh has no record of this server, so it shows the fingerprint of the server’s key and asks you to confirm.' },
        { t: 'Saying yes records the key', d: 'It is saved in ~/.ssh/known_hosts. On every later connection the server must present the same key, or ssh refuses loudly.' },
        { t: 'Now you prove who you are', d: 'With a password here; with a key, this prompt does not appear.' },
        { t: 'The prompt has changed', d: 'You are on web01 as deploy. Commands now run there, until you type exit.' },
      ],
    },
    recipes: [
      { run: 'ssh -p 2222 deploy@192.0.2.10', d: 'Connects to a server listening on another port.' },
      { run: 'ssh deploy@192.0.2.10 "df -h /"', d: 'Runs one command remotely and prints its output locally.' },
      { run: 'ssh -i ~/.ssh/work_key deploy@192.0.2.10', d: 'Uses a particular private key.' },
      { run: 'ssh -L 8080:localhost:80 deploy@192.0.2.10', d: 'Forwards local port 8080 to port 80 on the server, through the encrypted connection.' },
    ],
    security: {
      lede: ['SSH is ', { b: 'the front door of every server' }, ', and the most attacked service on the internet.'],
      points: [
        { t: 'Use keys, turn passwords off', d: 'Set "PasswordAuthentication no" and "PermitRootLogin no" in sshd_config once key login works. Password guessing then cannot succeed.' },
        { t: 'Take the host key warning seriously', d: '"REMOTE HOST IDENTIFICATION HAS CHANGED" means the server’s key differs from the one you saved: a rebuilt server, or someone in the middle. Find out which before continuing.' },
        { t: 'Forwarding crosses boundaries', d: '-L, -R and -D carry other traffic through the SSH connection, straight past a firewall. Useful, and exactly why it should be restricted on bastion hosts.' },
      ],
    },
    protocols: ['ssh', 'tcp'],
    related: ['scp', 'ssh-keygen'],
    footnote: 'Per-host settings — user, port, key — can be saved in ~/.ssh/config, so that "ssh web01" is enough.',
  },
  {
    slug: 'scp',
    cmd: 'scp',
    group: 'sockets',
    pkg: 'openssh-client',
    fn: 'Copies files between machines over SSH, with the same syntax as cp plus a host name.',
    kicker: 'Linux · sockets & transfer',
    sub: 'copy files over SSH',
    lede: [
      { m: 'scp' },
      ' is cp across the network. ',
      { a: 'A remote path is written user@host:path' },
      ', and the copy travels inside an SSH connection, so ',
      { b: 'it is encrypted and uses the same keys and passwords as ssh' },
      '.',
    ],
    takeaway: ['The colon is what makes it remote: ', { a: 'host:path' }, '. Without one, scp copies locally.'],
    points: [
      { k: 'Upload', v: 'scp file user@host:path', note: 'local to remote' },
      { k: 'Download', v: 'scp user@host:path .', note: 'remote to local' },
      { k: 'Directories', v: '-r', note: 'recursive' },
      { k: 'Port', v: '-P', note: 'capital, unlike ssh' },
    ],
    session: {
      run: 'scp site-backup.tar.gz deploy@192.0.2.10:/tmp/',
      prompt: '$',
      lines: [
        { text: 'site-backup.tar.gz                    100% 1215KB   4.1MB/s   00:00', n: 1 },
        { text: 'scp deploy@192.0.2.10:/var/log/app/app.log .', run: true, n: 2 },
        { text: 'app.log                               100%   21KB 310.2KB/s   00:00' },
        { text: 'scp -r site/ deploy@192.0.2.10:/var/www/', run: true, n: 3 },
        { text: 'index.html                            100% 4210   128.4KB/s   00:00' },
        { text: 'style.css                             100% 1822    61.0KB/s   00:00' },
      ],
      notes: [
        { t: 'An upload', d: 'The local file goes to /tmp on the server. The line shows the name, percentage, size, speed and time.' },
        { t: 'A download', d: 'The remote path comes first and the destination is the dot: the current directory.' },
        { t: 'A whole directory', d: '-r copies site and everything in it, printing a line for each file.' },
      ],
    },
    recipes: [
      { run: 'scp -P 2222 file deploy@192.0.2.10:', d: 'Uses another port. A bare colon means the remote home directory.' },
      { run: 'scp -p file deploy@192.0.2.10:/tmp/', d: 'Preserves the file’s modification time and mode.' },
      { run: 'scp host1:/tmp/a.txt host2:/tmp/', d: 'Copies from one remote machine to another.' },
      { run: 'rsync -avhP site/ deploy@192.0.2.10:/var/www/site/', d: 'Better for large or repeated copies: resumes, and sends only changes.' },
    ],
    security: {
      lede: ['scp is ', { b: 'the encrypted replacement for FTP and rcp' }, '.'],
      points: [
        { t: 'Never FTP a secret', d: 'FTP sends the password and the file in clear text. scp, sftp and rsync over SSH protect both.' },
        { t: 'Mind where files land', d: 'A file uploaded to /tmp is readable by other users on the server unless its mode says otherwise. Copy secrets straight to a private directory.' },
        { t: 'It overwrites without asking', d: 'scp replaces an existing file of the same name silently. Check the destination path, especially with -r.' },
      ],
    },
    protocols: ['ssh', 'sftp', 'tcp'],
    related: ['ssh', 'rsync'],
    footnote: 'Current OpenSSH versions run scp over the SFTP protocol internally; the command is used the same way.',
  },
  {
    slug: 'nc',
    cmd: 'nc',
    group: 'sockets',
    pkg: 'netcat-openbsd',
    fn: 'Opens raw TCP or UDP connections: tests whether a port is open, and sends or listens for data.',
    kicker: 'Linux · sockets & transfer',
    sub: 'a raw network connection',
    lede: [
      { m: 'nc' },
      ' — netcat — connects to a port and joins it to your keyboard and screen. With nothing else in the way, it shows ',
      { a: 'whether a port is reachable and what the service says first' },
      '. It can also ',
      { b: 'listen on a port and accept a connection' },
      '.',
    ],
    takeaway: [{ a: 'nc -zv host port' }, ' answers the most common network question: is that port open from here?'],
    points: [
      { k: 'Test a port', v: 'nc -zv HOST PORT', note: 'connect, report, close' },
      { k: 'Talk to a service', v: 'nc HOST PORT', note: 'type the protocol by hand' },
      { k: 'Listen', v: 'nc -l PORT', note: 'wait for a connection' },
      { k: 'UDP', v: '-u', note: 'TCP is the default' },
    ],
    session: {
      run: 'nc -zv 192.0.2.10 22',
      prompt: '$',
      lines: [
        { text: 'Connection to 192.0.2.10 22 port [tcp/ssh] succeeded!', n: 1 },
        { text: 'nc -zv 192.0.2.10 3306', run: true, n: 2 },
        { text: 'nc: connect to 192.0.2.10 port 3306 (tcp) failed: Connection refused' },
        { text: 'nc 192.0.2.10 22', run: true, n: 3 },
        { text: 'SSH-2.0-OpenSSH_9.6p1 Ubuntu-3ubuntu13.5' },
        { text: 'nc -l 9000', run: true, n: 4 },
      ],
      notes: [
        { t: 'The port is open', d: 'A TCP connection was made and closed. -z sends no data; -v reports the result.' },
        { t: 'Refused', d: 'The host answered, but nothing is listening on that port. A firewall silently dropping the packets would instead hang until it timed out.' },
        { t: 'The service’s banner', d: 'Connecting without -z shows what the server sends first — here the SSH version string.' },
        { t: 'Listening', d: 'nc waits on port 9000. Whatever another machine sends to that port appears here; it is a quick way to test that a firewall rule lets traffic through.' },
      ],
    },
    recipes: [
      { run: 'nc -zv 192.0.2.10 20-25', d: 'Tests a range of ports.' },
      { run: 'nc -zvw 3 192.0.2.10 443', d: 'Gives up after three seconds instead of waiting.' },
      { run: 'printf "GET / HTTP/1.0\\r\\n\\r\\n" | nc example.com 80', d: 'Sends an HTTP request by hand and prints the raw response.' },
      { run: 'nc -zvu 192.0.2.53 53', d: 'Tests a UDP port.' },
    ],
    security: {
      lede: ['netcat is ', { b: 'equally a diagnostic tool and an attacker’s tool' }, '.'],
      points: [
        { t: 'Banners disclose versions', d: 'Many services announce their software and version on connect. That is what an attacker matches against lists of known vulnerabilities.' },
        { t: 'Reverse shells', d: 'netcat can attach a shell to a network connection. An nc process on a server that nobody started, especially with -e or connected to an outside address, is an incident.' },
        { t: 'Only test what you may', d: 'Probing ports on systems you do not own or have permission to test is unauthorised access in many jurisdictions.' },
      ],
    },
    protocols: ['tcp', 'udp'],
    related: ['ss', 'nmap'],
    footnote: 'Several versions of netcat exist with slightly different switches; this describes the OpenBSD one that Debian and Ubuntu ship.',
  },
  {
    slug: 'netstat',
    cmd: 'netstat',
    group: 'sockets',
    pkg: 'net-tools',
    fn: 'The older command for listing open ports, connections and the routing table — replaced by ss and ip.',
    kicker: 'Linux · sockets & transfer',
    sub: 'the classic socket listing',
    lede: [
      { m: 'netstat' },
      ' lists network connections and listening ports. Like ifconfig it belongs to net-tools and ',
      { a: 'has been replaced — by ss' },
      ' — but ',
      { b: '"netstat -tulpn" is in so many guides that it is worth knowing' },
      ', and it exists on Windows and macOS as well.',
    ],
    takeaway: [{ b: 'netstat -tulpn' }, ' and ', { a: 'ss -tulpn' }, ' answer the same question: what is listening?'],
    points: [
      { k: 'Listening ports', v: 'netstat -tulpn', note: 'TCP and UDP, with process' },
      { k: 'Replaced by', v: 'ss', note: 'same switches, faster' },
      { k: 'Routing table', v: 'netstat -rn', note: 'now "ip route"' },
      { k: 'Package', v: 'net-tools', note: 'not installed by default' },
    ],
    session: {
      run: 'netstat -tulpn',
      prompt: '#',
      lines: [
        { text: 'Proto Recv-Q Send-Q Local Address      Foreign Address    State    PID/Program name', n: 1 },
        { text: 'tcp        0      0 0.0.0.0:22         0.0.0.0:*          LISTEN   812/sshd', n: 2 },
        { text: 'tcp        0      0 127.0.0.1:3306     0.0.0.0:*          LISTEN   1004/mysqld', n: 3 },
        { text: 'tcp6       0      0 :::80              :::*               LISTEN   2231/nginx' },
        { text: 'udp        0      0 127.0.0.53:53      0.0.0.0:*                   640/systemd-resolve', n: 4 },
      ],
      notes: [
        { t: 'The switches spell the question', d: 't TCP, u UDP, l listening, p the owning process, n numbers instead of names.' },
        { t: 'Listening on every address', d: '0.0.0.0:22 means SSH accepts connections on all interfaces — reachable from the network.' },
        { t: 'Listening on localhost only', d: '127.0.0.1:3306 means MySQL accepts connections only from this machine. Nothing outside can reach it.' },
        { t: 'UDP has no state', d: 'UDP is connectionless, so the State column is empty. This is the local DNS stub.' },
      ],
    },
    recipes: [
      { run: 'ss -tulpn', d: 'The modern equivalent, with the same switches.' },
      { run: 'netstat -rn', d: 'Shows the routing table numerically.' },
      { run: 'netstat -i', d: 'Shows per-interface packet and error counters.' },
      { run: 'netstat -an | grep ESTABLISHED', d: 'Lists the connections currently open.' },
    ],
    security: {
      lede: ['Every listening port is ', { b: 'a service an attacker can try' }, '.'],
      points: [
        { t: 'Know your listeners', d: 'Each line should be something you can name and justify. An unknown process listening on a high port is a classic sign of a backdoor.' },
        { t: '0.0.0.0 versus 127.0.0.1', d: 'A database or admin panel bound to 0.0.0.0 is exposed to the network. Bind it to localhost unless other machines truly need it.' },
        { t: 'Run it as root', d: 'Without root the process column is blank for other users’ sockets, and the most interesting information is missing.' },
      ],
    },
    protocols: ['tcp', 'udp', 'ip4', 'ip6'],
    related: ['ss', 'ip-route'],
    footnote: 'netstat reads /proc and is slow on busy machines; ss asks the kernel directly.',
  },
  {
    slug: 'ssh-keygen',
    cmd: 'ssh-keygen',
    group: 'sockets',
    pkg: 'openssh-client',
    fn: 'Creates an SSH key pair: a private key that stays with you, and a public key that servers use to recognise you.',
    kicker: 'Linux · sockets & transfer',
    sub: 'make an SSH key',
    lede: [
      { m: 'ssh-keygen' },
      ' generates a pair of keys. ',
      { a: 'The public key is copied to servers; the private key never leaves your machine' },
      '. A server that holds your public key can check that you hold the private one — ',
      { b: 'a login with no password sent at all' },
      '.',
    ],
    takeaway: ['The ', { a: '.pub' }, ' file can go anywhere. The other one ', { b: 'is the secret' }, '.'],
    points: [
      { k: 'Recommended type', v: 'ed25519', note: 'short, fast, strong' },
      { k: 'Creates', v: 'Two files', note: 'id_ed25519 and id_ed25519.pub' },
      { k: 'Passphrase', v: 'Set one', note: 'encrypts the private key on disk' },
      { k: 'Install with', v: 'ssh-copy-id', note: 'puts the public key on a server' },
    ],
    session: {
      run: 'ssh-keygen -t ed25519 -C "user@netflow"',
      prompt: '$',
      lines: [
        { text: 'Generating public/private ed25519 key pair.' },
        { text: 'Enter file in which to save the key (/home/user/.ssh/id_ed25519): ', n: 1 },
        { text: 'Enter passphrase (empty for no passphrase): ', n: 2 },
        { text: 'Your identification has been saved in /home/user/.ssh/id_ed25519', n: 3 },
        { text: 'Your public key has been saved in /home/user/.ssh/id_ed25519.pub' },
        { text: 'The key fingerprint is:' },
        { text: 'SHA256:Zp4x0aB7mQe2Lk9sVh1TtR8cNw3yUo6dJfGiE5rXbHc user@netflow' },
        { text: 'ssh-copy-id deploy@192.0.2.10', run: true, n: 4 },
        { text: 'Number of key(s) added: 1' },
      ],
      notes: [
        { t: 'Where to save it', d: 'Pressing Enter accepts the default location, which is where ssh looks for keys.' },
        { t: 'The passphrase', d: 'It encrypts the private key file. Someone who copies the file still cannot use it without the passphrase.' },
        { t: 'Two files', d: 'The first is the private key — guard it. The .pub file is the public half, safe to share.' },
        { t: 'Installing the public key', d: 'ssh-copy-id appends it to ~/.ssh/authorized_keys on the server. From now on ssh logs in with the key.' },
      ],
    },
    recipes: [
      { run: 'cat ~/.ssh/id_ed25519.pub', d: 'Prints your public key, to paste into GitHub or a server.' },
      { run: 'ssh-keygen -lf ~/.ssh/id_ed25519.pub', d: 'Shows a key’s fingerprint.' },
      { run: 'ssh-keygen -p -f ~/.ssh/id_ed25519', d: 'Changes or adds the passphrase on an existing key.' },
      { run: 'ssh-keygen -R 192.0.2.10', d: 'Removes a host from known_hosts, after a server has been rebuilt.' },
    ],
    security: {
      lede: ['A private key is ', { b: 'a password that is never typed and never expires' }, ' — so look after it accordingly.'],
      points: [
        { t: 'Always set a passphrase', d: 'An unprotected private key works for whoever copies the file. With a passphrase, a stolen laptop or backup does not hand over every server.' },
        { t: 'One key per device', d: 'Do not copy a private key between machines. Give each device its own key, so one can be revoked without affecting the rest.' },
        { t: 'Review authorized_keys', d: 'Each line in ~/.ssh/authorized_keys is someone who can log in as that user. An unrecognised key is a backdoor.' },
      ],
    },
    protocols: ['ssh'],
    related: ['ssh', 'scp'],
    footnote: 'RSA keys are still widely accepted; if one is needed, use at least 3072 bits: ssh-keygen -t rsa -b 4096.',
  },

  // ── reachability ──────────────────────────────────────────────────────
  {
    slug: 'mtr',
    cmd: 'mtr',
    group: 'reach',
    pkg: 'mtr-tiny',
    fn: 'Combines ping and traceroute: shows every hop on the path, with live loss and latency for each.',
    kicker: 'Linux · reachability',
    sub: 'traceroute, continuously',
    lede: [
      { m: 'mtr' },
      ' traces the route like traceroute, then ',
      { a: 'keeps probing every hop and updates the figures as it goes' },
      '. One screen shows ',
      { b: 'where on the path packets are being lost or delayed' },
      ', which a single traceroute cannot.',
    ],
    takeaway: ['Loss that ', { a: 'continues to the final hop' }, ' is real. Loss at one middle hop only usually is not.'],
    points: [
      { k: 'Shows', v: 'Each hop, live', note: 'loss and latency' },
      { k: 'For a report', v: 'mtr -rw HOST', note: 'runs, then prints a table' },
      { k: 'Fewer lookups', v: '-n', note: 'addresses only' },
      { k: 'Quit', v: 'q', note: 'in the live view' },
    ],
    session: {
      run: 'mtr -rwn -c 10 198.51.100.20',
      prompt: '$',
      lines: [
        { text: 'HOST: netflow          Loss%   Snt   Last   Avg  Best  Wrst StDev', n: 1 },
        { text: '  1.|-- 192.168.1.1     0.0%    10    0.6   0.7   0.5   1.1   0.2', n: 2 },
        { text: '  2.|-- 192.0.2.1       0.0%    10    4.8   5.1   4.6   6.3   0.5' },
        { text: '  3.|-- 203.0.113.9    40.0%    10   12.4  12.9  12.1  14.0   0.6', n: 3 },
        { text: '  4.|-- 198.51.100.20   0.0%    10   13.0  13.2  12.8  14.1   0.4', n: 4 },
      ],
      notes: [
        { t: 'The columns', d: 'Percentage lost, probes sent, then the last, average, best and worst round-trip time in milliseconds, and how much it varies.' },
        { t: 'The first hop is your router', d: 'Under a millisecond and no loss: the local network is fine.' },
        { t: 'Loss at one hop only', d: 'Hop 3 dropped 40% of the probes sent to it, but the hop after it shows none. The router is simply limiting how often it replies; traffic through it is unaffected.' },
        { t: 'The destination', d: 'No loss and a steady 13 ms. The path is healthy end to end, whatever hop 3 looked like.' },
      ],
    },
    recipes: [
      { run: 'mtr 198.51.100.20', d: 'The live view, updating until you press q.' },
      { run: 'mtr -T -P 443 example.com', d: 'Probes with TCP to port 443, as real web traffic would travel.' },
      { run: 'mtr -u example.com', d: 'Probes with UDP instead of ICMP.' },
      { run: 'mtr -rw -c 100 example.com > path.txt', d: 'Saves a 100-probe report to send to a network provider.' },
    ],
    security: {
      lede: ['A path trace shows ', { b: 'whose networks your traffic crosses' }, '.'],
      points: [
        { t: 'Read loss correctly', d: 'Routers deliberately limit replies to probes. Misreading that as a fault leads to blaming the wrong network. Trust the last hop.' },
        { t: 'Unexpected paths', d: 'Traffic to a nearby service that suddenly crosses another country may be a routing change — or a route hijack. A saved baseline makes the difference visible.' },
        { t: 'Firewalls change the picture', d: 'Many networks drop ICMP. Probing with TCP to the service’s real port shows the path that the actual traffic takes.' },
      ],
    },
    protocols: ['icmp', 'ip4', 'udp', 'tcp'],
    related: ['traceroute', 'ping'],
    footnote: 'The package is mtr-tiny on Debian and Ubuntu for the terminal version, and mtr on Fedora.',
  },
  {
    slug: 'nmap',
    cmd: 'nmap',
    group: 'reach',
    pkg: 'nmap',
    fn: 'Scans hosts to find which ports are open and what services and versions are running on them.',
    kicker: 'Linux · reachability',
    sub: 'what is open on that host',
    lede: [
      { m: 'nmap' },
      ' — network mapper — probes a host’s ports and reports ',
      { a: 'which are open, closed or filtered' },
      '. Asked to, it also ',
      { b: 'identifies the service and version behind each open port' },
      '. It is how administrators check what their own machines expose.',
    ],
    takeaway: ['Scan your own server from outside: ', { a: 'what nmap sees is what an attacker sees' }, '.'],
    points: [
      { k: 'Default scan', v: 'Top 1000 TCP ports', note: 'of 65535' },
      { k: 'States', v: 'open, closed, filtered', note: 'filtered means no reply' },
      { k: 'Versions', v: '-sV', note: 'asks each service what it is' },
      { k: 'Permission', v: 'Required', note: 'scan only what you may' },
    ],
    session: {
      run: 'nmap -sV 192.168.1.20',
      prompt: '$',
      lines: [
        { text: 'Nmap scan report for fileserver (192.168.1.20)', n: 1 },
        { text: 'Host is up (0.00041s latency).' },
        { text: 'Not shown: 997 closed tcp ports (conn-refused)', n: 2 },
        { text: 'PORT    STATE SERVICE     VERSION', n: 3 },
        { text: '22/tcp  open  ssh         OpenSSH 9.6p1 Ubuntu 3ubuntu13.5' },
        { text: '80/tcp  open  http        nginx 1.24.0' },
        { text: '445/tcp open  netbios-ssn Samba smbd 4.6.2', n: 4 },
        { text: 'Nmap done: 1 IP address (1 host up) scanned in 11.42 seconds' },
      ],
      notes: [
        { t: 'The target, and that it answered', d: 'The host is up and replied in under a millisecond, so it is on the local network.' },
        { t: 'What is not listed', d: '997 of the 1000 ports tried were closed: the host replied, but nothing was listening.' },
        { t: 'The table of open ports', d: 'Port and protocol, state, the service usually found there, and — because of -sV — the software and version actually answering.' },
        { t: 'A file-sharing service', d: 'Port 445 is SMB. Fine on a file server inside a network; it should never be reachable from the internet.' },
      ],
    },
    recipes: [
      { run: 'nmap -sn 192.168.1.0/24', d: 'Finds which hosts on a network are up, without scanning ports.' },
      { run: 'nmap -p 22,80,443 192.168.1.20', d: 'Scans only the ports named.' },
      { run: 'nmap -p- 192.168.1.20', d: 'Scans all 65535 TCP ports.' },
      { run: 'sudo nmap -sU --top-ports 20 192.168.1.20', d: 'Scans the twenty most common UDP ports.' },
    ],
    security: {
      lede: ['Scanning is ', { b: 'the first step of an attack and the first step of a defence' }, ' — what differs is permission.'],
      points: [
        { t: 'Only scan what you are authorised to', d: 'Scanning networks you do not own or have written permission to test can break the law and will trip intrusion detection. Practise on your own machines or a lab.' },
        { t: 'Audit yourself regularly', d: 'Scan your servers from outside the firewall and compare with the previous result. A newly open port is either a mistake or an intrusion.' },
        { t: 'Version strings invite attack', d: 'What -sV reads is what an attacker matches against known vulnerabilities. Keep services patched, and close what is not needed.' },
      ],
    },
    protocols: ['tcp', 'udp', 'icmp', 'ip4'],
    related: ['nc', 'ss'],
    footnote: 'scanme.nmap.org is a host the nmap project provides for testing scans against, within its stated limits.',
  },

  // ── capture & filtering ───────────────────────────────────────────────
  {
    slug: 'iptables',
    cmd: 'iptables',
    group: 'capture',
    pkg: 'iptables',
    fn: 'The long-standing Linux firewall command: lists and edits the rules that accept or drop packets.',
    kicker: 'Linux · capture & filtering',
    sub: 'the classic firewall',
    lede: [
      { m: 'iptables' },
      ' manages packet-filtering rules in the kernel. Rules live in ',
      { a: 'chains — INPUT, OUTPUT, FORWARD — and are checked in order until one matches' },
      '. nftables has replaced it underneath, but ',
      { b: 'iptables syntax is still what most guides, Docker and many servers use' },
      '.',
    ],
    takeaway: ['Rules are read ', { a: 'top to bottom, first match wins' }, ' — so order is everything.'],
    points: [
      { k: 'List', v: 'iptables -L -n -v', note: 'with packet counters' },
      { k: 'Chains', v: 'INPUT, OUTPUT, FORWARD', note: 'to, from, through the host' },
      { k: 'Targets', v: 'ACCEPT, DROP, REJECT', note: 'what happens on a match' },
      { k: 'Not saved', v: 'By default', note: 'lost at reboot' },
    ],
    session: {
      run: 'iptables -L INPUT -n -v --line-numbers',
      prompt: '#',
      lines: [
        { text: 'Chain INPUT (policy DROP 214 packets, 12840 bytes)', n: 1 },
        { text: 'num   pkts bytes target  prot opt in  out  source      destination' },
        { text: '1     8412  701K ACCEPT  all  --  lo  *    0.0.0.0/0   0.0.0.0/0', n: 2 },
        { text: '2      94K   88M ACCEPT  all  --  *   *    0.0.0.0/0   0.0.0.0/0   ctstate RELATED,ESTABLISHED', n: 3 },
        { text: '3      312 18720 ACCEPT  tcp  --  *   *    0.0.0.0/0   0.0.0.0/0   tcp dpt:22', n: 4 },
        { text: 'iptables -A INPUT -p tcp --dport 443 -j ACCEPT', run: true },
      ],
      notes: [
        { t: 'The chain and its policy', d: 'The policy is what happens to a packet no rule matches. DROP means everything not explicitly allowed is discarded: 214 packets so far.' },
        { t: 'Allow loopback', d: 'Traffic on the lo interface is the machine talking to itself. Blocking it breaks many programs.' },
        { t: 'Allow replies', d: 'Packets belonging to connections already established are accepted. This one rule lets answers to your own outgoing requests back in.' },
        { t: 'Allow SSH', d: 'New TCP connections to port 22 are accepted. The counters show the rule has matched 312 packets.' },
      ],
    },
    recipes: [
      { run: 'sudo iptables -S', d: 'Prints the rules as the commands that would recreate them.' },
      { run: 'sudo iptables -I INPUT 1 -s 203.0.113.50 -j DROP', d: 'Inserts a rule at the top to block one address.' },
      { run: 'sudo iptables -D INPUT 3', d: 'Deletes rule number 3 from the chain.' },
      { run: 'sudo iptables-save > rules.v4', d: 'Saves the current ruleset to a file.' },
    ],
    security: {
      lede: ['A firewall should ', { b: 'drop by default and allow by exception' }, '.'],
      points: [
        { t: 'Do not lock yourself out', d: 'Setting the policy to DROP before allowing SSH cuts your own connection. Add the allow rules first, and keep console access for a remote server.' },
        { t: 'Rules vanish at reboot', d: 'iptables changes are in memory only. Without iptables-persistent or an equivalent, a restart leaves the machine with no firewall.' },
        { t: 'IPv6 is separate', d: 'iptables covers IPv4 only. Unless ip6tables has matching rules, every service is still reachable over IPv6.' },
      ],
    },
    protocols: ['tcp', 'udp', 'icmp', 'ip4', 'nat'],
    related: ['nft', 'ufw'],
    footnote: 'On current distributions the iptables command is usually iptables-nft, translating its rules into nftables.',
  },
  {
    slug: 'ufw',
    cmd: 'ufw',
    group: 'capture',
    pkg: 'ufw',
    fn: 'A simple front end to the firewall: allow or deny a port in one short command, with safe defaults.',
    kicker: 'Linux · capture & filtering',
    sub: 'the firewall, made simple',
    lede: [
      { m: 'ufw' },
      ' — uncomplicated firewall — writes the iptables or nftables rules for you. ',
      { a: 'It blocks incoming connections by default and lets you open ports by name or number' },
      ', and ',
      { b: 'its rules are saved and applied again at boot' },
      '.',
    ],
    takeaway: ['Allow SSH ', { b: 'before' }, ' you enable it: ', { a: 'ufw allow ssh, then ufw enable' }, '.'],
    points: [
      { k: 'Default', v: 'Deny incoming', note: 'allow outgoing' },
      { k: 'Open a port', v: 'ufw allow 443/tcp', note: 'or by name: ufw allow ssh' },
      { k: 'Switch on', v: 'ufw enable', note: 'and at every boot' },
      { k: 'Found on', v: 'Ubuntu, Debian', note: 'Fedora uses firewalld' },
    ],
    session: {
      run: 'ufw allow ssh',
      prompt: '#',
      lines: [
        { text: 'Rules updated', n: 1 },
        { text: 'Rules updated (v6)' },
        { text: 'ufw enable', run: true, n: 2 },
        { text: 'Command may disrupt existing ssh connections. Proceed with operation (y|n)? y' },
        { text: 'Firewall is active and enabled on system startup' },
        { text: 'ufw status verbose', run: true, n: 3 },
        { text: 'Status: active' },
        { text: 'Default: deny (incoming), allow (outgoing), disabled (routed)' },
        { text: 'To                         Action      From' },
        { text: '22/tcp                     ALLOW IN    Anywhere', n: 4 },
        { text: '22/tcp (v6)                ALLOW IN    Anywhere (v6)' },
      ],
      notes: [
        { t: 'A rule for IPv4 and IPv6', d: 'ufw looked "ssh" up as port 22 and added it for both protocols at once — something iptables needs two commands for.' },
        { t: 'Turning it on', d: 'The warning is real: enabling the firewall without the SSH rule would cut you off. It is safe here because the rule was added first.' },
        { t: 'The defaults', d: 'Incoming connections are denied unless a rule allows them; outgoing ones are allowed.' },
        { t: 'The rules in force', d: 'Port 22 is open to anyone, over both IPv4 and IPv6. Nothing else is.' },
      ],
    },
    recipes: [
      { run: 'sudo ufw allow from 192.168.1.0/24 to any port 22', d: 'Allows SSH only from the local network.' },
      { run: 'sudo ufw status numbered', d: 'Lists rules with numbers, for deleting.' },
      { run: 'sudo ufw delete 2', d: 'Deletes rule number 2.' },
      { run: 'sudo ufw limit ssh', d: 'Allows SSH but blocks an address that connects too often — a simple brake on password guessing.' },
    ],
    security: {
      lede: ['The value of ufw is ', { b: 'that a correct default-deny firewall takes three commands' }, '.'],
      points: [
        { t: 'Open as little as possible', d: 'Each allowed port is a service exposed. Restrict administrative ports to the addresses that need them rather than to Anywhere.' },
        { t: 'Docker bypasses it', d: 'Ports published by Docker containers are opened by Docker’s own rules and are reachable even when ufw says otherwise. Bind them to 127.0.0.1 or filter in the DOCKER-USER chain.' },
        { t: 'Check from outside', d: 'A firewall rule is a claim. Scanning the machine from another host with nmap is the proof.' },
      ],
    },
    protocols: ['tcp', 'udp', 'ip4', 'ip6'],
    related: ['iptables', 'nft'],
    footnote: 'On Fedora, RHEL and their relatives the equivalent tool is firewall-cmd, the front end to firewalld.',
  },
];

export const switches: Record<string, LinuxSwitch[]> = {
  ifconfig: [
    { flag: '-a', d: 'Show all interfaces, including those that are down.' },
    { flag: '-s', d: 'Short: a one-line summary per interface.' },
    { flag: 'IFACE up', d: 'Enable an interface. "down" disables it.' },
  ],
  nmcli: [
    { flag: '-t', d: 'Terse: colon-separated output for scripts.' },
    { flag: '-f FIELDS', d: 'Show only these fields.' },
    { flag: '-p', d: 'Pretty: add headers and alignment.' },
    { flag: '--ask', d: 'Prompt for missing values such as a password.' },
    { flag: '-s', d: 'Show secrets, such as saved Wi-Fi passwords. Needs root.' },
  ],
  nslookup: [
    { flag: '-type=TYPE', d: 'Ask for a record type: A, AAAA, MX, NS, TXT.' },
    { flag: 'SERVER', d: 'A DNS server given after the name is asked instead of the default.' },
    { flag: '-port=NUM', d: 'Query a DNS server on another port.' },
    { flag: '-debug', d: 'Print the full response.' },
    { flag: '-timeout=SECS', d: 'How long to wait for a reply.' },
  ],
  host: [
    { flag: '-t TYPE', d: 'Ask for a record type.' },
    { flag: '-a', d: 'Ask for all records and print the full response.' },
    { flag: '-4', d: 'Use IPv4 for the query. -6 uses IPv6.' },
    { flag: '-W SECS', d: 'Wait this long for a reply.' },
    { flag: '-v', d: 'Verbose output.' },
  ],
  wget: [
    { flag: '-O FILE', d: 'Save under this name. "-O -" writes to standard output.' },
    { flag: '-c', d: 'Continue a partially downloaded file.' },
    { flag: '-q', d: 'Quiet: no progress output.' },
    { flag: '-P DIR', d: 'Save into this directory.' },
    { flag: '-i FILE', d: 'Read URLs from a file.' },
    { flag: '-r', d: 'Recursive: follow links and download what they point to.' },
    { flag: '--limit-rate=RATE', d: 'Limit the download speed, such as 500k.' },
    { flag: '-b', d: 'Go to the background straight after starting.' },
  ],
  ssh: [
    { flag: '-p PORT', d: 'Connect to this port instead of 22.' },
    { flag: '-i FILE', d: 'Use this private key.' },
    { flag: '-v', d: 'Verbose: show each step of the connection. Essential for debugging.' },
    { flag: '-L L:HOST:R', d: 'Forward local port L to HOST port R through the server.' },
    { flag: '-D PORT', d: 'Open a SOCKS proxy on a local port.' },
    { flag: '-J HOST', d: 'Jump through an intermediate host.' },
    { flag: '-N', d: 'Do not run a remote command — for forwarding only.' },
    { flag: '-X', d: 'Forward graphical (X11) programs.' },
  ],
  scp: [
    { flag: '-r', d: 'Recursive: copy directories.' },
    { flag: '-P PORT', d: 'Connect to this port. Capital P.' },
    { flag: '-p', d: 'Preserve modification times and modes.' },
    { flag: '-i FILE', d: 'Use this private key.' },
    { flag: '-C', d: 'Compress data in transit.' },
    { flag: '-q', d: 'Quiet: no progress meter.' },
  ],
  nc: [
    { flag: '-z', d: 'Zero I/O: just test whether the port is open.' },
    { flag: '-v', d: 'Verbose: report the result.' },
    { flag: '-l', d: 'Listen for an incoming connection.' },
    { flag: '-u', d: 'Use UDP instead of TCP.' },
    { flag: '-w SECS', d: 'Time out after this many seconds.' },
    { flag: '-n', d: 'Numeric only: do not look up names.' },
    { flag: '-k', d: 'Keep listening after a client disconnects.' },
  ],
  netstat: [
    { flag: '-t', d: 'TCP sockets.' },
    { flag: '-u', d: 'UDP sockets.' },
    { flag: '-l', d: 'Listening sockets only.' },
    { flag: '-p', d: 'Show the owning process.' },
    { flag: '-n', d: 'Numeric: no name lookups.' },
    { flag: '-r', d: 'Show the routing table.' },
    { flag: '-i', d: 'Show interface statistics.' },
    { flag: '-a', d: 'All sockets, listening and connected.' },
  ],
  'ssh-keygen': [
    { flag: '-t TYPE', d: 'The key type: ed25519 or rsa.' },
    { flag: '-b BITS', d: 'Key size, for RSA.' },
    { flag: '-C COMMENT', d: 'A label stored with the key.' },
    { flag: '-f FILE', d: 'The file to write or read.' },
    { flag: '-p', d: 'Change the passphrase of an existing key.' },
    { flag: '-l', d: 'Show a key’s fingerprint.' },
    { flag: '-R HOST', d: 'Remove a host’s entries from known_hosts.' },
    { flag: '-y', d: 'Print the public key belonging to a private key.' },
  ],
  mtr: [
    { flag: '-r', d: 'Report mode: run, then print a table and exit.' },
    { flag: '-w', d: 'Wide report: do not cut host names short.' },
    { flag: '-n', d: 'Numeric: no name lookups.' },
    { flag: '-c NUM', d: 'Send NUM probes to each hop.' },
    { flag: '-T', d: 'Use TCP probes. -u uses UDP.' },
    { flag: '-P PORT', d: 'The destination port for TCP or UDP probes.' },
    { flag: '-b', d: 'Show both names and addresses.' },
  ],
  nmap: [
    { flag: '-sV', d: 'Detect the service and version on each open port.' },
    { flag: '-sn', d: 'Host discovery only: no port scan.' },
    { flag: '-p PORTS', d: 'Ports to scan: 22,80 or 1-1000. -p- means all.' },
    { flag: '-sS', d: 'TCP SYN scan, the default as root.' },
    { flag: '-sU', d: 'Scan UDP ports.' },
    { flag: '-O', d: 'Guess the operating system. Needs root.' },
    { flag: '-A', d: 'Aggressive: versions, OS, scripts and traceroute together.' },
    { flag: '-Pn', d: 'Skip the ping and treat the host as up.' },
    { flag: '-oN FILE', d: 'Save the output to a file.' },
  ],
  iptables: [
    { flag: '-L', d: 'List the rules in a chain.' },
    { flag: '-n', d: 'Numeric: no name lookups.' },
    { flag: '-v', d: 'Verbose: show counters and interfaces.' },
    { flag: '-A CHAIN', d: 'Append a rule to the end of a chain.' },
    { flag: '-I CHAIN NUM', d: 'Insert a rule at position NUM.' },
    { flag: '-D CHAIN NUM', d: 'Delete rule number NUM.' },
    { flag: '-p PROTO', d: 'Match a protocol: tcp, udp, icmp.' },
    { flag: '--dport PORT', d: 'Match the destination port.' },
    { flag: '-s ADDR', d: 'Match the source address.' },
    { flag: '-j TARGET', d: 'What to do on a match: ACCEPT, DROP, REJECT.' },
    { flag: '-t TABLE', d: 'Work on another table, such as nat.' },
  ],
  ufw: [
    { flag: 'enable', d: 'Turn the firewall on, now and at boot. "disable" turns it off.' },
    { flag: 'status verbose', d: 'Show the state, the defaults and every rule.' },
    { flag: 'allow PORT', d: 'Allow incoming connections to a port or named service.' },
    { flag: 'deny PORT', d: 'Block incoming connections to a port.' },
    { flag: 'limit PORT', d: 'Allow, but rate-limit repeated connections.' },
    { flag: 'delete NUM', d: 'Delete a rule by its number.' },
    { flag: '--dry-run', d: 'Show the rules that would be written without applying them.' },
  ],
};
