import type { LinuxCommand } from '../linux-data';
import type { LinuxSwitch } from '../linux-switches';

/* More on processes — stopping them by name, running them in the background,
   scheduling them, reading what they logged — and the package managers that
   put the programs there in the first place. */

export const commands: LinuxCommand[] = [
  // ── process & service management ──────────────────────────────────────
  {
    slug: 'pkill',
    cmd: 'pkill',
    group: 'proc',
    pkg: 'procps',
    fn: 'Sends a signal to every process whose name matches a pattern — kill, without looking up the id first.',
    kicker: 'Linux · process & service management',
    sub: 'stop a process by name',
    lede: [
      { m: 'pkill' },
      ' finds processes by name and signals them in one step. Its partner ',
      { a: 'pgrep does the finding without the killing' },
      ', and is ',
      { b: 'the way to check what a pattern will match before you use it' },
      '.',
    ],
    takeaway: ['Run ', { a: 'pgrep -a pattern' }, ' first. Whatever it lists is what pkill will signal.'],
    points: [
      { k: 'Matches', v: 'Process names', note: 'as a pattern, not exactly' },
      { k: 'Default signal', v: 'TERM', note: 'a polite request to stop' },
      { k: 'Preview', v: 'pgrep -a', note: 'same matching, no signal' },
      { k: 'Whole command line', v: '-f', note: 'not just the name' },
    ],
    session: {
      run: 'pgrep -a python',
      prompt: '$',
      lines: [
        { text: '4127 python3 worker.py', n: 1 },
        { text: '4188 python3 -m http.server 8000' },
        { text: 'pkill -f "http.server"', run: true, n: 2 },
        { text: 'pgrep -a python', run: true, n: 3 },
        { text: '4127 python3 worker.py' },
        { text: 'pkill -u deploy', run: true, n: 4 },
      ],
      notes: [
        { t: 'What the pattern matches', d: 'Two processes have "python" in their name. -a shows the full command line, so they can be told apart.' },
        { t: '-f matches the whole command line', d: 'Both processes are named python3, so the name alone cannot separate them. -f matches against the arguments too.' },
        { t: 'One left', d: 'The web server is gone; the worker is untouched. pkill printed nothing, which means it found and signalled a match.' },
        { t: 'Every process of one user', d: '-u matches by owner instead of name. This signals everything the deploy account is running.' },
      ],
    },
    recipes: [
      { run: 'pkill -9 firefox', d: 'Sends KILL, for a process that ignores the polite request.' },
      { run: 'pkill -HUP nginx', d: 'Sends HUP, which asks many services to re-read their configuration.' },
      { run: 'pgrep -c sshd', d: 'Counts the matching processes.' },
      { run: 'killall -v chrome', d: 'A similar tool that matches the exact name only.' },
    ],
    security: {
      lede: ['A pattern ', { b: 'matches more than you had in mind' }, ' more often than not.'],
      points: [
        { t: 'Loose patterns', d: '"pkill ssh" also matches sshd and ssh-agent, and can cut your own connection. Use -x for an exact name, and preview with pgrep.' },
        { t: 'As root there is no limit', d: 'An ordinary user can only signal their own processes. Root can signal anything, including the init process and the database.' },
        { t: 'Stopping security tools', d: 'Killing the logging or monitoring agent is an early step in many intrusions. An agent that stops unexpectedly deserves an alert of its own.' },
      ],
    },
    protocols: [],
    related: ['kill', 'ps'],
    footnote: 'pgrep and pkill match against the first 15 characters of the process name unless -f is given.',
  },
  {
    slug: 'jobs',
    cmd: 'jobs',
    group: 'proc',
    pkg: 'bash',
    fn: 'Lists the commands this shell has running in the background or stopped, so they can be resumed.',
    kicker: 'Linux · process & service management',
    sub: 'background and foreground',
    lede: [
      { m: 'jobs' },
      ' shows what the current shell is running besides the command in front of you. ',
      { a: 'Ctrl+Z pauses a running command; bg lets it continue in the background; fg brings it back' },
      ' — ',
      { b: 'a way to do two things in one terminal' },
      '.',
    ],
    takeaway: [{ a: 'Ctrl+Z, then bg' }, ' moves a command you forgot to start in the background out of the way.'],
    points: [
      { k: 'Start in background', v: 'command &', note: 'the prompt returns at once' },
      { k: 'Pause', v: 'Ctrl+Z', note: 'the job is stopped, not ended' },
      { k: 'Resume', v: 'bg or fg', note: 'background or foreground' },
      { k: 'Refer to one', v: '%1, %2', note: 'the job number' },
    ],
    session: {
      run: 'sleep 300 &',
      prompt: '$',
      lines: [
        { text: '[1] 4410', n: 1 },
        { text: 'ping 192.0.2.1 > ping.log', run: true },
        { text: '^Z', n: 2 },
        { text: '[2]+  Stopped                 ping 192.0.2.1 > ping.log' },
        { text: 'bg %2', run: true, n: 3 },
        { text: '[2]+ ping 192.0.2.1 > ping.log &' },
        { text: 'jobs', run: true, n: 4 },
        { text: '[1]-  Running                 sleep 300 &' },
        { text: '[2]+  Running                 ping 192.0.2.1 > ping.log &' },
      ],
      notes: [
        { t: '& starts a job in the background', d: '[1] is the job number in this shell and 4410 is the process id. The prompt comes straight back.' },
        { t: 'Ctrl+Z stops the foreground command', d: 'ping is paused, not ended. It is not running at all until it is resumed.' },
        { t: 'bg resumes it in the background', d: 'Job 2 continues, and the terminal is free for other commands.' },
        { t: 'Both running', d: 'The + marks the job that fg or bg acts on by default. "fg %1" would bring the sleep to the foreground.' },
      ],
    },
    recipes: [
      { run: 'fg', d: 'Brings the most recent job back to the foreground.' },
      { run: 'kill %1', d: 'Ends job number 1.' },
      { run: 'jobs -l', d: 'Lists jobs with their process ids.' },
      { run: 'disown %1', d: 'Detaches a job from the shell, so closing the terminal does not end it.' },
    ],
    security: {
      lede: ['A background job ', { b: 'belongs to the terminal that started it' }, '.'],
      points: [
        { t: 'Jobs die with the session', d: 'Closing the terminal or losing the SSH connection ends its jobs. For work that must survive, use nohup, tmux or a systemd service.' },
        { t: 'Forgotten background processes', d: 'A test server left running with & keeps listening after you have moved on. Check jobs and "ss -tlnp" before leaving a machine.' },
        { t: 'Stopped is not finished', d: 'A job paused with Ctrl+Z still holds its files and its port. The shell warns "There are stopped jobs" when you try to exit.' },
      ],
    },
    protocols: [],
    related: ['nohup', 'kill'],
    footnote: 'Job numbers belong to one shell; another terminal cannot see or control them.',
  },
  {
    slug: 'nohup',
    cmd: 'nohup',
    group: 'proc',
    pkg: 'coreutils',
    fn: 'Runs a command so that it keeps going after you log out or the terminal closes.',
    kicker: 'Linux · process & service management',
    sub: 'keep running after logout',
    lede: [
      { m: 'nohup' },
      ' — no hang-up — starts a command that ',
      { a: 'ignores the signal sent when a terminal closes' },
      '. Combined with &, it lets a long job ',
      { b: 'carry on after you disconnect from SSH' },
      '.',
    ],
    takeaway: [{ a: 'nohup command &' }, ' — start it, log out, and it is still running tomorrow.'],
    points: [
      { k: 'Survives', v: 'Logout', note: 'and a dropped SSH connection' },
      { k: 'Output goes to', v: 'nohup.out', note: 'unless redirected' },
      { k: 'Use with', v: '&', note: 'to get the prompt back' },
      { k: 'For services', v: 'systemd instead', note: 'restarts, logs, limits' },
    ],
    session: {
      run: 'nohup ./backup.sh &',
      prompt: '$',
      lines: [
        { text: '[1] 4502', n: 1 },
        { text: "nohup: ignoring input and appending output to 'nohup.out'", n: 2 },
        { text: 'exit', run: true, n: 3 },
        { text: 'pgrep -a backup', run: true, n: 4 },
        { text: '4502 /bin/bash ./backup.sh' },
        { text: 'tail -1 nohup.out', run: true },
        { text: 'copied 1240 of 5310 files' },
      ],
      notes: [
        { t: 'Started in the background', d: 'The job number and process id. Note the id: it is how you will find the process later.' },
        { t: 'Where the output is going', d: 'With no terminal to print to, output is appended to nohup.out in the current directory.' },
        { t: 'Logging out', d: 'Normally this would end the script. Because of nohup, it keeps running.' },
        { t: 'Still there in a new session', d: 'After logging back in, the process is running and its progress can be read from nohup.out.' },
      ],
    },
    recipes: [
      { run: 'nohup ./job.sh > job.log 2>&1 &', d: 'Sends both output and errors to a log file of your choosing.' },
      { run: 'tmux new -s work', d: 'A session you can detach from and return to — better for interactive work.' },
      { run: 'systemd-run --user ./job.sh', d: 'Runs the command as a temporary systemd unit, with logging.' },
      { run: 'disown -h %1', d: 'Protects a job that is already running from the hang-up signal.' },
    ],
    security: {
      lede: ['A process that outlives your login ', { b: 'is easy to forget and hard to notice' }, '.'],
      points: [
        { t: 'Persistence', d: 'nohup is the simplest way to leave something running on a machine. Processes whose parent is init and that belong to a user who is not logged in are worth a look.' },
        { t: 'nohup.out collects everything', d: 'The output file grows without limit and may contain credentials the command printed. Redirect it somewhere deliberate, with sensible permissions.' },
        { t: 'It is not a service manager', d: 'Nothing restarts the process if it crashes, and nothing stops it. For anything permanent, write a systemd unit.' },
      ],
    },
    protocols: [],
    related: ['jobs', 'systemctl'],
    footnote: 'screen and tmux solve the same problem and let you reattach to see the output live.',
  },
  {
    slug: 'journalctl',
    cmd: 'journalctl',
    group: 'proc',
    pkg: 'systemd',
    fn: 'Reads the systemd journal: the logs of the kernel and every service, filterable by unit, time and priority.',
    kicker: 'Linux · process & service management',
    sub: 'read the system logs',
    lede: [
      { m: 'journalctl' },
      ' queries the journal, where systemd collects ',
      { a: 'everything services print, along with kernel and boot messages' },
      '. Instead of opening files in /var/log you ',
      { b: 'ask for one unit, one time range, or errors only' },
      '.',
    ],
    takeaway: ['A service failed? ', { a: 'journalctl -u name -e' }, ' shows the end of its log, where the reason is.'],
    points: [
      { k: 'One service', v: '-u NAME', note: 'the unit’s log only' },
      { k: 'Follow', v: '-f', note: 'live, like tail -f' },
      { k: 'Time', v: '--since, --until', note: '"1 hour ago", "today"' },
      { k: 'Errors only', v: '-p err', note: 'by priority' },
    ],
    session: {
      run: 'journalctl -u nginx --since "10 min ago" --no-pager',
      prompt: '$',
      lines: [
        { text: 'Sep 30 10:38:11 netflow systemd[1]: Starting nginx.service - A high performance web server...', n: 1 },
        { text: 'Sep 30 10:38:11 netflow nginx[5120]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)', n: 2 },
        { text: 'Sep 30 10:38:11 netflow systemd[1]: nginx.service: Failed with result \'exit-code\'.', n: 3 },
        { text: 'journalctl -p err -b --no-pager | tail -1', run: true, n: 4 },
        { text: 'Sep 30 10:38:11 netflow systemd[1]: Failed to start nginx.service - A high performance web server.' },
      ],
      notes: [
        { t: 'One unit, the last ten minutes', d: 'Each line has the time, the host, the program and its process id, then the message.' },
        { t: 'The actual reason', d: 'nginx could not bind to port 80 because something else already has it. This line is what systemctl status hints at but cuts short.' },
        { t: 'systemd’s verdict', d: 'The service exited with an error, so the unit is marked failed.' },
        { t: 'Errors since boot', d: '-p err keeps messages of priority error and worse; -b limits them to the current boot.' },
      ],
    },
    recipes: [
      { run: 'journalctl -f', d: 'Follows every log on the system live.' },
      { run: 'journalctl -u ssh -e', d: 'Opens one service’s log at its end.' },
      { run: 'journalctl -k -b', d: 'Kernel messages from this boot, like dmesg.' },
      { run: 'journalctl --disk-usage', d: 'Shows how much space the journal is taking.' },
    ],
    security: {
      lede: ['The journal is ', { b: 'the first place to look after anything unexpected' }, '.'],
      points: [
        { t: 'Logins and sudo', d: '"journalctl -u ssh" shows every accepted and failed login; "journalctl _COMM=sudo" shows who ran what as root.' },
        { t: 'Who may read it', d: 'Full access needs root or membership of the adm or systemd-journal group, because the logs contain user names, addresses and commands.' },
        { t: 'Logs on the same machine can be erased', d: 'An intruder with root can clear the journal. Forwarding logs to another host is what makes them trustworthy evidence.' },
      ],
    },
    protocols: ['syslog'],
    related: ['systemctl', 'tail'],
    footnote: 'The journal is stored in a binary format under /var/log/journal; journalctl is the only way to read it.',
  },
  {
    slug: 'crontab',
    cmd: 'crontab',
    group: 'proc',
    pkg: 'cron',
    fn: 'Edits and lists your scheduled jobs: commands that run by themselves at set times.',
    kicker: 'Linux · process & service management',
    sub: 'run a command on a schedule',
    lede: [
      { m: 'crontab' },
      ' manages your table of scheduled jobs. Each line is ',
      { a: 'five time fields followed by a command' },
      ', and the cron service ',
      { b: 'runs the command whenever the clock matches' },
      ' — every night, every Monday, every five minutes.',
    ],
    takeaway: ['The five fields, in order: ', { a: 'minute, hour, day of month, month, day of week' }, '.'],
    points: [
      { k: 'Edit', v: 'crontab -e', note: 'opens your table in an editor' },
      { k: 'List', v: 'crontab -l', note: 'prints it' },
      { k: 'Fields', v: 'm h dom mon dow', note: '* means "every"' },
      { k: 'Runs as', v: 'You', note: 'with a minimal environment' },
    ],
    session: {
      run: 'crontab -l',
      prompt: '$',
      lines: [
        { text: '# m h  dom mon dow   command', n: 1 },
        { text: '0 2 * * * /home/user/backup.sh', n: 2 },
        { text: '*/5 * * * * /usr/bin/curl -s https://example.com/ping > /dev/null', n: 3 },
        { text: '30 9 * * 1 /home/user/report.sh >> /home/user/report.log 2>&1', n: 4 },
      ],
      notes: [
        { t: 'The column order', d: 'A comment kept as a reminder: minute, hour, day of month, month, day of week, then the command.' },
        { t: 'Every day at 02:00', d: 'Minute 0, hour 2, and stars for the rest: any day, any month, any weekday.' },
        { t: 'Every five minutes', d: '*/5 in the minute field means "every fifth minute". The output is thrown away so cron does not try to mail it.' },
        { t: 'Mondays at 09:30', d: 'Day of week 1 is Monday. Output and errors are appended to a log, which is how you find out why a job failed.' },
      ],
    },
    recipes: [
      { run: 'crontab -e', d: 'Edits your schedule. It is installed when you save and quit.' },
      { run: 'sudo crontab -l -u www-data', d: 'Lists another user’s jobs.' },
      { run: '@reboot /home/user/start.sh', d: 'A crontab line that runs once each time the machine starts.' },
      { run: 'systemctl list-timers', d: 'Lists systemd timers — the modern alternative to cron.' },
    ],
    security: {
      lede: ['A scheduled job is ', { b: 'a command that runs with nobody watching' }, '.'],
      points: [
        { t: 'A favourite place to persist', d: 'A line added to a crontab runs for ever. Reviewing every user’s crontab and /etc/cron.* is a standard step in checking a suspect machine.' },
        { t: 'Writable scripts run by root', d: 'If root’s crontab runs a script that another user can edit, that user can run anything as root. Check the permissions of every script cron calls.' },
        { t: 'Use full paths', d: 'Cron runs with a short PATH. A bare command name may not be found — or may find a different program from the one you meant.' },
      ],
    },
    protocols: [],
    related: ['systemctl', 'nohup'],
    footnote: 'System-wide jobs live in /etc/crontab and /etc/cron.d, where each line has an extra field naming the user.',
  },
  {
    slug: 'shutdown',
    cmd: 'shutdown',
    group: 'proc',
    pkg: 'systemd',
    fn: 'Powers off or restarts the machine, now or at a set time, warning logged-in users first.',
    kicker: 'Linux · process & service management',
    sub: 'power off or restart',
    lede: [
      { m: 'shutdown' },
      ' brings the system down in order: ',
      { a: 'services are stopped, data is written to disk, filesystems are unmounted' },
      '. It can be ',
      { b: 'scheduled for later and cancelled' },
      ', with a warning sent to everyone logged in.',
    ],
    takeaway: [{ a: 'shutdown -r now' }, ' restarts; ', { b: 'shutdown -h now' }, ' powers off. Both do it cleanly.'],
    points: [
      { k: 'Power off', v: 'shutdown -h now', note: 'or poweroff' },
      { k: 'Restart', v: 'shutdown -r now', note: 'or reboot' },
      { k: 'Later', v: '+10 or 23:00', note: 'minutes from now, or a time' },
      { k: 'Cancel', v: 'shutdown -c', note: 'before it happens' },
    ],
    session: {
      run: 'shutdown -r +10 "Kernel update, back in 5 minutes"',
      prompt: '#',
      lines: [
        { text: "Reboot scheduled for Wed 2026-09-30 10:52:07 IST, use 'shutdown -c' to cancel.", n: 1 },
        { text: 'shutdown -c', run: true, n: 2 },
        { text: 'shutdown -h now', run: true, n: 3 },
        { text: 'Connection to 192.0.2.10 closed by remote host.', n: 4 },
      ],
      notes: [
        { t: 'A restart in ten minutes', d: 'Everyone logged in sees the message, and new logins are refused shortly before the time.' },
        { t: 'Changed your mind', d: '-c cancels a scheduled shutdown. Users are told it was called off.' },
        { t: 'Power off immediately', d: '-h halts and powers off; "now" means no delay.' },
        { t: 'Over SSH, the connection drops', d: 'The machine is going down. If it is remote and you chose -h, someone must now press its power button.' },
      ],
    },
    recipes: [
      { run: 'sudo reboot', d: 'Restarts now. The same as shutdown -r now.' },
      { run: 'sudo poweroff', d: 'Powers off now.' },
      { run: 'sudo shutdown -r 23:30', d: 'Restarts at half past eleven tonight.' },
      { run: 'systemctl suspend', d: 'Suspends to memory instead of shutting down.' },
    ],
    security: {
      lede: ['Powering off a remote machine is ', { b: 'an outage you may not be able to undo from where you sit' }, '.'],
      points: [
        { t: 'Check which machine', d: 'With several SSH sessions open, it is easy to reboot the wrong one. Look at the host name in the prompt before pressing Enter.' },
        { t: '-h on a remote server', d: 'A halted machine does not come back by itself. Unless you have remote power control, use -r.' },
        { t: 'Reboots apply the patches', d: 'A kernel update does nothing until the machine restarts. Planned, announced reboots are part of keeping a server secure.' },
      ],
    },
    protocols: [],
    related: ['systemctl', 'uptime'],
    footnote: 'On systemd machines shutdown, reboot and poweroff are all front ends to systemctl.',
  },

  // ── packages & software ───────────────────────────────────────────────
  {
    slug: 'apt',
    cmd: 'apt',
    group: 'pkg',
    pkg: 'apt',
    fn: 'Installs, updates and removes software on Debian, Ubuntu and their relatives.',
    kicker: 'Linux · packages & software',
    sub: 'install software on Debian and Ubuntu',
    lede: [
      { m: 'apt' },
      ' is the package manager for Debian-family systems. It ',
      { a: 'downloads a program and everything it depends on from the distribution’s repositories' },
      ', and later ',
      { b: 'updates the whole system with two commands' },
      '.',
    ],
    takeaway: [{ a: 'apt update' }, ' refreshes the list of what is available; ', { b: 'apt upgrade' }, ' installs the newer versions.'],
    points: [
      { k: 'Refresh list', v: 'apt update', note: 'downloads no software' },
      { k: 'Upgrade all', v: 'apt upgrade', note: 'installs newer versions' },
      { k: 'Install', v: 'apt install NAME', note: 'with its dependencies' },
      { k: 'Needs root', v: 'For changes', note: 'searching does not' },
    ],
    session: {
      run: 'apt update',
      prompt: '#',
      lines: [
        { text: 'Hit:1 http://archive.ubuntu.com/ubuntu noble InRelease', n: 1 },
        { text: 'Get:2 http://security.ubuntu.com/ubuntu noble-security InRelease [126 kB]' },
        { text: 'Fetched 126 kB in 1s (118 kB/s)' },
        { text: '12 packages can be upgraded. Run \'apt list --upgradable\' to see them.', n: 2 },
        { text: 'apt install tree', run: true, n: 3 },
        { text: 'The following NEW packages will be installed:' },
        { text: '  tree' },
        { text: '0 upgraded, 1 newly installed, 0 to remove and 12 not upgraded.', n: 4 },
        { text: 'Need to get 47.1 kB of archives.' },
      ],
      notes: [
        { t: 'Checking each repository', d: 'Hit means the list has not changed; Get means a newer one was downloaded. No software is installed by this step.' },
        { t: 'What is out of date', d: 'Twelve installed packages have newer versions. "apt upgrade" would install them.' },
        { t: 'Installing a package', d: 'apt works out what else is needed and lists everything it will do before doing it.' },
        { t: 'The summary', d: 'One new package, nothing removed. Larger changes ask for confirmation at this point.' },
      ],
    },
    recipes: [
      { run: 'sudo apt update && sudo apt upgrade', d: 'The routine update: refresh the list, then install what is newer.' },
      { run: 'apt search "packet capture"', d: 'Searches package names and descriptions.' },
      { run: 'apt show nginx', d: 'Shows a package’s version, size, dependencies and description.' },
      { run: 'sudo apt autoremove', d: 'Removes packages that were installed as dependencies and are no longer needed.' },
    ],
    security: {
      lede: ['Updating is ', { b: 'the single most effective security task on a Linux machine' }, '.'],
      points: [
        { t: 'Most break-ins use known flaws', d: 'The fix usually existed before the attack. Regular "apt update && apt upgrade", or unattended-upgrades, closes those doors.' },
        { t: 'Packages are signed', d: 'apt verifies every repository’s signature. A warning about an unsigned or changed repository should stop you, not be clicked through.' },
        { t: 'Third-party repositories', d: 'Adding a repository gives its owner the power to install software as root on your machine at every update. Add as few as you can.' },
      ],
    },
    protocols: ['http', 'tls'],
    related: ['dpkg', 'dnf'],
    footnote: 'apt-get and apt-cache are the older commands with the same functions, and the ones to use in scripts.',
  },
  {
    slug: 'dpkg',
    cmd: 'dpkg',
    group: 'pkg',
    pkg: 'dpkg',
    fn: 'Installs a single .deb file, and answers questions about what is installed and which package owns a file.',
    kicker: 'Linux · packages & software',
    sub: 'the tool beneath apt',
    lede: [
      { m: 'dpkg' },
      ' is the low-level tool that apt drives. It ',
      { a: 'installs one .deb file you already have, without fetching dependencies' },
      ', and it is the way to ask ',
      { b: '"what is installed?" and "which package put this file here?"' },
    ],
    takeaway: ['apt fetches and resolves; ', { a: 'dpkg unpacks and keeps the records' }, '.'],
    points: [
      { k: 'List installed', v: 'dpkg -l', note: 'every package' },
      { k: 'Files in a package', v: 'dpkg -L NAME', note: 'where it put things' },
      { k: 'Owner of a file', v: 'dpkg -S PATH', note: 'which package' },
      { k: 'Install a file', v: 'dpkg -i file.deb', note: 'no dependency download' },
    ],
    session: {
      run: 'dpkg -l | grep openssh',
      prompt: '$',
      lines: [
        { text: 'ii  openssh-client  1:9.6p1-3ubuntu13.5  amd64  secure shell (SSH) client', n: 1 },
        { text: 'ii  openssh-server  1:9.6p1-3ubuntu13.5  amd64  secure shell (SSH) server' },
        { text: 'dpkg -S /usr/bin/ssh', run: true, n: 2 },
        { text: 'openssh-client: /usr/bin/ssh' },
        { text: 'dpkg -L tree | head -3', run: true, n: 3 },
        { text: '/.' },
        { text: '/usr' },
        { text: '/usr/bin' },
        { text: 'sudo dpkg --verify openssh-server', run: true, n: 4 },
      ],
      notes: [
        { t: 'ii means installed', d: 'The first column is the state, then the name, version, architecture and description.' },
        { t: 'Which package owns a file', d: '/usr/bin/ssh came from openssh-client. Useful for finding what to reinstall, or where a strange file came from.' },
        { t: 'What a package installed', d: 'Every path the package created, starting from the root.' },
        { t: 'No output is good news', d: '--verify compares installed files with what the package shipped. Silence means nothing has been altered.' },
      ],
    },
    recipes: [
      { run: 'sudo dpkg -i package.deb', d: 'Installs a downloaded .deb file.' },
      { run: 'sudo apt install -f', d: 'Fetches the dependencies a dpkg -i left missing.' },
      { run: 'dpkg -s nginx', d: 'Shows the status and details of one installed package.' },
      { run: 'dpkg -c package.deb', d: 'Lists the files inside a .deb before installing it.' },
    ],
    security: {
      lede: ['A .deb installed by hand ', { b: 'skips every check the repositories provide' }, '.'],
      points: [
        { t: 'A package runs scripts as root', d: 'Installation scripts inside a .deb execute as root. A package from an untrusted source is a root shell handed to its author.' },
        { t: 'It will not be updated', d: 'Software installed with dpkg -i from a download has no repository behind it, so security fixes never arrive unless you fetch them.' },
        { t: 'Verify system files', d: '"dpkg --verify" lists files that differ from the packaged originals — a quick test for binaries replaced by an intruder.' },
      ],
    },
    protocols: [],
    related: ['apt', 'dnf'],
    footnote: 'The equivalent on Fedora and RHEL is rpm: rpm -qa, rpm -ql, rpm -qf and rpm -V.',
  },
  {
    slug: 'dnf',
    cmd: 'dnf',
    group: 'pkg',
    pkg: 'dnf',
    fn: 'Installs, updates and removes software on Fedora, RHEL, Rocky and AlmaLinux.',
    kicker: 'Linux · packages & software',
    sub: 'install software on Fedora and RHEL',
    lede: [
      { m: 'dnf' },
      ' is the package manager of the Red Hat family. It does the job apt does on Debian: ',
      { a: 'resolves dependencies and installs from signed repositories' },
      '. The main difference in use is that ',
      { b: 'there is no separate "update the list" step' },
      '.',
    ],
    takeaway: ['On Fedora and RHEL, ', { a: 'dnf upgrade' }, ' is the whole routine update.'],
    points: [
      { k: 'Upgrade all', v: 'dnf upgrade', note: 'refreshes metadata itself' },
      { k: 'Install', v: 'dnf install NAME', note: 'with dependencies' },
      { k: 'Search', v: 'dnf search WORD', note: 'names and summaries' },
      { k: 'Undo', v: 'dnf history undo', note: 'reverses a transaction' },
    ],
    session: {
      run: 'dnf install tree',
      prompt: '#',
      lines: [
        { text: 'Last metadata expiration check: 0:12:41 ago on Wed 30 Sep 2026 10:29:26 AM IST.', n: 1 },
        { text: 'Dependencies resolved.' },
        { text: ' Package      Architecture   Version          Repository      Size', n: 2 },
        { text: 'Installing:' },
        { text: ' tree         x86_64         2.1.0-4.fc40     fedora          58 k' },
        { text: 'Install  1 Package', n: 3 },
        { text: 'Total download size: 58 k' },
        { text: 'Is this ok [y/N]: ', n: 4 },
      ],
      notes: [
        { t: 'Metadata is refreshed automatically', d: 'dnf checks how old its copy of the package lists is and updates them when needed.' },
        { t: 'The transaction, as a table', d: 'Each package with its architecture, version, and the repository it comes from.' },
        { t: 'The summary', d: 'What will be installed, upgraded or removed, and how much will be downloaded.' },
        { t: 'It waits for a yes', d: 'The capital N is the default: pressing Enter cancels. -y answers yes in advance, for scripts.' },
      ],
    },
    recipes: [
      { run: 'sudo dnf upgrade', d: 'Updates every installed package.' },
      { run: 'dnf provides /usr/bin/dig', d: 'Finds which package supplies a file or command.' },
      { run: 'dnf history', d: 'Lists past install and update transactions.' },
      { run: 'sudo dnf upgrade --security', d: 'Installs only the updates marked as security fixes.' },
    ],
    security: {
      lede: ['The package manager is ', { b: 'the trusted path by which software reaches the machine' }, '.'],
      points: [
        { t: 'Keep signature checking on', d: 'gpgcheck=1 in the repository settings makes dnf refuse unsigned packages. Turning it off to "fix" an error removes the protection.' },
        { t: 'Security-only updates', d: '"dnf upgrade --security" applies fixes without other changes — useful on servers where every change must be justified.' },
        { t: 'History is an audit trail', d: '"dnf history" records what was installed, when and by which user. Unexpected entries are worth following up.' },
      ],
    },
    protocols: ['http', 'tls'],
    related: ['apt', 'dpkg'],
    footnote: 'Older RHEL and CentOS releases use yum, which takes the same commands.',
  },
];

export const switches: Record<string, LinuxSwitch[]> = {
  pkill: [
    { flag: '-f', d: 'Match against the full command line, not only the process name.' },
    { flag: '-x', d: 'Match the name exactly, not as part of a longer name.' },
    { flag: '-u USER', d: 'Match only processes owned by this user.' },
    { flag: '-SIGNAL', d: 'Send this signal instead of TERM: -9, -HUP, -STOP.' },
    { flag: '-n', d: 'Match only the newest matching process. -o matches the oldest.' },
    { flag: '-e', d: 'Echo: print what was killed.' },
  ],
  jobs: [
    { flag: '-l', d: 'Also list each job’s process id.' },
    { flag: '-p', d: 'List only the process ids.' },
    { flag: '-r', d: 'Show running jobs only.' },
    { flag: '-s', d: 'Show stopped jobs only.' },
  ],
  /* nohup takes no switches of its own: everything after it is the command */
  nohup: [],
  journalctl: [
    { flag: '-u UNIT', d: 'Show the log of one service.' },
    { flag: '-f', d: 'Follow: print new entries as they arrive.' },
    { flag: '-e', d: 'Jump to the end of the log.' },
    { flag: '-b', d: 'Only entries from the current boot. -b -1 is the previous boot.' },
    { flag: '-p LEVEL', d: 'Only this priority and worse: err, warning, info.' },
    { flag: '--since TIME', d: 'From this time: "today", "1 hour ago", "2026-09-30 09:00".' },
    { flag: '-n NUM', d: 'Show the last NUM lines.' },
    { flag: '-k', d: 'Kernel messages only.' },
    { flag: '--no-pager', d: 'Print directly instead of opening a pager.' },
  ],
  crontab: [
    { flag: '-e', d: 'Edit your crontab.' },
    { flag: '-l', d: 'List your crontab.' },
    { flag: '-r', d: 'Remove your whole crontab — without asking.' },
    { flag: '-u USER', d: 'Work on another user’s crontab. Needs root.' },
    { flag: '-i', d: 'With -r, ask for confirmation first.' },
  ],
  shutdown: [
    { flag: '-h', d: 'Halt and power off.' },
    { flag: '-r', d: 'Reboot.' },
    { flag: '-c', d: 'Cancel a scheduled shutdown.' },
    { flag: 'now', d: 'Do it immediately. +10 means in ten minutes; 23:00 means at that time.' },
    { flag: '-k', d: 'Send the warning message only; do not shut down.' },
  ],
  apt: [
    { flag: '-y', d: 'Answer yes to prompts. For scripts.' },
    { flag: '--no-install-recommends', d: 'Install only the hard dependencies, not the suggested extras.' },
    { flag: '-s', d: 'Simulate: show what would happen, change nothing.' },
    { flag: '--purge', d: 'With remove, also delete the package’s configuration files.' },
    { flag: '--reinstall', d: 'With install, install the package again over itself.' },
    { flag: '-f', d: 'Fix broken dependencies.' },
  ],
  dpkg: [
    { flag: '-i FILE', d: 'Install a .deb file.' },
    { flag: '-r NAME', d: 'Remove a package, keeping its configuration.' },
    { flag: '-P NAME', d: 'Purge: remove a package and its configuration.' },
    { flag: '-l', d: 'List installed packages.' },
    { flag: '-L NAME', d: 'List the files a package installed.' },
    { flag: '-S PATH', d: 'Find the package that owns a file.' },
    { flag: '-s NAME', d: 'Show a package’s status and details.' },
    { flag: '--verify', d: 'Check installed files against the package’s records.' },
  ],
  dnf: [
    { flag: '-y', d: 'Answer yes to prompts.' },
    { flag: '--security', d: 'With upgrade, apply only security updates.' },
    { flag: '--refresh', d: 'Force the package lists to be downloaded again.' },
    { flag: '--assumeno', d: 'Answer no: show the transaction without doing it.' },
    { flag: '--enablerepo=NAME', d: 'Use a repository that is disabled by default, for this command.' },
    { flag: '-q', d: 'Quiet.' },
  ],
};
