import type { LinuxCommand } from '../linux-data';
import type { LinuxSwitch } from '../linux-switches';

/* Disks and how they are attached, and the commands that describe the machine
   itself: its kernel, its name, how long it has been up, and how to look
   things up. */

export const commands: LinuxCommand[] = [
  // ── disks & space ─────────────────────────────────────────────────────
  {
    slug: 'lsblk',
    cmd: 'lsblk',
    group: 'disk',
    pkg: 'util-linux',
    fn: 'Lists the disks and partitions attached to the machine, as a tree, with where each is mounted.',
    kicker: 'Linux · disks & space',
    sub: 'what disks are attached',
    lede: [
      { m: 'lsblk' },
      ' — list block devices — shows ',
      { a: 'every disk and the partitions on it' },
      ', with sizes and mount points. It is the command to run ',
      { b: 'before touching a disk, to be sure which device is which' },
      '.',
    ],
    takeaway: ['Before any command that writes to a disk, ', { a: 'lsblk tells you its real name' }, '.'],
    points: [
      { k: 'Shows', v: 'Disks and partitions', note: 'as a tree' },
      { k: 'Names', v: 'sda, nvme0n1', note: 'partitions add a number' },
      { k: 'Needs root', v: 'No', note: 'it only reads' },
      { k: 'More detail', v: '-f', note: 'filesystem, label, UUID' },
    ],
    session: {
      run: 'lsblk',
      prompt: '$',
      lines: [
        { text: 'NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS', n: 1 },
        { text: 'sda      8:0    0   100G  0 disk', n: 2 },
        { text: '├─sda1   8:1    0   1.1G  0 part /boot/efi' },
        { text: '└─sda2   8:2    0  98.9G  0 part /', n: 3 },
        { text: 'sdb      8:16   1  14.9G  0 disk', n: 4 },
        { text: '└─sdb1   8:17   1  14.9G  0 part' },
      ],
      notes: [
        { t: 'The columns', d: 'RM is 1 for removable media, RO is 1 for read-only, TYPE says disk or partition, and MOUNTPOINTS is where it appears in the tree.' },
        { t: 'A whole disk', d: 'sda is the first disk, 100 GB. The lines drawn beneath it are its partitions.' },
        { t: 'A mounted partition', d: 'sda2 holds the root filesystem. Its contents are what you see at /.' },
        { t: 'A USB stick, not mounted', d: 'RM is 1 and the size is 14.9G: removable. The empty MOUNTPOINTS column means its files are not yet reachable.' },
      ],
    },
    recipes: [
      { run: 'lsblk -f', d: 'Adds the filesystem type, label and UUID of each partition.' },
      { run: 'lsblk -o NAME,SIZE,MODEL,SERIAL', d: 'Chooses the columns — here, to identify the physical drives.' },
      { run: 'lsblk -d', d: 'Lists whole disks only, without their partitions.' },
      { run: 'sudo blkid', d: 'Prints the UUID and type of every partition, for use in /etc/fstab.' },
    ],
    security: {
      lede: ['Most disk disasters are ', { b: 'the right command run on the wrong device' }, '.'],
      points: [
        { t: 'Confirm the device first', d: 'Names such as sdb are handed out in the order disks are found and can change between boots. Check size and model with lsblk before dd, mkfs or fdisk.' },
        { t: 'Unexpected devices', d: 'A disk or USB device nobody recalls attaching is worth explaining — on a server, removable media should be rare.' },
        { t: 'Look for encryption', d: 'A partition of type crypt is encrypted with LUKS. A laptop whose data partition is not is readable by whoever takes the disk out.' },
      ],
    },
    protocols: [],
    related: ['df', 'mount'],
    footnote: 'SATA and USB disks appear as sd*, NVMe drives as nvme*, and virtual disks often as vd*.',
  },
  {
    slug: 'mount',
    cmd: 'mount',
    group: 'disk',
    pkg: 'util-linux',
    fn: 'Attaches a filesystem — a partition, USB stick or network share — to a directory in the tree.',
    kicker: 'Linux · disks & space',
    sub: 'attach a disk to the tree',
    lede: [
      { m: 'mount' },
      ' makes the contents of a filesystem appear under a directory. ',
      { a: 'A disk has no drive letter: it shows up wherever you mount it' },
      '. Run with no arguments, it ',
      { b: 'lists everything currently mounted' },
      '.',
    ],
    takeaway: ['Device, then directory: ', { a: 'mount /dev/sdb1 /mnt' }, ' — and the files appear under /mnt.'],
    points: [
      { k: 'Order', v: 'Device, then directory', note: 'the directory must exist' },
      { k: 'Needs root', v: 'Yes', note: 'for ordinary mounts' },
      { k: 'At every boot', v: '/etc/fstab', note: 'lists the permanent ones' },
      { k: 'Detach with', v: 'umount', note: 'no n after the u' },
    ],
    session: {
      run: 'mount /dev/sdb1 /mnt/usb',
      prompt: '#',
      lines: [
        { text: 'ls /mnt/usb', run: true, n: 1 },
        { text: 'backup.tar.gz  photos  resume.pdf' },
        { text: 'mount | grep sdb1', run: true, n: 2 },
        { text: '/dev/sdb1 on /mnt/usb type vfat (rw,relatime,fmask=0022,dmask=0022)' },
        { text: 'mount -o remount,ro /mnt/usb', run: true, n: 3 },
        { text: 'mount -a', run: true, n: 4 },
      ],
      notes: [
        { t: 'The disk’s files, under the directory', d: 'mount printed nothing, which means it worked. The contents of the USB stick are now at /mnt/usb.' },
        { t: 'What is mounted, and how', d: 'The device, the directory, the filesystem type, and the options: rw means it is writable.' },
        { t: 'Changing options without detaching', d: 'remount applies new options to a mounted filesystem. ro makes it read-only.' },
        { t: 'Mount everything in fstab', d: 'mount -a attaches every filesystem listed in /etc/fstab. Run it after editing that file, to find a mistake before the next boot does.' },
      ],
    },
    recipes: [
      { run: 'findmnt', d: 'Shows all mounts as a tree — easier to read than plain mount.' },
      { run: 'sudo mount -o ro /dev/sdb1 /mnt', d: 'Mounts read-only, so nothing on the disk can be changed.' },
      { run: 'sudo mount -t nfs 192.168.1.20:/export /mnt/nfs', d: 'Mounts a network share from another machine.' },
      { run: 'sudo mount -o loop image.iso /mnt/iso', d: 'Mounts a disk image file as if it were a disk.' },
    ],
    security: {
      lede: ['Mount options are ', { b: 'a security control applied to a whole filesystem' }, '.'],
      points: [
        { t: 'noexec, nosuid, nodev', d: 'Mounting /tmp and removable media with these options stops programs running from them and ignores set-uid bits — closing a common path to root.' },
        { t: 'Read-only for evidence', d: 'A disk under investigation is mounted with -o ro so that looking at it cannot alter timestamps or contents.' },
        { t: 'Network mounts carry trust', d: 'An NFS share is only as safe as its server and the network between. Passwords for CIFS shares belong in a root-only credentials file, not in fstab.' },
      ],
    },
    protocols: [],
    related: ['umount', 'lsblk'],
    footnote: 'On a desktop, removable media is mounted for you under /media; mount is for doing it by hand.',
  },
  {
    slug: 'umount',
    cmd: 'umount',
    group: 'disk',
    pkg: 'util-linux',
    fn: 'Detaches a mounted filesystem, after writing out any data still waiting in memory.',
    kicker: 'Linux · disks & space',
    sub: 'detach a disk safely',
    lede: [
      { m: 'umount' },
      ' — spelt without the first n — detaches a filesystem. Before letting go it ',
      { a: 'writes everything still held in memory to the disk' },
      ', which is why ',
      { b: 'a drive must be unmounted before it is unplugged' },
      '.',
    ],
    takeaway: ['"Safely remove" on a desktop is ', { a: 'umount with a friendlier name' }, '.'],
    points: [
      { k: 'Give it', v: 'Device or directory', note: 'either works' },
      { k: 'Refuses if', v: 'Something is using it', note: '"target is busy"' },
      { k: 'Needs root', v: 'Yes', note: 'as mount does' },
      { k: 'Spelling', v: 'umount', note: 'not unmount' },
    ],
    session: {
      run: 'umount /mnt/usb',
      prompt: '#',
      lines: [
        { text: 'umount: /mnt/usb: target is busy.', n: 1 },
        { text: 'lsof +f -- /mnt/usb', run: true, n: 2 },
        { text: 'COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME' },
        { text: 'bash    3310 user  cwd    DIR   8,17    16384    1 /mnt/usb' },
        { text: 'cd / && umount /mnt/usb', run: true, n: 3 },
        { text: 'ls /mnt/usb', run: true, n: 4 },
      ],
      notes: [
        { t: 'Busy means in use', d: 'A program has a file open there, or a shell is standing in the directory. Nothing was detached.' },
        { t: 'Finding who is using it', d: 'lsof lists the processes with something open on that filesystem. Here a shell’s current directory — cwd — is inside it.' },
        { t: 'Step out, then unmount', d: 'Once nothing is using the filesystem, umount succeeds silently.' },
        { t: 'The directory is empty again', d: 'The mount point remains, but the disk’s files are no longer reachable. Now it is safe to unplug.' },
      ],
    },
    recipes: [
      { run: 'sudo umount /dev/sdb1', d: 'Unmounts by device name instead of directory.' },
      { run: 'sudo umount -l /mnt/nfs', d: 'Lazy: detaches now and cleans up when it stops being used. For a hung network share.' },
      { run: 'sync', d: 'Writes all pending data to disk without unmounting.' },
      { run: 'udisksctl power-off -b /dev/sdb', d: 'Powers down a USB drive after unmounting, ready for removal.' },
    ],
    security: {
      lede: ['An unclean removal ', { b: 'loses data that the system had already told you was saved' }, '.'],
      points: [
        { t: 'Writes are delayed', d: 'A copy that has "finished" may still be in memory. Pulling the drive before umount returns can leave files truncated or the filesystem damaged.' },
        { t: 'Avoid forcing it', d: '-f and -l get past a busy mount but do not make it safe. Find and stop whatever is using it instead.' },
        { t: 'Unmount encrypted volumes when done', d: 'While an encrypted volume is mounted its contents are readable. Unmounting and closing it is what puts the protection back.' },
      ],
    },
    protocols: [],
    related: ['mount', 'lsblk'],
    footnote: 'fuser -vm /mnt/usb is another way to list what is keeping a mount busy.',
  },
  {
    slug: 'fdisk',
    cmd: 'fdisk',
    group: 'disk',
    pkg: 'util-linux',
    fn: 'Shows a disk’s partition table, and edits it: creating, deleting and resizing partitions.',
    kicker: 'Linux · disks & space',
    sub: 'read and edit the partition table',
    lede: [
      { m: 'fdisk' },
      ' works on the partition table — the map at the start of a disk that says where each partition begins and ends. ',
      { a: 'With -l it only lists' },
      '; opened on a disk it is an editor in which ',
      { b: 'nothing is changed until you write with w' },
      '.',
    ],
    takeaway: [{ a: 'fdisk -l' }, ' is safe to run any time. Everything else here can erase a disk.'],
    points: [
      { k: 'List', v: 'fdisk -l', note: 'reads only' },
      { k: 'Edit', v: 'fdisk /dev/sdb', note: 'interactive' },
      { k: 'Save', v: 'w', note: 'q quits without saving' },
      { k: 'Needs root', v: 'Yes', note: 'always' },
    ],
    session: {
      run: 'fdisk -l /dev/sdb',
      prompt: '#',
      lines: [
        { text: 'Disk /dev/sdb: 14.91 GiB, 16008609792 bytes, 31266816 sectors', n: 1 },
        { text: 'Disk model: Flash Drive' },
        { text: 'Units: sectors of 1 * 512 = 512 bytes' },
        { text: 'Disklabel type: dos', n: 2 },
        { text: '' },
        { text: 'Device     Boot Start      End  Sectors  Size Id Type', n: 3 },
        { text: '/dev/sdb1        2048 31266815 31264768 14.9G  c W95 FAT32 (LBA)' },
        { text: 'fdisk /dev/sdb', run: true, n: 4 },
        { text: 'Command (m for help): ' },
      ],
      notes: [
        { t: 'The disk itself', d: 'Its size and model. Check these against what you expect before going any further.' },
        { t: 'The kind of partition table', d: 'dos is the older MBR scheme; gpt is the modern one, needed for disks over 2 TB.' },
        { t: 'One line per partition', d: 'Where it starts and ends, its size, and the type recorded for it — here a FAT32 partition filling the stick.' },
        { t: 'The interactive editor', d: 'p prints the table, n makes a new partition, d deletes one. Changes stay in memory until w writes them; q leaves without saving.' },
      ],
    },
    recipes: [
      { run: 'sudo fdisk -l', d: 'Lists the partition tables of every disk.' },
      { run: 'sudo parted -l', d: 'The same information from parted, which some prefer for GPT disks.' },
      { run: 'sudo mkfs.ext4 /dev/sdb1', d: 'Creates a filesystem on a new partition — the step after partitioning.' },
      { run: 'sudo partprobe /dev/sdb', d: 'Asks the kernel to re-read a partition table after it has changed.' },
    ],
    security: {
      lede: ['Editing a partition table is ', { b: 'the quickest way to lose everything on a disk' }, '.'],
      points: [
        { t: 'Check the device, then check again', d: 'fdisk /dev/sda and fdisk /dev/sdb differ by one letter. Compare the size and model shown with lsblk before pressing w.' },
        { t: 'Deleting a partition does not erase data', d: 'It removes only the map. The contents remain on the disk and can be recovered — by you, or by whoever gets the disk next.' },
        { t: 'Wiping before disposal', d: 'To make data unrecoverable a disk must be overwritten or, better, have been encrypted from the start. Repartitioning is not wiping.' },
      ],
    },
    protocols: [],
    related: ['lsblk', 'mount'],
    footnote: 'A new partition has no filesystem until mkfs is run on it; until then it cannot be mounted.',
  },

  // ── system information ────────────────────────────────────────────────
  {
    slug: 'uname',
    cmd: 'uname',
    group: 'system',
    pkg: 'coreutils',
    fn: 'Prints the kernel name, its version, and the type of processor the system runs on.',
    kicker: 'Linux · system information',
    sub: 'which kernel is this',
    lede: [
      { m: 'uname' },
      ' identifies the running kernel. ',
      { a: 'uname -r gives the kernel version' },
      ' and -m the processor architecture — ',
      { b: 'the two facts needed to pick the right download or driver' },
      '.',
    ],
    takeaway: ['uname describes the ', { a: 'kernel' }, '; /etc/os-release describes the ', { b: 'distribution' }, '.'],
    points: [
      { k: 'Kernel version', v: 'uname -r', note: 'such as 6.8.0-45-generic' },
      { k: 'Architecture', v: 'uname -m', note: 'x86_64 or aarch64' },
      { k: 'Everything', v: 'uname -a', note: 'on one line' },
      { k: 'Distribution', v: 'Not shown', note: 'see /etc/os-release' },
    ],
    session: {
      run: 'uname -a',
      prompt: '$',
      lines: [
        { text: 'Linux netflow 6.8.0-45-generic #45-Ubuntu SMP PREEMPT_DYNAMIC Sun Aug 30 12:02:04 UTC 2026 x86_64 x86_64 x86_64 GNU/Linux', n: 1 },
        { text: 'uname -r', run: true, n: 2 },
        { text: '6.8.0-45-generic' },
        { text: 'uname -m', run: true, n: 3 },
        { text: 'x86_64' },
        { text: 'cat /etc/os-release | head -2', run: true, n: 4 },
        { text: 'PRETTY_NAME="Ubuntu 24.04.1 LTS"' },
        { text: 'NAME="Ubuntu"' },
      ],
      notes: [
        { t: 'All of it at once', d: 'Kernel name, host name, kernel release, build number and date, and the hardware architecture.' },
        { t: 'The kernel release', d: 'The version that matters for drivers and for known vulnerabilities. Its modules live in /lib/modules under this exact name.' },
        { t: 'The architecture', d: 'x86_64 is 64-bit Intel or AMD; aarch64 is 64-bit ARM. Software must be downloaded for the matching one.' },
        { t: 'The distribution is recorded elsewhere', d: 'uname knows nothing about Ubuntu or Fedora. That is in /etc/os-release.' },
      ],
    },
    recipes: [
      { run: 'uname -sr', d: 'Kernel name and release together.' },
      { run: 'hostnamectl', d: 'Kernel, distribution, architecture and hardware model in one report.' },
      { run: 'lsb_release -a', d: 'The distribution’s name, release and codename.' },
      { run: 'cat /proc/version', d: 'The kernel version with the compiler that built it.' },
    ],
    security: {
      lede: ['The kernel version is ', { b: 'what decides which kernel vulnerabilities apply' }, '.'],
      points: [
        { t: 'First thing an attacker checks', d: 'After getting a shell, uname -a is run to look up privilege-escalation exploits for that exact kernel. An old kernel is an invitation.' },
        { t: 'Updated is not the same as running', d: 'A kernel update takes effect only after a reboot. If uname -r shows an older version than the newest in /boot, the fix is not yet active.' },
        { t: 'Version strings in banners', d: 'Services that announce the operating system and kernel give that information to anyone who connects. Turn it off where you can.' },
      ],
    },
    protocols: [],
    related: ['hostname', 'uptime'],
    footnote: 'Distribution kernels carry backported fixes, so a version number alone does not prove a kernel is vulnerable.',
  },
  {
    slug: 'hostname',
    cmd: 'hostname',
    group: 'system',
    pkg: 'hostname',
    fn: 'Prints the name of the machine, and with -I the IP addresses it has.',
    kicker: 'Linux · system information',
    sub: 'what is this machine called',
    lede: [
      { m: 'hostname' },
      ' prints the system’s name — the one in your shell prompt. ',
      { a: 'With -I it prints the machine’s IP addresses' },
      ', which is the quickest way to answer ',
      { b: '"what is my address?"' },
    ],
    takeaway: ['With several terminals open, ', { a: 'the host name is how you know which machine you are about to change' }, '.'],
    points: [
      { k: 'Prints', v: 'The host name', note: 'as in the prompt' },
      { k: 'Addresses', v: 'hostname -I', note: 'all of them, on one line' },
      { k: 'Full name', v: 'hostname -f', note: 'with the domain' },
      { k: 'To change it', v: 'hostnamectl', note: 'so it survives a reboot' },
    ],
    session: {
      run: 'hostname',
      prompt: '$',
      lines: [
        { text: 'netflow', n: 1 },
        { text: 'hostname -I', run: true, n: 2 },
        { text: '192.168.1.42 10.8.0.2 ' },
        { text: 'hostname -f', run: true, n: 3 },
        { text: 'netflow.lab.example' },
        { text: 'sudo hostnamectl set-hostname web01', run: true, n: 4 },
      ],
      notes: [
        { t: 'The short name', d: 'The same name that appears after the @ in the prompt.' },
        { t: 'Every address the machine has', d: 'Two here: one on the local network and one on a VPN. The loopback address is left out.' },
        { t: 'The fully qualified name', d: 'The host name with its DNS domain, where one is configured.' },
        { t: 'Renaming the machine', d: 'hostnamectl writes the new name to /etc/hostname, so it is kept after a reboot. Open a new shell to see it in the prompt.' },
      ],
    },
    recipes: [
      { run: 'hostnamectl', d: 'Shows the name together with the OS, kernel and hardware.' },
      { run: 'cat /etc/hostname', d: 'The file the name is read from at boot.' },
      { run: 'hostname -i', d: 'The address the host name itself resolves to.' },
      { run: 'getent hosts $(hostname)', d: 'Checks how the machine resolves its own name.' },
    ],
    security: {
      lede: ['A host name ', { b: 'tells an outsider what a machine is for' }, '.'],
      points: [
        { t: 'Names give things away', d: 'db-prod-01 and vpn-gateway advertise their role to anyone who sees them in a banner, a certificate or a DNS record.' },
        { t: 'Check before you act', d: 'Running a destructive command on production instead of the test server is a classic accident. Look at the prompt, or run hostname, first.' },
        { t: 'Keep /etc/hosts in step', d: 'If the machine’s own name does not resolve, sudo becomes slow and some services fail. After renaming, update the entry in /etc/hosts.' },
      ],
    },
    protocols: ['dns', 'ip4'],
    related: ['uname', 'ip-addr'],
    footnote: 'hostname NAME changes the name only until reboot; hostnamectl makes it permanent.',
  },
  {
    slug: 'uptime',
    cmd: 'uptime',
    group: 'system',
    pkg: 'procps',
    fn: 'Shows how long the system has been running, how many users are logged in, and the load average.',
    kicker: 'Linux · system information',
    sub: 'how long, and how busy',
    lede: [
      { m: 'uptime' },
      ' prints one line: the time, ',
      { a: 'how long since the last boot' },
      ', the number of logged-in users, and ',
      { b: 'the load average over 1, 5 and 15 minutes' },
      '.',
    ],
    takeaway: ['Compare the load with the number of CPU cores: ', { a: 'at or below the core count, the machine is keeping up' }, '.'],
    points: [
      { k: 'Up', v: 'Time since boot', note: 'days, hours, minutes' },
      { k: 'Load', v: 'Three averages', note: '1, 5 and 15 minutes' },
      { k: 'Judge against', v: 'CPU cores', note: 'nproc prints the count' },
      { k: 'Same line as', v: 'top’s first', note: 'and w’s' },
    ],
    session: {
      run: 'uptime',
      prompt: '$',
      lines: [
        { text: ' 10:42:07 up 12 days,  3:14,  2 users,  load average: 0.42, 0.31, 0.27', n: 1 },
        { text: 'nproc', run: true, n: 2 },
        { text: '4' },
        { text: 'uptime -s', run: true, n: 3 },
        { text: '2026-09-18 07:28:02' },
      ],
      notes: [
        { t: 'Reading the line', d: 'It is 10:42; the system has been up 12 days and 3 hours; two users are logged in. The load has been steady at well under 1.' },
        { t: 'Four cores', d: 'A load of 4.0 would mean all four are fully busy. 0.42 means the machine is mostly idle.' },
        { t: 'When it booted', d: '-s gives the date and time of the last boot — useful for matching against the time of an outage.' },
      ],
    },
    recipes: [
      { run: 'uptime -p', d: 'Prints only the running time, in words.' },
      { run: 'w', d: 'The same header, followed by who is logged in and what they are running.' },
      { run: 'cat /proc/loadavg', d: 'The raw load figures, as scripts read them.' },
      { run: 'last reboot | head -3', d: 'Lists the most recent restarts.' },
    ],
    security: {
      lede: ['A long uptime is ', { b: 'not something to be proud of' }, '.'],
      points: [
        { t: 'Months up means months unpatched', d: 'Kernel fixes need a reboot. A server up for 400 days is running a kernel with every vulnerability found in that time.' },
        { t: 'An unexpected reboot', d: 'If uptime is a few hours and nobody restarted the machine, find out why: a crash, a power loss, or someone covering their tracks.' },
        { t: 'Unexplained load', d: 'A high load on a machine that should be idle points to a runaway process — or one that should not be there at all.' },
      ],
    },
    protocols: [],
    related: ['top', 'uname'],
    footnote: 'Load on Linux counts processes waiting for disk as well as for CPU, so a slow disk raises it too.',
  },
  {
    slug: 'free',
    cmd: 'free',
    group: 'system',
    pkg: 'procps',
    fn: 'Shows how much memory and swap the system has, how much is used, and how much is available.',
    kicker: 'Linux · system information',
    sub: 'how much memory is left',
    lede: [
      { m: 'free' },
      ' reports memory. The column that matters is ',
      { a: '"available" — what programs can still have' },
      '. The "free" column looks alarmingly small on a healthy machine, because ',
      { b: 'Linux uses spare memory as disk cache and gives it back on demand' },
      '.',
    ],
    takeaway: ['Read ', { a: 'available' }, ', not free. Unused memory is wasted memory, so Linux fills it with cache.'],
    points: [
      { k: 'Readable', v: 'free -h', note: 'Gi and Mi instead of kilobytes' },
      { k: 'Watch', v: 'available', note: 'the real headroom' },
      { k: 'buff/cache', v: 'Reclaimable', note: 'released when needed' },
      { k: 'Swap in use', v: 'A warning', note: 'memory has run short' },
    ],
    session: {
      run: 'free -h',
      prompt: '$',
      lines: [
        { text: '               total        used        free      shared  buff/cache   available', n: 1 },
        { text: 'Mem:           7.8Gi       3.0Gi       1.2Gi       212Mi       3.5Gi       4.4Gi', n: 2 },
        { text: 'Swap:          2.0Gi          0B       2.0Gi', n: 3 },
      ],
      notes: [
        { t: 'The columns', d: 'Total installed, used by programs, completely unused, shared, used for cache, and available to new programs.' },
        { t: 'Only 1.2Gi free, but 4.4Gi available', d: '3.5Gi is disk cache. It makes file access faster and is handed back the moment a program needs the memory.' },
        { t: 'Swap is untouched', d: 'Swap is disk space used when memory runs out. Zero used means the machine has never been short.' },
      ],
    },
    recipes: [
      { run: 'free -h -s 2', d: 'Repeats every two seconds, to watch memory change.' },
      { run: 'free -m', d: 'Shows the figures in mebibytes.' },
      { run: 'cat /proc/meminfo | head -5', d: 'The kernel’s own figures, which free reads.' },
      { run: 'ps aux --sort=-%mem | head -5', d: 'Lists the processes using the most memory.' },
    ],
    security: {
      lede: ['Running out of memory ', { b: 'makes the kernel choose a process to kill' }, '.'],
      points: [
        { t: 'The OOM killer', d: 'When memory is exhausted the kernel kills a process to survive — often the database. "dmesg | grep -i oom" shows whether it has happened.' },
        { t: 'Memory exhaustion as an attack', d: 'A request that makes a service allocate without limit can take the whole machine down. Limits in systemd units and containers confine the damage.' },
        { t: 'Swap holds secrets', d: 'Whatever was in memory — keys, passwords — can be written to swap in plain text. Encrypted swap protects it on a stolen disk.' },
      ],
    },
    protocols: [],
    related: ['top', 'df'],
    footnote: 'Gi and Mi are powers of 1024; --si switches to powers of 1000.',
  },
  {
    slug: 'date',
    cmd: 'date',
    group: 'system',
    pkg: 'coreutils',
    fn: 'Prints the current date and time, in any format, and converts between time zones and timestamps.',
    kicker: 'Linux · system information',
    sub: 'the time, in any format',
    lede: [
      { m: 'date' },
      ' prints the system clock. With a format string after a plus sign it ',
      { a: 'produces a date in exactly the shape you want' },
      ' — used constantly to ',
      { b: 'name backups and log files' },
      '.',
    ],
    takeaway: [{ a: 'date +%F' }, ' gives 2026-09-30: the form that sorts correctly and belongs in file names.'],
    points: [
      { k: 'Format', v: '+%F %T', note: 'date and time, ISO style' },
      { k: 'In file names', v: '$(date +%F)', note: 'backup-2026-09-30.tar.gz' },
      { k: 'UTC', v: 'date -u', note: 'no time zone confusion' },
      { k: 'Set by', v: 'NTP, normally', note: 'not by hand' },
    ],
    session: {
      run: 'date',
      prompt: '$',
      lines: [
        { text: 'Wed Sep 30 10:42:07 IST 2026', n: 1 },
        { text: 'date +"%F %T"', run: true, n: 2 },
        { text: '2026-09-30 10:42:07' },
        { text: 'date -u', run: true, n: 3 },
        { text: 'Wed Sep 30 05:12:07 UTC 2026' },
        { text: 'date -d @1790745127', run: true, n: 4 },
        { text: 'Wed Sep 30 10:42:07 IST 2026' },
      ],
      notes: [
        { t: 'The default form', d: 'Day, date, time, time zone and year, in the system’s local time.' },
        { t: 'A format of your own', d: '%F is year-month-day and %T is hours:minutes:seconds. Everything after the + is the template.' },
        { t: 'The same moment in UTC', d: 'Five and a half hours behind Indian time. Logs from machines in different zones are compared in UTC.' },
        { t: 'From a Unix timestamp', d: 'Many logs record time as seconds since 1970. -d @number turns one back into a readable date.' },
      ],
    },
    recipes: [
      { run: 'date +%s', d: 'Prints the current time as a Unix timestamp.' },
      { run: 'tar -czf backup-$(date +%F).tar.gz site/', d: 'Puts today’s date in a file name.' },
      { run: 'date -d "next friday"', d: 'Works out a date described in words.' },
      { run: 'timedatectl', d: 'Shows the time zone and whether the clock is synchronised by NTP.' },
    ],
    security: {
      lede: ['Security depends on ', { b: 'machines agreeing what time it is' }, '.'],
      points: [
        { t: 'A wrong clock breaks things', d: 'TLS certificates look expired or not yet valid, Kerberos logins fail, and one-time codes are rejected when the clock has drifted.' },
        { t: 'Logs are only comparable in sync', d: 'Tracing an incident across several machines needs their timestamps to line up. Keep NTP running and prefer UTC on servers.' },
        { t: 'Who can set the clock', d: 'Changing the time needs root, because moving it backwards can hide activity or revive an expired credential.' },
      ],
    },
    protocols: ['ntp'],
    related: ['uptime', 'touch'],
    footnote: 'The time zone abbreviation shown depends on the system setting; IST here is Indian Standard Time.',
  },
  {
    slug: 'man',
    cmd: 'man',
    group: 'system',
    pkg: 'man-db',
    fn: 'Opens the manual page for a command: what it does, every option, and often examples.',
    kicker: 'Linux · system information',
    sub: 'the manual, built in',
    lede: [
      { m: 'man' },
      ' shows the reference manual for nearly every command on the system. ',
      { a: 'It is installed with the command and matches the exact version you have' },
      ' — which a web search does not guarantee. It opens in less, so ',
      { b: '/ searches and q quits' },
      '.',
    ],
    takeaway: ['Not sure what a switch does? ', { a: 'man command, then /-x' }, ' to jump to it.'],
    points: [
      { k: 'Open', v: 'man ls', note: 'q to quit' },
      { k: 'Search inside', v: '/word', note: 'n for the next match' },
      { k: 'Find a command', v: 'man -k word', note: 'searches the descriptions' },
      { k: 'Shorter help', v: 'command --help', note: 'a quick summary' },
    ],
    session: {
      run: 'man ls',
      prompt: '$',
      lines: [
        { text: 'LS(1)                     User Commands                    LS(1)', n: 1 },
        { text: '' },
        { text: 'NAME' },
        { text: '       ls - list directory contents' },
        { text: 'SYNOPSIS', n: 2 },
        { text: '       ls [OPTION]... [FILE]...' },
        { text: 'man -k "list directory"', run: true, n: 3 },
        { text: 'dir (1)              - list directory contents' },
        { text: 'ls (1)               - list directory contents' },
        { text: 'man 5 passwd', run: true, n: 4 },
      ],
      notes: [
        { t: 'The header: name and section', d: 'The (1) is the section. Section 1 is user commands, 5 is file formats, 8 is administration commands.' },
        { t: 'The synopsis', d: 'How the command is written. Square brackets mark optional parts, and three dots mean "one or more".' },
        { t: 'Searching for a command by what it does', d: '-k looks through the one-line descriptions of every page — for when you know the task but not the name.' },
        { t: 'Asking for a section', d: 'passwd is both a command and a file. man 5 passwd opens the page describing the format of /etc/passwd.' },
      ],
    },
    recipes: [
      { run: 'ls --help', d: 'A short summary of options, printed straight to the terminal.' },
      { run: 'whatis tar', d: 'Prints just the one-line description.' },
      { run: 'man -f printf', d: 'Lists every section that has a page of that name.' },
      { run: 'tldr tar', d: 'Practical examples rather than a full reference — a separate package.' },
    ],
    security: {
      lede: ['Reading the manual is ', { b: 'how you find out what a pasted command will really do' }, '.'],
      points: [
        { t: 'Look up switches before running', d: 'A command copied from a forum may contain an option you would not have chosen. Thirty seconds in the manual is cheaper than the mistake.' },
        { t: 'The local page is the accurate one', d: 'Options differ between versions and between Linux and macOS. man describes the program actually installed.' },
        { t: 'Read the security notes', d: 'Many pages have a section on security considerations — ssh, sudo and tar among them. It is where the sharp edges are documented.' },
      ],
    },
    protocols: [],
    related: ['which', 'history'],
    footnote: 'Minimal server and container images often leave the manual pages out to save space.',
  },
  {
    slug: 'history',
    cmd: 'history',
    group: 'system',
    pkg: 'bash',
    fn: 'Lists the commands you have typed, numbered, so they can be searched and run again.',
    kicker: 'Linux · system information',
    sub: 'what did I type',
    lede: [
      { m: 'history' },
      ' prints your recent commands with a number beside each. ',
      { a: 'Any of them can be run again by number' },
      ', and ',
      { b: 'Ctrl+R searches backwards through them as you type' },
      ' — the fastest way to find a long command from last week.',
    ],
    takeaway: [{ a: 'Ctrl+R' }, ', then a few letters, finds a command you ran before. Enter runs it.'],
    points: [
      { k: 'List', v: 'history', note: 'numbered, oldest first' },
      { k: 'Search', v: 'Ctrl+R', note: 'type part of the command' },
      { k: 'Run again', v: '!NUM or !!', note: '!! is the last command' },
      { k: 'Stored in', v: '~/.bash_history', note: 'written when the shell exits' },
    ],
    session: {
      run: 'history | tail -4',
      prompt: '$',
      lines: [
        { text: '  501  cd /var/www/site', n: 1 },
        { text: '  502  ls -la' },
        { text: '  503  sudo systemctl restart nginx' },
        { text: '  504  history | tail -4' },
        { text: '!503', run: true, n: 2 },
        { text: 'sudo systemctl restart nginx' },
        { text: 'apt update', run: true },
        { text: 'sudo !!', run: true, n: 3 },
        { text: 'sudo apt update' },
      ],
      notes: [
        { t: 'Numbered commands', d: 'The most recent are at the bottom. The number is what you use to refer to one.' },
        { t: 'Running by number', d: '!503 runs command 503 again. The shell prints the command it expanded to before running it.' },
        { t: '!! is the previous command', d: 'Forgot sudo? "sudo !!" repeats the last command with sudo in front.' },
      ],
    },
    recipes: [
      { run: 'history | grep ssh', d: 'Finds every earlier command that mentioned ssh.' },
      { run: 'history -c', d: 'Clears the history held in this shell’s memory.' },
      { run: 'history -d 503', d: 'Deletes a single entry by number.' },
      { run: ' export TOKEN=abc123', d: 'A leading space keeps a command out of history, where HISTCONTROL is set to ignorespace.' },
    ],
    security: {
      lede: ['Your history is ', { b: 'a plain-text record of everything you typed' }, ', passwords included.'],
      points: [
        { t: 'Secrets end up here', d: 'A password given as an argument, or a token in an export, is saved to ~/.bash_history in the clear. It is one of the first files read on a compromised account.' },
        { t: 'It is a weak audit trail', d: 'History is written by the user’s own shell and can be edited or switched off. For real accountability use auditd or sudo’s logging.' },
        { t: 'A cleared history is a clue', d: 'An empty history file, or one linked to /dev/null, on an account that is used daily suggests someone tidied up.' },
      ],
    },
    protocols: [],
    related: ['man', 'alias'],
    footnote: 'This describes bash. zsh keeps its history in ~/.zsh_history and behaves similarly.',
  },
  {
    slug: 'alias',
    cmd: 'alias',
    group: 'system',
    pkg: 'bash',
    fn: 'Defines a short name for a longer command, and lists the ones already defined.',
    kicker: 'Linux · system information',
    sub: 'a shortcut for a command',
    lede: [
      { m: 'alias' },
      ' gives a command a nickname. ',
      { a: 'Type the short name and the shell replaces it with the full command' },
      '. An alias lasts only for the current shell unless ',
      { b: 'it is written into ~/.bashrc' },
      '.',
    ],
    takeaway: ['If you type it ten times a day, ', { a: 'give it a two-letter name' }, '.'],
    points: [
      { k: 'Define', v: "alias ll='ls -la'", note: 'no spaces around the =' },
      { k: 'List', v: 'alias', note: 'with no arguments' },
      { k: 'Remove', v: 'unalias ll', note: 'for this shell' },
      { k: 'Keep it', v: '~/.bashrc', note: 'read at every new shell' },
    ],
    session: {
      run: 'alias',
      prompt: '$',
      lines: [
        { text: "alias grep='grep --color=auto'", n: 1 },
        { text: "alias ll='ls -alF'" },
        { text: "alias gs='git status'", run: true, n: 2 },
        { text: 'type ll', run: true, n: 3 },
        { text: "ll is aliased to `ls -alF'" },
        { text: "echo \"alias gs='git status'\" >> ~/.bashrc", run: true, n: 4 },
      ],
      notes: [
        { t: 'Aliases you already have', d: 'Most distributions define a few. This is why grep shows colour and ll works without you having set anything up.' },
        { t: 'Defining one', d: 'From now on, in this shell, gs runs git status. Quote the command so the spaces are kept together.' },
        { t: 'type shows what a name means', d: 'It reports that ll is an alias and what it expands to.' },
        { t: 'Making it permanent', d: 'Appending the line to ~/.bashrc defines the alias in every new shell. Run "source ~/.bashrc" to load it now.' },
      ],
    },
    recipes: [
      { run: "alias rm='rm -i'", d: 'Makes rm ask before each removal.' },
      { run: '\\ls', d: 'A leading backslash runs the real command, ignoring any alias.' },
      { run: 'unalias -a', d: 'Removes every alias from the current shell.' },
      { run: "alias ports='ss -tulpn'", d: 'A memorable name for a command with awkward switches.' },
    ],
    security: {
      lede: ['An alias means ', { b: 'the command you type may not be the command that runs' }, '.'],
      points: [
        { t: 'A hijacked alias', d: 'Someone with write access to your .bashrc can alias sudo to a script that records your password and then runs the real sudo. Check with "type sudo".' },
        { t: 'Aliases are not a safety net', d: "alias rm='rm -i' is not there in scripts, under sudo, or on the next machine. Do not let it teach you to type rm carelessly." },
        { t: 'Protect your dot files', d: '~/.bashrc and ~/.profile run at every login. They should be writable only by you.' },
      ],
    },
    protocols: [],
    related: ['history', 'which'],
    footnote: 'For anything that needs arguments in the middle, write a shell function instead of an alias.',
  },
];

export const switches: Record<string, LinuxSwitch[]> = {
  lsblk: [
    { flag: '-f', d: 'Show filesystem type, label, UUID and mount point.' },
    { flag: '-o COLUMNS', d: 'Choose the columns, such as NAME,SIZE,MODEL.' },
    { flag: '-d', d: 'List whole disks only, not partitions.' },
    { flag: '-p', d: 'Print full device paths: /dev/sda1.' },
    { flag: '-b', d: 'Print sizes in bytes.' },
    { flag: '-J', d: 'Print JSON, for scripts.' },
  ],
  mount: [
    { flag: '-t TYPE', d: 'The filesystem type: ext4, vfat, nfs, cifs.' },
    { flag: '-o OPTIONS', d: 'Mount options, comma-separated: ro, noexec, nosuid, loop.' },
    { flag: '-a', d: 'Mount everything listed in /etc/fstab.' },
    { flag: '-r', d: 'Mount read-only. The same as -o ro.' },
    { flag: '-v', d: 'Verbose: describe what is being done.' },
  ],
  umount: [
    { flag: '-l', d: 'Lazy: detach now, clean up when no longer in use.' },
    { flag: '-f', d: 'Force, for an unreachable network filesystem.' },
    { flag: '-R', d: 'Recursive: unmount everything mounted beneath as well.' },
    { flag: '-a', d: 'Unmount all filesystems.' },
    { flag: '-v', d: 'Verbose.' },
  ],
  fdisk: [
    { flag: '-l', d: 'List partition tables and exit. Changes nothing.' },
    { flag: '-x', d: 'Like -l, with more detail.' },
    { flag: '-u', d: 'Show sizes in sectors.' },
    { flag: '-w auto', d: 'Wipe old filesystem signatures when creating a table.' },
  ],
  uname: [
    { flag: '-a', d: 'All: print every field on one line.' },
    { flag: '-r', d: 'The kernel release.' },
    { flag: '-m', d: 'The machine architecture: x86_64, aarch64.' },
    { flag: '-s', d: 'The kernel name. This is the default.' },
    { flag: '-n', d: 'The host name.' },
    { flag: '-v', d: 'The kernel build number and date.' },
  ],
  hostname: [
    { flag: '-I', d: 'Print all the IP addresses of the host.' },
    { flag: '-f', d: 'Print the fully qualified domain name.' },
    { flag: '-s', d: 'Print the short name, cut at the first dot.' },
    { flag: '-d', d: 'Print the DNS domain name.' },
    { flag: '-i', d: 'Print the address the host name resolves to.' },
  ],
  uptime: [
    { flag: '-p', d: 'Pretty: print only the running time, in words.' },
    { flag: '-s', d: 'Since: print the date and time the system booted.' },
  ],
  free: [
    { flag: '-h', d: 'Human-readable units.' },
    { flag: '-m', d: 'Show mebibytes. -g shows gibibytes.' },
    { flag: '-s SECS', d: 'Repeat every SECS seconds.' },
    { flag: '-t', d: 'Add a line totalling memory and swap.' },
    { flag: '-w', d: 'Wide: show buffers and cache as separate columns.' },
  ],
  date: [
    { flag: '+FORMAT', d: 'Print using a format: %F is the date, %T the time, %s the timestamp.' },
    { flag: '-u', d: 'Use UTC instead of local time.' },
    { flag: '-d STRING', d: 'Show the time described, such as "yesterday" or "@1790745127".' },
    { flag: '-I', d: 'ISO 8601 format: 2026-09-30.' },
    { flag: '-R', d: 'RFC 5322 format, as used in email headers.' },
    { flag: '-s STRING', d: 'Set the system clock. Needs root.' },
  ],
  man: [
    { flag: '-k WORD', d: 'Search the descriptions of all pages for a word.' },
    { flag: '-f NAME', d: 'List the sections that have a page of this name.' },
    { flag: 'NUM', d: 'A section number before the name: man 5 passwd.' },
    { flag: '-a', d: 'Show every matching page, one after another.' },
  ],
  history: [
    { flag: 'NUM', d: 'Show only the last NUM commands: history 20.' },
    { flag: '-c', d: 'Clear the history in this shell.' },
    { flag: '-d NUM', d: 'Delete entry number NUM.' },
    { flag: '-w', d: 'Write the current history to the history file now.' },
    { flag: '-a', d: 'Append this session’s new lines to the history file.' },
  ],
  alias: [
    { flag: '-p', d: 'Print all aliases in a form that can be reused as input.' },
  ],
};
