import type { LinuxCommand } from '../linux-data';
import type { LinuxSwitch } from '../linux-switches';

/* Reading files, and the small tools that reshape text as it passes through a
   pipe. Each does one thing; the point of the section is that they combine. */

export const commands: LinuxCommand[] = [
  // ── reading files ─────────────────────────────────────────────────────
  {
    slug: 'head',
    cmd: 'head',
    group: 'read',
    pkg: 'coreutils',
    fn: 'Prints the first lines of a file — ten unless told otherwise.',
    kicker: 'Linux · reading files',
    sub: 'the start of a file',
    lede: [
      { m: 'head' },
      ' prints the beginning of a file and stops. It is how you ',
      { a: 'look at what a file contains without printing all of it' },
      ', and at the end of a pipe it ',
      { b: 'cuts long output down to the first few lines' },
      '.',
    ],
    takeaway: ['A glance at the top is usually enough to know ', { a: 'what kind of file you are holding' }, '.'],
    points: [
      { k: 'Prints', v: 'The first 10 lines', note: 'unless -n says otherwise' },
      { k: 'Opposite', v: 'tail', note: 'prints the last lines' },
      { k: 'In a pipe', v: 'Limits output', note: 'command | head' },
      { k: 'By bytes', v: '-c NUM', note: 'instead of lines' },
    ],
    session: {
      run: 'head -n 3 data.csv',
      prompt: '$',
      lines: [
        { text: 'id,name,department,salary', n: 1 },
        { text: '1,Asha,Engineering,72000' },
        { text: '2,Ravi,Support,41000' },
        { text: 'ls -t | head -1', run: true, n: 2 },
        { text: 'report-2026-09-30.txt' },
        { text: 'head -n -1 data.csv | wc -l', run: true, n: 3 },
        { text: '120' },
      ],
      notes: [
        { t: 'The header and two rows', d: 'Three lines are enough to see the columns and the shape of the data without scrolling through the rest.' },
        { t: 'head at the end of a pipe', d: 'ls -t lists newest first; head -1 keeps only the first line. Together: the most recently changed file.' },
        { t: 'A negative count', d: '-n -1 means "everything except the last line". The file has 121 lines, so 120 are passed on.' },
      ],
    },
    recipes: [
      { run: 'head -c 100 file.bin', d: 'Prints the first 100 bytes rather than lines.' },
      { run: 'head -n 5 *.log', d: 'Prints the start of several files, each under a header with its name.' },
      { run: 'head -n 20 app.log | tail -n 5', d: 'Prints lines 16 to 20.' },
      { run: 'dmesg | head', d: 'Shows just the start of a long output.' },
    ],
    security: {
      lede: ['Looking at the start of a file is ', { b: 'a safe way to identify it before trusting it' }, '.'],
      points: [
        { t: 'Check what a file really is', d: 'A file named invoice.pdf that begins with "MZ" or "#!/bin/sh" is a program, not a document. head -c 16 piped to xxd shows the first bytes.' },
        { t: 'Read scripts before running them', d: 'The first lines of an install script show its interpreter and intent. Read the whole thing before piping it to a shell.' },
        { t: 'Avoid printing whole secrets', d: 'When checking that a key file exists and looks right, head -1 shows the header line without putting the key on screen.' },
      ],
    },
    protocols: [],
    related: ['tail', 'cat'],
    footnote: 'The "file" command identifies a file’s type properly, from its contents rather than its name.',
  },
  {
    slug: 'less',
    cmd: 'less',
    group: 'read',
    pkg: 'less',
    fn: 'Opens a file for reading one screen at a time, with scrolling and search.',
    kicker: 'Linux · reading files',
    sub: 'read a long file',
    lede: [
      { m: 'less' },
      ' is a pager: it shows one screen of a file and waits. You can ',
      { a: 'scroll both ways, jump to the end, and search' },
      ', and it opens huge files instantly because ',
      { b: 'it reads only the part being shown' },
      '.',
    ],
    takeaway: ['cat prints and leaves; ', { a: 'less lets you move around' }, '. Press q to quit.'],
    points: [
      { k: 'Scroll', v: 'Arrows, Space, b', note: 'line, page down, page up' },
      { k: 'Search', v: '/word', note: 'n for next, N for previous' },
      { k: 'Jump', v: 'g and G', note: 'start and end of the file' },
      { k: 'Quit', v: 'q', note: 'nothing is changed' },
    ],
    session: {
      run: 'less /var/log/syslog',
      prompt: '$',
      lines: [
        { text: 'Sep 30 09:00:01 netflow systemd[1]: Started Daily apt download activities.', n: 1 },
        { text: 'Sep 30 09:00:04 netflow CRON[2101]: (root) CMD (run-parts /etc/cron.hourly)' },
        { text: 'Sep 30 09:17:42 netflow sshd[2231]: Accepted publickey for user from 192.168.1.20' },
        { text: '/sshd', n: 2 },
        { text: ':', n: 3 },
        { text: 'dmesg | less', run: true, n: 4 },
      ],
      notes: [
        { t: 'The first screen of the file', d: 'less fills the terminal and stops. Nothing more is read until you scroll.' },
        { t: 'Typing / starts a search', d: 'The pattern appears on the bottom line. Enter jumps to the first match and highlights every one; n moves to the next.' },
        { t: 'The colon is the prompt', d: 'It means less is waiting for a key: q to quit, G for the end, g for the start, h for help.' },
        { t: 'Any output can be paged', d: 'Piping a long command into less gives the same scrolling and searching for output that would otherwise fly past.' },
      ],
    },
    recipes: [
      { run: 'less +G app.log', d: 'Opens the file at its end, where the newest log lines are.' },
      { run: 'less -N script.sh', d: 'Shows line numbers down the left.' },
      { run: 'less -S wide.csv', d: 'Does not wrap long lines; scroll sideways with the arrow keys.' },
      { run: 'less +F app.log', d: 'Follows the file as it grows, like tail -f. Ctrl+C returns to normal scrolling.' },
    ],
    security: {
      lede: ['A pager is ', { b: 'a small program with more abilities than it appears to have' }, '.'],
      points: [
        { t: 'A pager can start a shell', d: 'Typing !command inside less runs it. If sudo allows a user to run less as root, that user has a root shell.' },
        { t: 'Safer than cat for unknown files', d: 'less shows control characters as visible symbols instead of sending them to the terminal, so a hostile file cannot rewrite your screen.' },
        { t: 'Reading leaves no trace', d: 'Opening a log in less changes nothing and is not recorded, which is right for an investigation — and worth remembering about anyone else with read access.' },
      ],
    },
    protocols: [],
    related: ['cat', 'tail'],
    footnote: 'The manual pages are shown in less, so the same keys work in "man".',
  },
  {
    slug: 'nano',
    cmd: 'nano',
    group: 'read',
    pkg: 'nano',
    fn: 'A simple text editor that runs in the terminal, with its commands listed on screen.',
    kicker: 'Linux · reading files',
    sub: 'edit a file in the terminal',
    lede: [
      { m: 'nano' },
      ' is the editor to start with. You type and the text appears; ',
      { a: 'the shortcuts are printed along the bottom of the screen' },
      '. On a server with no desktop it is ',
      { b: 'how configuration files get edited' },
      '.',
    ],
    takeaway: [{ a: 'Ctrl+O saves, Ctrl+X exits' }, ' — the caret in the on-screen help means the Ctrl key.'],
    points: [
      { k: 'Save', v: 'Ctrl+O', note: 'then Enter to confirm the name' },
      { k: 'Exit', v: 'Ctrl+X', note: 'asks to save if changed' },
      { k: 'Search', v: 'Ctrl+W', note: 'Alt+W repeats' },
      { k: 'Cut and paste', v: 'Ctrl+K, Ctrl+U', note: 'a line at a time' },
    ],
    session: {
      run: 'nano notes.txt',
      prompt: '$',
      lines: [
        { text: '  GNU nano 7.2                    notes.txt                      Modified', n: 1 },
        { text: '' },
        { text: 'Buy a new switch for the lab' },
        { text: 'Renew the domain before October', n: 2 },
        { text: '' },
        { text: '^G Help     ^O Write Out  ^W Where Is   ^K Cut       ^T Execute', n: 3 },
        { text: '^X Exit     ^R Read File  ^\\ Replace    ^U Paste     ^J Justify' },
        { text: 'sudo nano /etc/hosts', run: true, n: 4 },
      ],
      notes: [
        { t: 'The title bar', d: 'The file being edited, and "Modified" once anything has changed that is not yet saved.' },
        { t: 'The text area', d: 'Type to insert; move with the arrow keys. There are no modes to switch between.' },
        { t: 'The shortcut bar', d: '^ means Ctrl. "Write Out" is nano’s name for save, and "Where Is" for search.' },
        { t: 'System files need root', d: 'Files under /etc belong to root. Without sudo, nano opens the file but cannot save it.' },
      ],
    },
    recipes: [
      { run: 'nano +42 script.sh', d: 'Opens the file with the cursor on line 42.' },
      { run: 'nano -l config.yml', d: 'Shows line numbers.' },
      { run: 'nano -B /etc/fstab', d: 'Keeps a backup of the original, named with a trailing ~.' },
      { run: 'sudoedit /etc/hosts', d: 'The safer way to edit a root-owned file: your editor runs as you, on a copy.' },
    ],
    security: {
      lede: ['Editing a system file is ', { b: 'the moment a typing mistake becomes an outage' }, '.'],
      points: [
        { t: 'Prefer sudoedit to sudo nano', d: 'sudo nano runs the whole editor as root, and an editor can run commands. sudoedit runs it as you and copies the result into place.' },
        { t: 'Use the right tool for sudoers', d: 'Never edit /etc/sudoers with a plain editor. visudo checks the syntax before saving, so a mistake cannot lock you out of sudo.' },
        { t: 'Backup files left behind', d: 'Editors leave copies such as config.php~ or .swp files. In a web root these can be downloaded as plain text, revealing passwords.' },
      ],
    },
    protocols: [],
    related: ['cat', 'less'],
    footnote: 'vim is the other editor found everywhere. To leave it: press Esc, type :q! and press Enter.',
  },
  {
    slug: 'echo',
    cmd: 'echo',
    group: 'read',
    pkg: 'bash',
    fn: 'Prints its arguments — text, or the value of a variable — followed by a new line.',
    kicker: 'Linux · reading files',
    sub: 'print text',
    lede: [
      { m: 'echo' },
      ' writes out whatever follows it. On its own that is trivial; with redirection it ',
      { a: 'creates and appends to files' },
      ', and with a dollar sign it ',
      { b: 'shows what a variable holds' },
      '.',
    ],
    takeaway: ['> replaces a file’s contents; ', { a: '>> adds to the end' }, '. One character apart.'],
    points: [
      { k: 'Prints', v: 'Its arguments', note: 'then a new line' },
      { k: 'Variables', v: '$NAME', note: 'expanded inside double quotes' },
      { k: 'To a file', v: '> and >>', note: 'overwrite and append' },
      { k: 'Built in', v: 'To the shell', note: 'no separate program needed' },
    ],
    session: {
      run: 'echo "Hello, $USER"',
      prompt: '$',
      lines: [
        { text: 'Hello, user', n: 1 },
        { text: "echo 'Hello, $USER'", run: true, n: 2 },
        { text: 'Hello, $USER' },
        { text: 'echo "nameserver 192.0.2.53" > resolv.test', run: true, n: 3 },
        { text: 'echo "nameserver 192.0.2.54" >> resolv.test', run: true, n: 4 },
        { text: 'cat resolv.test', run: true },
        { text: 'nameserver 192.0.2.53' },
        { text: 'nameserver 192.0.2.54' },
      ],
      notes: [
        { t: 'Double quotes expand variables', d: '$USER was replaced by its value before echo ran. The shell does the substituting; echo only prints.' },
        { t: 'Single quotes do not', d: 'Everything inside single quotes is taken literally, dollar sign included.' },
        { t: '> writes to a file', d: 'The output goes to the file instead of the screen. If the file existed, its old contents are gone.' },
        { t: '>> appends', d: 'The second line is added after the first. This is the usual way to add one line to a configuration file.' },
      ],
    },
    recipes: [
      { run: 'echo $PATH', d: 'Shows the value of a variable.' },
      { run: 'echo $?', d: 'Shows the exit status of the last command: 0 means success.' },
      { run: 'echo -e "one\\ttwo\\nthree"', d: 'Interprets \\t as a tab and \\n as a new line.' },
      { run: 'echo "text" | sudo tee -a /etc/hosts', d: 'Appends to a root-owned file — sudo echo with >> does not work.' },
    ],
    security: {
      lede: ['Whatever you echo ', { b: 'is recorded in your shell history' }, '.'],
      points: [
        { t: 'Secrets on the command line', d: 'echo "password" | some-command leaves the password in ~/.bash_history. Read it with "read -s" instead, or from a file.' },
        { t: 'One > can destroy a file', d: 'Typing > where >> was meant replaces the whole file with one line. Keep a copy before appending to anything that matters.' },
        { t: 'sudo does not apply to the redirect', d: 'In "sudo echo x > /etc/file" the shell, running as you, opens the file — and is refused. Pipe to "sudo tee" instead.' },
      ],
    },
    protocols: [],
    related: ['cat', 'tee'],
    footnote: 'printf is the more predictable choice in scripts, because echo’s options differ between shells.',
  },

  // ── text processing ───────────────────────────────────────────────────
  {
    slug: 'wc',
    cmd: 'wc',
    group: 'text',
    pkg: 'coreutils',
    fn: 'Counts the lines, words and bytes in a file or in the output of another command.',
    kicker: 'Linux · text processing',
    sub: 'count lines and words',
    lede: [
      { m: 'wc' },
      ' — word count — prints three numbers: ',
      { a: 'lines, words and bytes' },
      '. It is used most with -l at the end of a pipe, to answer ',
      { b: '"how many?"' },
      ' about anything that prints one item per line.',
    ],
    takeaway: ['Anything that lists one per line can be counted: ', { a: 'command | wc -l' }, '.'],
    points: [
      { k: 'Counts', v: 'Lines, words, bytes', note: 'in that order' },
      { k: 'Lines only', v: '-l', note: 'the one used most' },
      { k: 'In a pipe', v: 'Counts output', note: 'no file name needed' },
      { k: 'Characters', v: '-m', note: 'differs from bytes in UTF-8' },
    ],
    session: {
      run: 'wc app.log',
      prompt: '$',
      lines: [
        { text: '  312  2840 21744 app.log', n: 1 },
        { text: 'wc -l app.log', run: true, n: 2 },
        { text: '312 app.log' },
        { text: 'grep -c "" /etc/passwd; cat /etc/passwd | wc -l', run: true },
        { text: '34' },
        { text: '34', n: 3 },
        { text: 'ls /usr/bin | wc -l', run: true, n: 4 },
        { text: '1487' },
      ],
      notes: [
        { t: 'Three numbers and a name', d: '312 lines, 2840 words, 21744 bytes.' },
        { t: '-l prints only the line count', d: 'The file name follows. Read from a pipe instead, and the name is left off.' },
        { t: 'One line per account', d: '/etc/passwd has a line for each user, so its line count is the number of accounts on the machine.' },
        { t: 'Counting another command’s output', d: 'ls prints one name per line when piped, so wc -l gives the number of commands installed.' },
      ],
    },
    recipes: [
      { run: 'wc -l *.py', d: 'Counts lines in each file and prints a total.' },
      { run: 'grep -r "TODO" src/ | wc -l', d: 'Counts how many lines match across a tree.' },
      { run: 'wc -c < file.bin', d: 'Prints only the size in bytes, with no file name.' },
      { run: 'ps -e --no-headers | wc -l', d: 'Counts the processes running.' },
    ],
    security: {
      lede: ['A count is ', { b: 'the cheapest way to notice that something has changed' }, '.'],
      points: [
        { t: 'Baselines', d: 'The number of accounts, listening ports or scheduled jobs should not change by itself. Counting them regularly makes an addition stand out.' },
        { t: 'Measuring an attack', d: 'Counting failed-login lines in the auth log turns "there seem to be a lot" into a number that can be compared day to day.' },
        { t: 'A count hides the detail', d: 'Thirty-four accounts yesterday and thirty-four today does not mean the same thirty-four. Compare the lists with diff when it matters.' },
      ],
    },
    protocols: [],
    related: ['grep', 'sort'],
    footnote: 'wc -l counts newline characters, so a last line with no newline at its end is not counted.',
  },
  {
    slug: 'sort',
    cmd: 'sort',
    group: 'text',
    pkg: 'coreutils',
    fn: 'Sorts lines of text — alphabetically, numerically, or by a chosen column.',
    kicker: 'Linux · text processing',
    sub: 'put lines in order',
    lede: [
      { m: 'sort' },
      ' reads lines and prints them in order. By default that is alphabetical, which ',
      { a: 'puts 10 before 9' },
      '; -n sorts by number and ',
      { b: '-h understands sizes such as 2K and 1G' },
      '.',
    ],
    takeaway: ['Text order is not number order: ', { a: 'use -n for numbers and -h for sizes' }, '.'],
    points: [
      { k: 'Default', v: 'Alphabetical', note: 'character by character' },
      { k: 'Numbers', v: '-n', note: 'or -h for 2K, 1G' },
      { k: 'By column', v: '-k NUM', note: 'with -t for the separator' },
      { k: 'Reverse', v: '-r', note: 'largest or last first' },
    ],
    session: {
      run: 'sort sizes.txt',
      prompt: '$',
      lines: [
        { text: '10', n: 1 },
        { text: '200' },
        { text: '9' },
        { text: 'sort -n sizes.txt', run: true, n: 2 },
        { text: '9' },
        { text: '10' },
        { text: '200' },
        { text: 'sort -t, -k4 -nr data.csv | head -2', run: true, n: 3 },
        { text: '7,Meera,Engineering,98000' },
        { text: '1,Asha,Engineering,72000' },
      ],
      notes: [
        { t: 'Alphabetical order', d: 'Compared as text, "10" comes before "9" because the character 1 comes before 9.' },
        { t: '-n compares as numbers', d: 'Now 9 is first. This is almost always what is wanted for a column of figures.' },
        { t: 'Sorting by a column', d: '-t, makes the comma the separator and -k4 sorts on the fourth field. -n is numeric and -r reverses: highest salary first.' },
      ],
    },
    recipes: [
      { run: 'du -sh * | sort -h', d: 'Sorts readable sizes correctly, so 900K comes before 2M.' },
      { run: 'sort -u names.txt', d: 'Sorts and removes duplicate lines in one step.' },
      { run: 'sort -k2 file.txt', d: 'Sorts on the second whitespace-separated field.' },
      { run: 'sort access.log | uniq -c | sort -nr | head', d: 'The classic pipeline: the ten most frequent lines.' },
    ],
    security: {
      lede: ['Sorting is ', { b: 'the first step in making sense of a log' }, '.'],
      points: [
        { t: 'Finding the most active address', d: 'Extract the address column from an access log, sort it, count with uniq -c and sort by the count: the top talkers appear first.' },
        { t: 'Sorted lists can be compared', d: 'diff and comm need sorted input. Sorting two lists of users or packages is what makes comparing them possible.' },
        { t: 'Locale changes the order', d: 'Sorting rules depend on the language setting, so two machines can sort the same file differently. LC_ALL=C sort gives a fixed byte order.' },
      ],
    },
    protocols: [],
    related: ['uniq', 'wc'],
    footnote: 'sort handles files larger than memory by using temporary files, so it is safe on very large logs.',
  },
  {
    slug: 'uniq',
    cmd: 'uniq',
    group: 'text',
    pkg: 'coreutils',
    fn: 'Collapses repeated neighbouring lines into one, optionally counting how many there were.',
    kicker: 'Linux · text processing',
    sub: 'remove or count repeats',
    lede: [
      { m: 'uniq' },
      ' removes duplicate lines — but ',
      { a: 'only when the duplicates are next to each other' },
      '. That is why it is always fed from sort. With -c it ',
      { b: 'counts how often each line occurred' },
      '.',
    ],
    takeaway: [{ a: 'sort | uniq -c | sort -nr' }, ' turns any list into a ranking of what occurs most.'],
    points: [
      { k: 'Removes', v: 'Adjacent repeats', note: 'not repeats further apart' },
      { k: 'So first', v: 'sort', note: 'to bring duplicates together' },
      { k: 'Count', v: '-c', note: 'occurrences, before each line' },
      { k: 'Only repeats', v: '-d', note: '-u for lines that occur once' },
    ],
    session: {
      run: 'uniq visitors.txt',
      prompt: '$',
      lines: [
        { text: '192.0.2.7' },
        { text: '198.51.100.3' },
        { text: '192.0.2.7', n: 1 },
        { text: 'sort visitors.txt | uniq -c', run: true, n: 2 },
        { text: '      3 192.0.2.7' },
        { text: '      1 198.51.100.3' },
        { text: 'sort visitors.txt | uniq -c | sort -nr | head -1', run: true, n: 3 },
        { text: '      3 192.0.2.7' },
      ],
      notes: [
        { t: 'The repeat was not removed', d: '192.0.2.7 appears twice in the output because, in the file, another line sat between its occurrences.' },
        { t: 'Sorted first, then counted', d: 'sort puts identical lines together; uniq -c then collapses each run and prints how many it replaced.' },
        { t: 'Ranked by the count', d: 'A second sort, numeric and reversed, orders by the number in front. head keeps the top one: the most frequent visitor.' },
      ],
    },
    recipes: [
      { run: 'sort file.txt | uniq -d', d: 'Prints only the lines that occur more than once.' },
      { run: 'sort file.txt | uniq -u', d: 'Prints only the lines that occur exactly once.' },
      { run: 'sort file.txt | uniq -i', d: 'Treats upper and lower case as the same.' },
      { run: 'cut -d" " -f1 access.log | sort | uniq -c | sort -nr | head', d: 'The ten addresses making the most requests to a web server.' },
    ],
    security: {
      lede: ['Counting repeats is ', { b: 'how a pattern is pulled out of a noisy log' }, '.'],
      points: [
        { t: 'Who is guessing passwords', d: 'Failed-login lines reduced to source addresses, then sort | uniq -c | sort -nr, lists the attackers by number of attempts.' },
        { t: 'Rare is interesting too', d: 'The lines that occur once — uniq -u — are often the unusual event: a single request to an odd path, a process seen on one host only.' },
        { t: 'Forgetting sort gives wrong numbers', d: 'Without sorting, the same value is counted in several separate runs and the totals are meaningless.' },
      ],
    },
    protocols: [],
    related: ['sort', 'cut'],
    footnote: '"sort -u" does the same as "sort | uniq" when no count is needed.',
  },
  {
    slug: 'cut',
    cmd: 'cut',
    group: 'text',
    pkg: 'coreutils',
    fn: 'Extracts chosen columns from each line, by separator or by character position.',
    kicker: 'Linux · text processing',
    sub: 'pick out columns',
    lede: [
      { m: 'cut' },
      ' keeps part of every line and discards the rest. Tell it ',
      { a: 'the separator with -d and the fields wanted with -f' },
      ', and a file with columns is reduced to ',
      { b: 'just the ones you asked for' },
      '.',
    ],
    takeaway: ['-d names the separator, ', { a: '-f names the fields' }, '. Fields count from 1.'],
    points: [
      { k: 'Selects', v: 'Columns', note: 'from every line' },
      { k: 'Separator', v: '-d CHAR', note: 'a tab unless given' },
      { k: 'Fields', v: '-f 1,3 or -f 2-4', note: 'a list or a range' },
      { k: 'Characters', v: '-c 1-10', note: 'by position instead' },
    ],
    session: {
      run: 'cut -d: -f1 /etc/passwd | head -3',
      prompt: '$',
      lines: [
        { text: 'root', n: 1 },
        { text: 'daemon' },
        { text: 'bin' },
        { text: 'cut -d: -f1,7 /etc/passwd | tail -1', run: true, n: 2 },
        { text: 'user:/bin/bash' },
        { text: 'cut -d, -f2-3 data.csv | head -2', run: true, n: 3 },
        { text: 'name,department' },
        { text: 'Asha,Engineering' },
      ],
      notes: [
        { t: 'The first field of each line', d: '/etc/passwd separates its fields with colons, and the first is the account name. This lists every user.' },
        { t: 'Two fields, kept with their separator', d: 'Fields 1 and 7: the name and the login shell. The colon between them is preserved in the output.' },
        { t: 'A range of fields', d: '2-3 means the second to the third. With -d, the same works on a CSV file.' },
      ],
    },
    recipes: [
      { run: 'cut -c 1-80 long.txt', d: 'Keeps the first 80 characters of each line.' },
      { run: 'cut -d" " -f1 access.log', d: 'Takes the first space-separated field: the client address.' },
      { run: 'cut -f2 data.tsv', d: 'With no -d, fields are separated by tabs.' },
      { run: 'echo $PATH | cut -d: -f1', d: 'Shows the first directory in PATH.' },
    ],
    security: {
      lede: ['Reducing a log to one column is ', { b: 'what makes it countable' }, '.'],
      points: [
        { t: 'Listing who can log in', d: 'cut -d: -f1,7 /etc/passwd shows each account with its shell. Accounts with a real shell that should not have one are worth questioning.' },
        { t: 'Extracting addresses and users', d: 'Most log analysis begins by cutting out the field of interest — address, user, URL — and handing it to sort and uniq.' },
        { t: 'It splits on one character only', d: 'cut cannot handle repeated spaces or quoted commas, and will quietly take the wrong column. Use awk for those.' },
      ],
    },
    protocols: [],
    related: ['awk', 'sort'],
    footnote: 'For columns separated by runs of spaces, as in the output of ps or ls -l, awk is the right tool.',
  },
  {
    slug: 'sed',
    cmd: 'sed',
    group: 'text',
    pkg: 'sed',
    fn: 'Edits text as it streams past: replaces, deletes or prints lines that match a pattern.',
    kicker: 'Linux · text processing',
    sub: 'find and replace, without an editor',
    lede: [
      { m: 'sed' },
      ' — stream editor — applies an editing command to every line of its input. Its ',
      { a: 'substitute command, s/old/new/, is find-and-replace from the command line' },
      ', and with -i it ',
      { b: 'changes the file itself' },
      '.',
    ],
    takeaway: [{ a: 's/old/new/g' }, ' — substitute, the pattern, the replacement, and g for every occurrence on the line.'],
    points: [
      { k: 'Replace', v: 's/old/new/g', note: 'g means all on the line' },
      { k: 'By default', v: 'Prints, changes nothing', note: 'the file is untouched' },
      { k: 'Edit the file', v: '-i', note: 'in place' },
      { k: 'Delete lines', v: '/pattern/d', note: 'or by number: 5d' },
    ],
    session: {
      run: "sed 's/http:/https:/g' links.txt",
      prompt: '$',
      lines: [
        { text: 'https://example.com/a', n: 1 },
        { text: 'https://example.com/b' },
        { text: "sed -n '2p' links.txt", run: true, n: 2 },
        { text: 'http://example.com/b' },
        { text: "sed -i.bak 's/^#Port 22/Port 2222/' sshd_config", run: true, n: 3 },
        { text: "sed '/^#/d;/^$/d' sshd_config | head -2", run: true, n: 4 },
        { text: 'Port 2222' },
        { text: 'PermitRootLogin no' },
      ],
      notes: [
        { t: 'Every match replaced, in the output', d: 'The result is printed. links.txt on disk still says http: — nothing was written.' },
        { t: 'Printing one line', d: '-n stops sed printing everything, and 2p prints line 2 only. It shows the file is unchanged.' },
        { t: '-i edits in place, .bak keeps a copy', d: 'The file is rewritten, and the original is saved as sshd_config.bak. ^ anchors the pattern to the start of the line.' },
        { t: 'Deleting lines', d: 'Two commands separated by a semicolon: delete lines starting with #, and delete empty lines. What is left is the active configuration.' },
      ],
    },
    recipes: [
      { run: "sed -n '10,20p' file.txt", d: 'Prints lines 10 to 20 only.' },
      { run: "sed 's/ *$//' file.txt", d: 'Removes trailing spaces from every line.' },
      { run: "sed -i 's/\\r$//' script.sh", d: 'Removes Windows line endings from a script.' },
      { run: "sed 's|/var/www|/srv/www|g' config", d: 'Uses | as the delimiter, so paths need no escaping.' },
    ],
    security: {
      lede: ['sed -i ', { b: 'rewrites a file with no confirmation and no undo' }, '.'],
      points: [
        { t: 'Always keep a backup suffix', d: '-i.bak costs nothing and saves the original. Run the command without -i first to see the result.' },
        { t: 'A pattern can match more than you meant', d: 'A dot matches any character and unanchored text matches anywhere in a line. Anchor with ^ and $, and escape the dots.' },
        { t: 'Changing configuration in bulk', d: 'sed is how hardening scripts flip settings across many files. Check the result with grep afterwards — a pattern that matched nothing fails silently.' },
      ],
    },
    protocols: [],
    related: ['awk', 'grep'],
    footnote: 'This describes GNU sed. On macOS and BSD, -i needs an argument, written as -i "" for no backup.',
  },
  {
    slug: 'awk',
    cmd: 'awk',
    group: 'text',
    pkg: 'gawk',
    fn: 'Processes text column by column: prints, filters and totals fields from each line.',
    kicker: 'Linux · text processing',
    sub: 'work with columns',
    lede: [
      { m: 'awk' },
      ' splits every line into fields and lets you ',
      { a: 'refer to them as $1, $2, $3' },
      '. It handles ',
      { b: 'any amount of space between columns' },
      ', which is why it is the tool for the output of ps, df and ls -l.',
    ],
    takeaway: [{ a: "awk '{print $1}'" }, ' prints the first column of anything, however it is spaced.'],
    points: [
      { k: 'Fields', v: '$1, $2 … $NF', note: '$0 is the whole line' },
      { k: 'Separator', v: 'Whitespace', note: 'or -F to choose one' },
      { k: 'Filter', v: 'condition {action}', note: 'the action runs on matching lines' },
      { k: 'Arithmetic', v: 'Built in', note: 'sums and averages' },
    ],
    session: {
      run: "df -h | awk '{print $5, $6}'",
      prompt: '$',
      lines: [
        { text: 'Use% Mounted', n: 1 },
        { text: '44% /' },
        { text: '95% /home' },
        { text: "awk -F: '$3 >= 1000 {print $1}' /etc/passwd", run: true, n: 2 },
        { text: 'user' },
        { text: 'deploy' },
        { text: "awk -F, 'NR>1 {sum += $4} END {print sum}' data.csv", run: true, n: 3 },
        { text: '6410000' },
      ],
      notes: [
        { t: 'Two columns out of six', d: 'The fifth and sixth fields of each line of df. The uneven spacing between columns does not matter to awk.' },
        { t: 'A condition before the action', d: '-F: splits on colons. Only lines whose third field, the user id, is 1000 or more are printed — the human accounts.' },
        { t: 'Adding up a column', d: 'NR>1 skips the header line. sum grows with each row’s fourth field, and END prints it once the input is finished.' },
      ],
    },
    recipes: [
      { run: "ps aux | awk '$3 > 50 {print $2, $11}'", d: 'Prints the id and command of processes using more than 50% CPU.' },
      { run: "awk '{print $NF}' file.txt", d: 'Prints the last field of each line, however many there are.' },
      { run: "awk 'NR==5' file.txt", d: 'Prints line 5 only.' },
      { run: "awk '{print $1}' access.log | sort | uniq -c | sort -nr | head", d: 'The ten busiest client addresses in a web log.' },
    ],
    security: {
      lede: ['awk is ', { b: 'how a log line becomes data you can add up' }, '.'],
      points: [
        { t: 'Totals and thresholds', d: 'Summing bytes sent per address, or printing only requests that returned 500, takes one line of awk and often answers the question on the spot.' },
        { t: 'Accounts with user id 0', d: "awk -F: '$3 == 0' /etc/passwd lists every account with root's id. There should be exactly one." },
        { t: 'Quote the program', d: 'The awk program belongs in single quotes. In double quotes the shell replaces $1 with its own value before awk runs.' },
      ],
    },
    protocols: [],
    related: ['cut', 'sed'],
    footnote: 'awk is a small programming language; these one-liners are the part used every day.',
  },
  {
    slug: 'diff',
    cmd: 'diff',
    group: 'text',
    pkg: 'diffutils',
    fn: 'Compares two files line by line and prints the lines that differ.',
    kicker: 'Linux · text processing',
    sub: 'what changed between two files',
    lede: [
      { m: 'diff' },
      ' reports the differences between two files. ',
      { a: 'If they are identical it prints nothing' },
      '; otherwise it shows ',
      { b: 'which lines to remove and which to add' },
      ' to turn the first into the second.',
    ],
    takeaway: ['Lines starting ', { b: '-' }, ' are only in the old file; lines starting ', { a: '+' }, ' are only in the new.'],
    points: [
      { k: 'Compares', v: 'Two files', note: 'or two directories with -r' },
      { k: 'Identical', v: 'No output', note: 'exit status 0' },
      { k: 'Readable form', v: '-u', note: 'unified, with context' },
      { k: 'Result', v: 'A patch', note: 'that patch can apply' },
    ],
    session: {
      run: 'diff -u sshd_config.bak sshd_config',
      prompt: '$',
      lines: [
        { text: '--- sshd_config.bak 2026-09-29 17:03:11.000000000 +0530', n: 1 },
        { text: '+++ sshd_config     2026-09-30 10:41:03.000000000 +0530' },
        { text: '@@ -12,7 +12,7 @@', n: 2 },
        { text: ' Include /etc/ssh/sshd_config.d/*.conf' },
        { text: '-#Port 22', n: 3 },
        { text: '+Port 2222' },
        { text: ' #AddressFamily any' },
        { text: 'diff -q a.conf b.conf', run: true, n: 4 },
        { text: 'Files a.conf and b.conf differ' },
      ],
      notes: [
        { t: 'The two files', d: '--- is the old file and +++ the new, each with its modification time.' },
        { t: 'Where the change is', d: 'The hunk header: seven lines starting at line 12 in each file.' },
        { t: 'The change itself', d: 'The line with - was removed and the line with + was added. Lines starting with a space are unchanged context.' },
        { t: '-q only says whether they differ', d: 'No detail — useful in a script, or when comparing many files.' },
      ],
    },
    recipes: [
      { run: 'diff -r dir1 dir2', d: 'Compares two directory trees, file by file.' },
      { run: 'diff -y a.txt b.txt', d: 'Shows the two files side by side.' },
      { run: 'diff <(ssh host1 cat /etc/hosts) <(ssh host2 cat /etc/hosts)', d: 'Compares a file on two machines.' },
      { run: 'diff -u old new > change.patch', d: 'Saves the differences as a patch file.' },
    ],
    security: {
      lede: ['Knowing exactly what changed is ', { b: 'the core of both review and investigation' }, '.'],
      points: [
        { t: 'Review before applying', d: 'After editing a configuration file, diff it against the backup. An unexpected changed line is caught before the service is restarted.' },
        { t: 'Spotting tampering', d: 'Comparing a file with a known-good copy from a backup or the package shows precisely what an intruder altered.' },
        { t: 'Comparing lists over time', d: "Save the list of users, listening ports or cron jobs each day and diff today's against yesterday's: additions stand out." },
      ],
    },
    protocols: [],
    related: ['cat', 'sort'],
    footnote: '"git diff" uses the same unified format; reading one teaches you the other.',
  },
  {
    slug: 'tee',
    cmd: 'tee',
    group: 'text',
    pkg: 'coreutils',
    fn: 'Copies its input both to a file and to the screen, so output can be saved and watched at once.',
    kicker: 'Linux · text processing',
    sub: 'save and show at once',
    lede: [
      { m: 'tee' },
      ' sits in a pipe and ',
      { a: 'sends what passes through to two places: a file, and onward' },
      '. Named after a T-shaped pipe joint, it is also ',
      { b: 'the standard way to write to a root-owned file from a pipe' },
      '.',
    ],
    takeaway: ['A redirect sends output to a file ', { b: 'instead of' }, ' the screen; tee sends it to ', { a: 'both' }, '.'],
    points: [
      { k: 'Writes to', v: 'A file and the screen', note: 'both at once' },
      { k: 'Append', v: '-a', note: 'otherwise the file is replaced' },
      { k: 'With sudo', v: '| sudo tee file', note: 'for files you cannot write' },
      { k: 'Several files', v: 'tee a b c', note: 'each gets a copy' },
    ],
    session: {
      run: 'ping -c 2 192.0.2.1 | tee ping.log',
      prompt: '$',
      lines: [
        { text: 'PING 192.0.2.1 (192.0.2.1) 56(84) bytes of data.', n: 1 },
        { text: '64 bytes from 192.0.2.1: icmp_seq=1 ttl=64 time=0.412 ms' },
        { text: '64 bytes from 192.0.2.1: icmp_seq=2 ttl=64 time=0.398 ms' },
        { text: 'wc -l ping.log', run: true, n: 2 },
        { text: '3 ping.log' },
        { text: 'echo "192.168.1.20 fileserver" | sudo tee -a /etc/hosts', run: true, n: 3 },
        { text: '192.168.1.20 fileserver' },
      ],
      notes: [
        { t: 'The output appears as usual', d: 'tee passes everything through to the screen, so the command can be watched while it runs.' },
        { t: 'And it was saved', d: 'The same three lines are in ping.log.' },
        { t: 'Appending to a root-owned file', d: 'tee runs under sudo, so it may open /etc/hosts. -a appends instead of replacing. The line is echoed back because tee also prints.' },
      ],
    },
    recipes: [
      { run: 'make 2>&1 | tee build.log', d: 'Saves both normal output and errors while showing them.' },
      { run: 'command | tee -a history.log', d: 'Appends to a log instead of overwriting it.' },
      { run: 'echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward', d: 'Writes a kernel setting that needs root.' },
      { run: 'command | sudo tee file > /dev/null', d: 'Writes the file without echoing the content to the screen.' },
    ],
    security: {
      lede: ['tee is how ', { b: 'a record is kept of what a command actually printed' }, '.'],
      points: [
        { t: 'Keeping evidence', d: 'During an investigation or an authorised test, piping commands through tee keeps a dated record of exactly what was seen.' },
        { t: 'Forgetting -a overwrites', d: 'sudo tee /etc/hosts without -a replaces the whole file with one line. Check for the -a every time.' },
        { t: 'Saved output may contain secrets', d: 'A log made with tee holds whatever the command printed, tokens and passwords included. Give it tight permissions.' },
      ],
    },
    protocols: [],
    related: ['echo', 'cat'],
    footnote: '2>&1 before the pipe sends error messages through tee as well; without it they go only to the screen.',
  },
  {
    slug: 'xargs',
    cmd: 'xargs',
    group: 'text',
    pkg: 'findutils',
    fn: 'Takes a list from standard input and runs a command with those items as its arguments.',
    kicker: 'Linux · text processing',
    sub: 'turn a list into arguments',
    lede: [
      { m: 'xargs' },
      ' bridges two kinds of command: ones that ',
      { a: 'print a list' },
      ', and ones that ',
      { b: 'want their input as arguments, not on a pipe' },
      ' — rm, cp, chmod. It reads the list and builds the command line.',
    ],
    takeaway: ['find produces names; ', { a: 'xargs hands them to the command that acts on them' }, '.'],
    points: [
      { k: 'Reads', v: 'A list', note: 'separated by spaces or new lines' },
      { k: 'Runs', v: 'One command', note: 'with many arguments at once' },
      { k: 'One at a time', v: '-n 1 or -I {}', note: 'when the command needs it' },
      { k: 'Safe with spaces', v: '-0', note: 'paired with find -print0' },
    ],
    session: {
      run: 'find . -name "*.tmp" | xargs rm -v',
      prompt: '$',
      lines: [
        { text: "removed './cache/a.tmp'", n: 1 },
        { text: "removed './cache/b.tmp'" },
        { text: 'echo "one two three" | xargs -n 1 echo item:', run: true, n: 2 },
        { text: 'item: one' },
        { text: 'item: two' },
        { text: 'item: three' },
        { text: 'find . -name "*.log" -print0 | xargs -0 gzip', run: true, n: 3 },
        { text: 'cat hosts.txt | xargs -I {} ping -c 1 {}', run: true, n: 4 },
      ],
      notes: [
        { t: 'One rm, many files', d: 'find printed the names, and xargs ran a single "rm -v ./cache/a.tmp ./cache/b.tmp".' },
        { t: '-n 1 runs the command per item', d: 'Three separate echo commands, each given one word.' },
        { t: 'Handling awkward file names', d: '-print0 and -0 separate names with a null byte instead of a new line, so names with spaces are passed correctly.' },
        { t: '-I {} places the item', d: 'Each line of hosts.txt is put where {} appears, and ping runs once per host.' },
      ],
    },
    recipes: [
      { run: 'grep -rl "old-domain" . | xargs sed -i "s/old-domain/new-domain/g"', d: 'Replaces text in every file that contains it.' },
      { run: 'cat urls.txt | xargs -n 1 -P 4 curl -sO', d: 'Downloads four at a time, in parallel.' },
      { run: 'find . -type f | xargs -p rm', d: 'Shows the command and asks before running it.' },
      { run: 'ls *.jpg | xargs -I {} mv {} photos/', d: 'Moves each file into a directory.' },
    ],
    security: {
      lede: ['xargs runs commands ', { b: 'built from data it was handed' }, ', so the data matters.'],
      points: [
        { t: 'File names with spaces', d: 'Without -0, a file called "my notes.txt" becomes two arguments, and rm may delete a different file called "my". Use -print0 with -0.' },
        { t: 'Names chosen by someone else', d: 'A file named "-rf" is read as a switch by the command. Put -- before the arguments so nothing after it is treated as an option.' },
        { t: 'Rehearse destructive pipelines', d: 'Replace rm with echo, or use -p, to see the command that would run before letting it loose.' },
      ],
    },
    protocols: [],
    related: ['find', 'grep'],
    footnote: 'find has its own "-exec command {} +" which does the same job without a pipe.',
  },
];

export const switches: Record<string, LinuxSwitch[]> = {
  head: [
    { flag: '-n NUM', d: 'Print the first NUM lines instead of 10.' },
    { flag: '-n -NUM', d: 'Print everything except the last NUM lines.' },
    { flag: '-c NUM', d: 'Print the first NUM bytes.' },
    { flag: '-q', d: 'Do not print a header with the file name when given several files.' },
  ],
  less: [
    { flag: '-N', d: 'Show line numbers.' },
    { flag: '-S', d: 'Do not wrap long lines; scroll sideways instead.' },
    { flag: '-i', d: 'Ignore case when searching, unless the pattern has capitals.' },
    { flag: '-R', d: 'Show colours from commands that produce them.' },
    { flag: '+G', d: 'Start at the end of the file.' },
    { flag: '+F', d: 'Follow the file as it grows, like tail -f.' },
  ],
  nano: [
    { flag: '-l', d: 'Show line numbers.' },
    { flag: '+NUM', d: 'Open with the cursor on line NUM.' },
    { flag: '-B', d: 'Keep a backup of the original file, with a ~ suffix.' },
    { flag: '-v', d: 'View only: open the file read-only.' },
    { flag: '-m', d: 'Enable the mouse for placing the cursor.' },
  ],
  echo: [
    { flag: '-n', d: 'Do not add a new line at the end.' },
    { flag: '-e', d: 'Interpret escapes such as \\n for a new line and \\t for a tab.' },
    { flag: '-E', d: 'Do not interpret escapes. This is the default in bash.' },
  ],
  wc: [
    { flag: '-l', d: 'Count lines only.' },
    { flag: '-w', d: 'Count words only.' },
    { flag: '-c', d: 'Count bytes only.' },
    { flag: '-m', d: 'Count characters, which differs from bytes for non-ASCII text.' },
    { flag: '-L', d: 'Print the length of the longest line.' },
  ],
  sort: [
    { flag: '-n', d: 'Numeric: compare as numbers.' },
    { flag: '-h', d: 'Human-numeric: understand sizes such as 2K and 1G.' },
    { flag: '-r', d: 'Reverse the order.' },
    { flag: '-u', d: 'Unique: drop duplicate lines.' },
    { flag: '-k NUM', d: 'Sort by field number NUM.' },
    { flag: '-t CHAR', d: 'Use this character as the field separator.' },
    { flag: '-f', d: 'Fold case: treat upper and lower case alike.' },
  ],
  uniq: [
    { flag: '-c', d: 'Count: prefix each line with the number of times it occurred.' },
    { flag: '-d', d: 'Print only lines that are repeated.' },
    { flag: '-u', d: 'Print only lines that are not repeated.' },
    { flag: '-i', d: 'Ignore case when comparing.' },
  ],
  cut: [
    { flag: '-d CHAR', d: 'Use this character as the field separator instead of a tab.' },
    { flag: '-f LIST', d: 'Select these fields: 1,3 or 2-4 or 3-.' },
    { flag: '-c LIST', d: 'Select these character positions.' },
    { flag: '-s', d: 'Skip lines that do not contain the separator.' },
    { flag: '--complement', d: 'Print everything except the selected fields.' },
  ],
  sed: [
    { flag: '-i', d: 'Edit the file in place. -i.bak also keeps a backup.' },
    { flag: '-n', d: 'Do not print each line automatically; print only what p asks for.' },
    { flag: '-e SCRIPT', d: 'Add another editing command.' },
    { flag: '-E', d: 'Use extended regular expressions.' },
    { flag: '-f FILE', d: 'Read the editing commands from a file.' },
  ],
  awk: [
    { flag: '-F SEP', d: 'Use this as the field separator instead of whitespace.' },
    { flag: '-v NAME=VALUE', d: 'Set a variable before the program runs.' },
    { flag: '-f FILE', d: 'Read the awk program from a file.' },
  ],
  diff: [
    { flag: '-u', d: 'Unified format, with lines of context. The readable one.' },
    { flag: '-r', d: 'Recursive: compare directories and everything in them.' },
    { flag: '-q', d: 'Brief: report only whether the files differ.' },
    { flag: '-y', d: 'Side by side, in two columns.' },
    { flag: '-i', d: 'Ignore differences in case.' },
    { flag: '-w', d: 'Ignore all differences in spacing.' },
  ],
  tee: [
    { flag: '-a', d: 'Append to the file instead of overwriting it.' },
    { flag: '-i', d: 'Ignore interrupt signals, so Ctrl+C does not stop tee before the command.' },
  ],
  xargs: [
    { flag: '-n NUM', d: 'Use at most NUM arguments per command.' },
    { flag: '-I {}', d: 'Replace {} in the command with each input item.' },
    { flag: '-0', d: 'Expect items separated by null bytes, as from find -print0.' },
    { flag: '-P NUM', d: 'Run up to NUM commands in parallel.' },
    { flag: '-p', d: 'Prompt: show each command and ask before running it.' },
    { flag: '-r', d: 'Do not run the command at all if there is no input.' },
  ],
};
