import type { LinuxCommand } from '../linux-data';
import type { LinuxSwitch } from '../linux-switches';

/* Accounts and groups: finding out who you are, becoming someone else, and
   creating, changing and removing users. */

export const commands: LinuxCommand[] = [
  {
    slug: 'whoami',
    cmd: 'whoami',
    group: 'perm',
    pkg: 'coreutils',
    fn: 'Prints the user name you are currently acting as.',
    kicker: 'Linux · users & permissions',
    sub: 'which user am I',
    lede: [
      { m: 'whoami' },
      ' prints one word: the account the shell is running as. It matters ',
      { a: 'after su or sudo, when that may no longer be the account you logged in with' },
      ' — and ',
      { b: 'before any command that would be dangerous as root' },
      '.',
    ],
    takeaway: ['One word, and worth checking: ', { a: 'are you root right now, or yourself?' }],
    points: [
      { k: 'Prints', v: 'The effective user', note: 'who the system treats you as' },
      { k: 'After sudo', v: 'root', note: 'for that one command' },
      { k: 'More detail', v: 'id', note: 'ids and groups too' },
      { k: 'Who logged in', v: 'who am i', note: 'the original account' },
    ],
    session: {
      run: 'whoami',
      prompt: '$',
      lines: [
        { text: 'user', n: 1 },
        { text: 'sudo whoami', run: true, n: 2 },
        { text: 'root' },
        { text: 'sudo -u www-data whoami', run: true, n: 3 },
        { text: 'www-data' },
      ],
      notes: [
        { t: 'Your own account', d: 'The name the shell is running under — the same one in the prompt.' },
        { t: 'Under sudo, you are root', d: 'The command ran as root, so that is what it reports. It is a quick way to confirm that sudo works for you.' },
        { t: 'Or any other user', d: 'sudo -u runs a command as a named account. Running whoami this way tests whether you are allowed to.' },
      ],
    },
    recipes: [
      { run: 'id', d: 'Shows the user id, group id and every group you belong to.' },
      { run: 'who', d: 'Lists everyone logged in to the machine.' },
      { run: 'echo $USER', d: 'The same name, from an environment variable.' },
      { run: 'logname', d: 'The name you originally logged in as, even after su.' },
    ],
    security: {
      lede: ['It is ', { b: 'the first command run on any newly gained shell' }, '.'],
      points: [
        { t: 'What an intruder asks first', d: 'After exploiting a service, whoami shows which account was obtained. www-data means there is more work to do; root means there is not.' },
        { t: 'Know when you are root', d: 'A root prompt usually ends in # rather than $. If in doubt, ask — before running rm or chown, not after.' },
        { t: 'Services should not be root', d: 'A web application that reports root when it runs whoami is running with far more power than it needs.' },
      ],
    },
    protocols: [],
    related: ['id', 'sudo'],
    footnote: 'whoami prints the effective user; after "su" this differs from the login name that logname reports.',
  },
  {
    slug: 'id',
    cmd: 'id',
    group: 'perm',
    pkg: 'coreutils',
    fn: 'Prints a user’s numeric id, primary group, and every group they belong to.',
    kicker: 'Linux · users & permissions',
    sub: 'ids and group membership',
    lede: [
      { m: 'id' },
      ' shows who a user is as the kernel sees them: ',
      { a: 'a user id, a group id, and a list of groups' },
      '. Permissions are decided by these numbers, so ',
      { b: 'when access is denied, this is where to look' },
      '.',
    ],
    takeaway: ['"Permission denied" on a group-readable file? ', { a: 'id tells you whether you are in the group' }, '.'],
    points: [
      { k: 'uid', v: 'User id', note: '0 is root; people start at 1000' },
      { k: 'gid', v: 'Primary group', note: 'given to files you create' },
      { k: 'groups', v: 'All memberships', note: 'each grants access' },
      { k: 'Another user', v: 'id NAME', note: 'no root needed' },
    ],
    session: {
      run: 'id',
      prompt: '$',
      lines: [
        { text: 'uid=1000(user) gid=1000(user) groups=1000(user),27(sudo),998(docker)', n: 1 },
        { text: 'id www-data', run: true, n: 2 },
        { text: 'uid=33(www-data) gid=33(www-data) groups=33(www-data)' },
        { text: 'id -u root', run: true, n: 3 },
        { text: '0' },
        { text: 'id -nG', run: true, n: 4 },
        { text: 'user sudo docker' },
      ],
      notes: [
        { t: 'Your identity, in full', d: 'User id 1000, primary group 1000, and membership of sudo and docker. Each number is shown with its name.' },
        { t: 'A service account', d: 'The web server’s account has a low id and belongs only to its own group — as little access as possible.' },
        { t: 'root is user id 0', d: 'The kernel grants root’s powers to id 0, whatever the account is called.' },
        { t: 'Group names only', d: '-n prints names instead of numbers and -G lists all groups: a compact answer to "what groups am I in?"' },
      ],
    },
    recipes: [
      { run: 'groups', d: 'Lists your group names — the same as id -nG.' },
      { run: 'getent passwd user', d: 'Shows a user’s account record: id, home directory and shell.' },
      { run: 'getent group docker', d: 'Lists the members of a group.' },
      { run: 'newgrp docker', d: 'Starts a shell with a newly added group active, without logging out.' },
    ],
    security: {
      lede: ['Group membership is ', { b: 'where privilege hides in plain sight' }, '.'],
      points: [
        { t: 'Groups that amount to root', d: 'Members of sudo or wheel can become root. Members of docker, disk or lxd can too, by less obvious routes. Review who is in them.' },
        { t: 'More than one uid 0', d: 'A second account with user id 0 is a second root, whatever its name. There should be exactly one.' },
        { t: 'Changes need a new login', d: 'Adding a user to a group does not affect sessions already open — and removing them does not either, until those sessions end.' },
      ],
    },
    protocols: [],
    related: ['whoami', 'usermod'],
    footnote: 'The numbers come from /etc/passwd and /etc/group, or from a directory service such as LDAP.',
  },
  {
    slug: 'su',
    cmd: 'su',
    group: 'perm',
    pkg: 'util-linux',
    fn: 'Switches to another user account in the current terminal, after asking for that user’s password.',
    kicker: 'Linux · users & permissions',
    sub: 'become another user',
    lede: [
      { m: 'su' },
      ' — substitute user — starts a shell as someone else. With no name it means root. ',
      { a: 'It asks for the target account’s password, not yours' },
      ', which is the main way it ',
      { b: 'differs from sudo' },
      '.',
    ],
    takeaway: ['su asks for ', { b: 'their' }, ' password; sudo asks for ', { a: 'yours' }, '.'],
    points: [
      { k: 'Default target', v: 'root', note: 'when no name is given' },
      { k: 'Password asked', v: 'The target’s', note: 'unless you are root' },
      { k: 'Full login', v: 'su -', note: 'their environment and home' },
      { k: 'Return', v: 'exit', note: 'back to your own shell' },
    ],
    session: {
      run: 'su - deploy',
      prompt: '$',
      lines: [
        { text: 'Password: ', n: 1 },
        { text: 'whoami', run: true, n: 2 },
        { text: 'deploy' },
        { text: 'pwd', run: true, n: 3 },
        { text: '/home/deploy' },
        { text: 'exit', run: true, n: 4 },
        { text: 'logout' },
      ],
      notes: [
        { t: 'The other account’s password', d: 'Nothing is shown as you type. You must know deploy’s password — yours will not do.' },
        { t: 'You are now deploy', d: 'Every command from here runs with that account’s permissions.' },
        { t: 'The dash gave a full login', d: 'With "su -" you land in the target’s home directory with their environment. Without it you keep your own directory and variables.' },
        { t: 'exit returns you', d: 'The substitute shell ends and you are back in your own, as yourself.' },
      ],
    },
    recipes: [
      { run: 'su -', d: 'Becomes root with a full login environment.' },
      { run: 'su -c "systemctl restart nginx"', d: 'Runs one command as root and returns.' },
      { run: 'sudo su - postgres', d: 'Becomes a service account using your own sudo rights.' },
      { run: 'sudo -i', d: 'A root login shell through sudo — no root password needed.' },
    ],
    security: {
      lede: ['su works by ', { b: 'sharing a password between everyone who needs the account' }, '.'],
      points: [
        { t: 'Prefer sudo', d: 'With su, every administrator knows the root password and the log shows only "root". With sudo each person uses their own password and each command is logged against their name.' },
        { t: 'Use the dash', d: 'Plain "su" keeps your PATH and environment. A PATH containing a directory you can write to, carried into a root shell, is a known way to be tricked.' },
        { t: 'Attempts are logged', d: 'Failed and successful su attempts are written to the auth log. Repeated failures against root are worth an alert.' },
      ],
    },
    protocols: [],
    related: ['sudo', 'whoami'],
    footnote: 'Ubuntu locks the root password by default, so "su -" to root fails there until one is set; sudo is used instead.',
  },
  {
    slug: 'passwd',
    cmd: 'passwd',
    group: 'perm',
    pkg: 'passwd',
    fn: 'Changes a password — your own, or as root anyone’s — and locks or unlocks accounts.',
    kicker: 'Linux · users & permissions',
    sub: 'change a password',
    lede: [
      { m: 'passwd' },
      ' sets a new password. Run as yourself it ',
      { a: 'asks for the current one first, then the new one twice' },
      '. Run as root it ',
      { b: 'can set any account’s password, and lock an account so it cannot log in' },
      '.',
    ],
    takeaway: ['Nothing appears as you type a password. ', { a: 'That is deliberate, not a frozen terminal' }, '.'],
    points: [
      { k: 'Your own', v: 'passwd', note: 'asks for the old one first' },
      { k: 'Someone else’s', v: 'sudo passwd NAME', note: 'root is not asked the old one' },
      { k: 'Lock', v: 'passwd -l NAME', note: 'password login refused' },
      { k: 'Stored in', v: '/etc/shadow', note: 'as a hash, never plain text' },
    ],
    session: {
      run: 'passwd',
      prompt: '$',
      lines: [
        { text: 'Changing password for user.' },
        { text: 'Current password: ', n: 1 },
        { text: 'New password: ', n: 2 },
        { text: 'Retype new password: ' },
        { text: 'passwd: password updated successfully', n: 3 },
        { text: 'sudo passwd -S deploy', run: true, n: 4 },
        { text: 'deploy P 2026-09-30 0 99999 7 -1' },
      ],
      notes: [
        { t: 'Prove it is you', d: 'The current password is asked so that someone who finds your terminal unlocked cannot change it.' },
        { t: 'The new one, twice', d: 'Nothing is echoed, not even stars. Typing it twice guards against a slip that would lock you out.' },
        { t: 'Done', d: 'The hash in /etc/shadow has been replaced. Existing sessions stay logged in; the new password applies from the next login.' },
        { t: 'Account status', d: 'P means a usable password is set; L would mean locked. Then the date of the last change and the ageing limits in days.' },
      ],
    },
    recipes: [
      { run: 'sudo passwd deploy', d: 'Sets another user’s password.' },
      { run: 'sudo passwd -l deploy', d: 'Locks the account’s password. -u unlocks it.' },
      { run: 'sudo passwd -e deploy', d: 'Expires the password, forcing a change at next login.' },
      { run: 'sudo chage -l deploy', d: 'Shows when the password was changed and when it expires.' },
    ],
    security: {
      lede: ['Passwords are stored as hashes, and ', { b: 'a weak password’s hash can be cracked' }, '.'],
      points: [
        { t: 'Length beats cleverness', d: 'A long passphrase resists guessing far better than a short password with symbols. Use a password manager and never reuse one across systems.' },
        { t: 'Locking is not disabling', d: 'passwd -l blocks password logins only. The user can still get in with an SSH key. To disable an account fully, also expire it with usermod -e 1.' },
        { t: 'Protect /etc/shadow', d: 'It is readable only by root because anyone holding the hashes can attack them offline at full speed.' },
      ],
    },
    protocols: [],
    related: ['useradd', 'su'],
    footnote: 'The program is set-uid root, which is how an ordinary user is able to update a file only root may write.',
  },
  {
    slug: 'useradd',
    cmd: 'useradd',
    group: 'perm',
    pkg: 'passwd',
    fn: 'Creates a new user account: an entry in /etc/passwd, a group, and optionally a home directory.',
    kicker: 'Linux · users & permissions',
    sub: 'create a user',
    lede: [
      { m: 'useradd' },
      ' adds an account to the system. It is deliberately minimal: ',
      { a: 'without -m no home directory is made' },
      ', and ',
      { b: 'the account has no password until passwd sets one' },
      '.',
    ],
    takeaway: [{ a: 'useradd -m -s /bin/bash name' }, ', then ', { b: 'passwd name' }, ' — two steps to a usable account.'],
    points: [
      { k: 'Home directory', v: '-m', note: 'not created without it' },
      { k: 'Shell', v: '-s /bin/bash', note: 'the default may be /bin/sh' },
      { k: 'Extra groups', v: '-G sudo,docker', note: 'besides the primary one' },
      { k: 'Then', v: 'passwd NAME', note: 'the account starts locked' },
    ],
    session: {
      run: 'useradd -m -s /bin/bash -c "Asha Verma" asha',
      prompt: '#',
      lines: [
        { text: 'passwd asha', run: true, n: 1 },
        { text: 'New password: ' },
        { text: 'passwd: password updated successfully' },
        { text: 'getent passwd asha', run: true, n: 2 },
        { text: 'asha:x:1002:1002:Asha Verma:/home/asha:/bin/bash' },
        { text: 'ls -ld /home/asha', run: true, n: 3 },
        { text: 'drwxr-x--- 2 asha asha 4096 Sep 30 11:20 /home/asha' },
      ],
      notes: [
        { t: 'Give it a password', d: 'useradd printed nothing — it worked — but the account cannot log in until a password or an SSH key is set.' },
        { t: 'The new account record', d: 'Name, an x in place of the password, user id, group id, the comment, the home directory and the login shell.' },
        { t: 'The home directory', d: 'Created by -m and owned by the new user. Mode drwxr-x--- keeps other users out.' },
      ],
    },
    recipes: [
      { run: 'sudo useradd -m -G sudo -s /bin/bash asha', d: 'Creates an administrator who can use sudo.' },
      { run: 'sudo useradd -r -s /usr/sbin/nologin appsvc', d: 'Creates a system account for a service: low id, no login.' },
      { run: 'sudo adduser asha', d: 'On Debian and Ubuntu, a friendlier tool that asks questions and does every step.' },
      { run: 'useradd -D', d: 'Shows the defaults used when no switch is given.' },
    ],
    security: {
      lede: ['Every account is ', { b: 'another way in' }, ', so create them on purpose and keep count.'],
      points: [
        { t: 'One person, one account', d: 'Shared accounts make it impossible to say who did what, and cannot be taken away from one person without affecting the rest.' },
        { t: 'Services get no shell', d: 'An account that exists only to run a program should have /usr/sbin/nologin as its shell, so nobody can log in as it.' },
        { t: 'New accounts are a red flag', d: 'An account nobody remembers creating — especially one in the sudo group — is a classic sign of a break-in. Review /etc/passwd regularly.' },
      ],
    },
    protocols: [],
    related: ['passwd', 'usermod'],
    footnote: 'On Debian-family systems "adduser" is the recommended interactive wrapper around useradd.',
  },
  {
    slug: 'usermod',
    cmd: 'usermod',
    group: 'perm',
    pkg: 'passwd',
    fn: 'Changes an existing account: its groups, shell, home directory, name, or whether it is locked.',
    kicker: 'Linux · users & permissions',
    sub: 'change a user',
    lede: [
      { m: 'usermod' },
      ' modifies an account that already exists. Its commonest use by far is ',
      { a: 'adding a user to a group with -aG' },
      ' — and the commonest mistake is ',
      { b: 'forgetting the a, which removes them from every other group' },
      '.',
    ],
    takeaway: [{ a: '-aG' }, ' adds to a group. ', { b: '-G alone replaces the whole list' }, '. Always type the a.'],
    points: [
      { k: 'Add to a group', v: '-aG GROUP NAME', note: 'append, do not replace' },
      { k: 'Change shell', v: '-s /bin/zsh', note: 'or nologin to block login' },
      { k: 'Lock', v: '-L', note: '-U unlocks' },
      { k: 'Takes effect', v: 'At next login', note: 'for group changes' },
    ],
    session: {
      run: 'usermod -aG docker asha',
      prompt: '#',
      lines: [
        { text: 'id asha', run: true, n: 1 },
        { text: 'uid=1002(asha) gid=1002(asha) groups=1002(asha),998(docker)' },
        { text: 'usermod -s /usr/sbin/nologin olduser', run: true, n: 2 },
        { text: 'usermod -L olduser', run: true, n: 3 },
        { text: 'passwd -S olduser', run: true },
        { text: 'olduser L 2026-08-11 0 99999 7 -1', n: 4 },
      ],
      notes: [
        { t: 'Added, and nothing lost', d: 'asha is now in docker as well as her own group. With -G and no -a, docker would have become her only extra group.' },
        { t: 'Taking away the shell', d: 'nologin as the shell means any login attempt is refused with a polite message.' },
        { t: 'Locking the password', d: '-L puts a ! in front of the password hash, so no password can ever match.' },
        { t: 'L for locked', d: 'The status confirms it. The account and its files remain; it simply cannot be logged in to with a password.' },
      ],
    },
    recipes: [
      { run: 'sudo usermod -aG sudo asha', d: 'Makes a user an administrator on Debian and Ubuntu. On Fedora the group is wheel.' },
      { run: 'sudo gpasswd -d asha docker', d: 'Removes a user from one group.' },
      { run: 'sudo usermod -l newname oldname', d: 'Renames an account.' },
      { run: 'sudo usermod -e 2026-12-31 contractor', d: 'Sets the date on which an account expires.' },
    ],
    security: {
      lede: ['Adding someone to a group ', { b: 'is granting them a privilege' }, ', and should be treated as one.'],
      points: [
        { t: 'The missing -a', d: '"usermod -G docker asha" silently removes asha from sudo and every other group. If that was the only administrator, nobody can fix it without rescue media.' },
        { t: 'Disable fully', d: 'Locking the password does not stop SSH key logins. For a departed user: lock it, expire it with -e 1, and set the shell to nologin.' },
        { t: 'Watch the admin groups', d: 'Changes to the membership of sudo, wheel and docker deserve logging and review; that is how privilege quietly grows.' },
      ],
    },
    protocols: [],
    related: ['useradd', 'id'],
    footnote: 'A user must log out and back in before a new group membership is active in their sessions.',
  },
  {
    slug: 'userdel',
    cmd: 'userdel',
    group: 'perm',
    pkg: 'passwd',
    fn: 'Deletes a user account, and with -r its home directory and mail as well.',
    kicker: 'Linux · users & permissions',
    sub: 'remove a user',
    lede: [
      { m: 'userdel' },
      ' removes an account from the system. ',
      { a: 'Without -r the home directory is left behind' },
      ', owned by a number that no longer has a name — ',
      { b: 'and that a future account may be given' },
      '.',
    ],
    takeaway: ['Decide what happens to the files first: ', { a: 'archive them, then userdel -r' }, '.'],
    points: [
      { k: 'Removes', v: 'The account', note: 'from passwd, shadow and group' },
      { k: 'Home too', v: '-r', note: 'otherwise it stays' },
      { k: 'Refuses if', v: 'The user is logged in', note: 'or has processes running' },
      { k: 'Elsewhere', v: 'Files remain', note: 'find them by user id' },
    ],
    session: {
      run: 'userdel olduser',
      prompt: '#',
      lines: [
        { text: 'userdel: user olduser is currently used by process 4127', n: 1 },
        { text: 'pkill -u olduser', run: true, n: 2 },
        { text: 'userdel -r olduser', run: true, n: 3 },
        { text: 'find / -xdev -nouser 2>/dev/null', run: true, n: 4 },
        { text: '/srv/shared/report-old.xlsx' },
      ],
      notes: [
        { t: 'Still in use', d: 'The account has a process running, so userdel refuses rather than leave it orphaned.' },
        { t: 'Stop their processes', d: 'pkill -u ends everything the user is running.' },
        { t: 'Account and home removed', d: '-r deletes /home/olduser and the mail spool along with the account. Nothing is printed on success.' },
        { t: 'Files left elsewhere', d: '-nouser finds files whose owner id no longer matches any account. This one, outside the home directory, was missed by -r.' },
      ],
    },
    recipes: [
      { run: 'sudo tar -czf olduser-home.tar.gz /home/olduser', d: 'Archives the home directory before deleting the account.' },
      { run: 'sudo userdel -r olduser', d: 'Deletes the account with its home directory.' },
      { run: 'sudo find / -xdev -uid 1003', d: 'Finds every file owned by a given user id.' },
      { run: 'sudo deluser --remove-home olduser', d: 'The Debian and Ubuntu wrapper for the same job.' },
    ],
    security: {
      lede: ['Removing an account is ', { b: 'part of the job when someone leaves' }, ' — and easy to do halfway.'],
      points: [
        { t: 'User ids get reused', d: 'Files left behind are owned by a bare number. The next account created may be given that number and inherit them all.' },
        { t: 'Check for what else they left', d: 'Cron jobs, SSH keys in other accounts’ authorized_keys, and running processes outlive the account unless they are removed too.' },
        { t: 'Disable first, delete later', d: 'Locking an account at once and deleting it after a retention period keeps the evidence and the files while removing the access.' },
      ],
    },
    protocols: [],
    related: ['useradd', 'usermod'],
    footnote: 'userdel does not remove the user’s crontab on every system; check /var/spool/cron.',
  },
  {
    slug: 'groupadd',
    cmd: 'groupadd',
    group: 'perm',
    pkg: 'passwd',
    fn: 'Creates a new group, so that a set of users can be given the same access to files.',
    kicker: 'Linux · users & permissions',
    sub: 'create a group',
    lede: [
      { m: 'groupadd' },
      ' adds a group to the system. A group is ',
      { a: 'a named set of users who can be granted access together' },
      ': create it, add people to it, and ',
      { b: 'hand a directory to the group instead of to each person' },
      '.',
    ],
    takeaway: ['Three steps to a shared directory: ', { a: 'groupadd, usermod -aG, chgrp' }, '.'],
    points: [
      { k: 'Creates', v: 'An entry in /etc/group', note: 'with the next free id' },
      { k: 'Add members', v: 'usermod -aG', note: 'or gpasswd -a' },
      { k: 'Remove it', v: 'groupdel NAME', note: 'files keep the bare id' },
      { k: 'List members', v: 'getent group NAME', note: 'no root needed' },
    ],
    session: {
      run: 'groupadd developers',
      prompt: '#',
      lines: [
        { text: 'usermod -aG developers asha', run: true, n: 1 },
        { text: 'getent group developers', run: true, n: 2 },
        { text: 'developers:x:1005:asha' },
        { text: 'mkdir /srv/project && chgrp developers /srv/project', run: true, n: 3 },
        { text: 'chmod 2775 /srv/project', run: true, n: 4 },
        { text: 'ls -ld /srv/project', run: true },
        { text: 'drwxrwsr-x 2 root developers 4096 Sep 30 11:45 /srv/project' },
      ],
      notes: [
        { t: 'Put someone in it', d: 'The group exists but is empty until members are added.' },
        { t: 'The group record', d: 'Name, a password placeholder, the group id, and the list of members.' },
        { t: 'Give the group a directory', d: 'The directory now belongs to the developers group.' },
        { t: 'The leading 2 is set-gid', d: 'Shown as the s in rws. Files created inside inherit the developers group, so everything in the directory stays shared.' },
      ],
    },
    recipes: [
      { run: 'sudo gpasswd -a ravi developers', d: 'Adds a user to a group.' },
      { run: 'sudo gpasswd -d ravi developers', d: 'Removes a user from a group.' },
      { run: 'sudo groupdel developers', d: 'Deletes a group.' },
      { run: 'cat /etc/group | cut -d: -f1', d: 'Lists every group on the system.' },
    ],
    security: {
      lede: ['Groups are ', { b: 'how access is granted without handing out root' }, '.'],
      points: [
        { t: 'Grant to groups, not to everyone', d: 'A shared directory owned by a group and closed to others is the right answer. chmod 777 is the wrong one.' },
        { t: 'Keep membership current', d: 'People change teams. A group whose membership is never reviewed slowly comes to include everyone.' },
        { t: 'Set-gid directories', d: 'They keep shared files in the right group, but check that only intended members can write there — whoever can, can alter everyone’s files.' },
      ],
    },
    protocols: [],
    related: ['chgrp', 'usermod'],
    footnote: 'System groups, made with -r, take low ids and are meant for services rather than people.',
  },
];

export const switches: Record<string, LinuxSwitch[]> = {
  whoami: [],
  id: [
    { flag: '-u', d: 'Print only the user id.' },
    { flag: '-g', d: 'Print only the primary group id.' },
    { flag: '-G', d: 'Print every group id.' },
    { flag: '-n', d: 'With -u, -g or -G, print names instead of numbers.' },
    { flag: '-r', d: 'Print the real id rather than the effective one.' },
  ],
  su: [
    { flag: '-', d: 'Start a login shell: the target’s environment and home directory. Also written -l.' },
    { flag: '-c COMMAND', d: 'Run one command as the target user, then return.' },
    { flag: '-s SHELL', d: 'Use this shell instead of the target’s default.' },
    { flag: '-p', d: 'Preserve your current environment.' },
  ],
  passwd: [
    { flag: '-l', d: 'Lock the account’s password.' },
    { flag: '-u', d: 'Unlock it.' },
    { flag: '-e', d: 'Expire the password, forcing a change at next login.' },
    { flag: '-d', d: 'Delete the password, leaving the account with none.' },
    { flag: '-S', d: 'Show the account’s password status.' },
    { flag: '-x DAYS', d: 'Set the maximum number of days a password may be used.' },
  ],
  useradd: [
    { flag: '-m', d: 'Create the home directory.' },
    { flag: '-s SHELL', d: 'Set the login shell.' },
    { flag: '-G GROUPS', d: 'Supplementary groups, comma-separated.' },
    { flag: '-c COMMENT', d: 'A description, usually the full name.' },
    { flag: '-d DIR', d: 'Use this as the home directory.' },
    { flag: '-r', d: 'Create a system account, with a low id.' },
    { flag: '-u UID', d: 'Use this user id.' },
    { flag: '-e DATE', d: 'Set the date the account expires.' },
  ],
  usermod: [
    { flag: '-aG GROUPS', d: 'Append the user to these groups, keeping the existing ones.' },
    { flag: '-G GROUPS', d: 'Replace the supplementary group list entirely.' },
    { flag: '-s SHELL', d: 'Change the login shell.' },
    { flag: '-L', d: 'Lock the password. -U unlocks it.' },
    { flag: '-l NAME', d: 'Change the login name.' },
    { flag: '-d DIR -m', d: 'Change the home directory and move its contents.' },
    { flag: '-e DATE', d: 'Set the account’s expiry date.' },
  ],
  userdel: [
    { flag: '-r', d: 'Remove the home directory and mail spool too.' },
    { flag: '-f', d: 'Force removal even if the user is logged in. Dangerous.' },
  ],
  groupadd: [
    { flag: '-g GID', d: 'Use this group id.' },
    { flag: '-r', d: 'Create a system group, with a low id.' },
    { flag: '-f', d: 'Exit successfully if the group already exists.' },
  ],
};
